[package]
name = "covalence-nucleus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Portable trusted core for Nucleus"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1"
covalence-lib-crypto = { path = "../lib/crypto" }
covalence-lib-error = { path = "../lib/error" }
covalence-lib-hash = { path = "../lib/hash", default-features = false, features = ["blake3"] }
covalence-lib-rand = { path = "../lib/rand" }
covalence-lib-sqlite = { path = "../lib/sqlite", features = ["vfs-register"] }
covalence-neutron = { path = "../neutron" }

[target.'cfg(target_os = "wasi")'.dependencies]
wit-bindgen-rt = { version = "=0.44.0", features = ["bitflags"] }

[package.metadata.component]
package = "nucleus:smoke"

[package.metadata.component.dependencies]

[lints]
workspace = true
