[package]
name = "covalence-lib-serde"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Serialization primitives for Nucleus"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
