[package]
name = "covalence-proton"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Execution instances for Nucleus"
publish = false

[lints]
workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmtime = { version = "=46.0.1", default-features = false, features = ["component-model", "cranelift", "runtime", "std"] }
