[package]
name = "covalence-logic-bdd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Binary decision diagrams for Covalence userspace"
publish = false

[dependencies]
covalence-logic-sat = { path = "../sat" }

[lints]
workspace = true
