[workspace]
members = [
  "crates/lib/error",
  "crates/lib/crypto",
  "crates/lib/hash",
  "crates/lib/rand",
  "crates/lib/sqlite",
  "crates/data/basic",
  "crates/data/container",
  "crates/proton",
  "crates/neutron",
  "crates/nucleus",
  "crates/hol-proof-guest-beta",
  "crates/hol-proof-guest-eta",
  "crates/hol-proof-guest-schematic-binding",
  "crates/hol-proof-guest-conversions",
  "crates/repl",
  "crates/bin/nucleus",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "CC0-1.0"
rust-version = "1.97"
version = "0.0.0"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
