"""Compiled primitives exposed through the public Covalence modules."""

# PyO3 does not emit stubs, so this file is maintained alongside
# `crates/ffi/python/src`. `tests/test_typing.py` checks both directions for
# drift between the declarations and the compiled module.
#
# Buffer intentionally accepts bytes, bytearray, memoryview, and other
# contiguous buffer exporters.

from collections.abc import Buffer, Iterable, Sequence

__version__: str

COV: ContextKey
COV_ROOT: O256
COV_ROOT_CTX_KEY: str

class InvalidLengthError(ValueError):
    """A value had the wrong number of bytes or encoded characters."""

class InvalidHexError(ValueError):
    """A hexadecimal string contained something that is not a hexadecimal digit."""

class InvalidBase64Error(ValueError):
    """A Base64 string was outside the alphabet, mispadded, or non-canonical."""

class LratError(ValueError):
    """A typed LRAT operation was rejected."""

class CnfError(ValueError):
    """A conjunctive-normal-form value was malformed."""

class Literal:
    """A signed, nonzero propositional literal."""

    value: int
    variable: int

    def __init__(self, value: int, /) -> None: ...
    def __int__(self) -> int: ...
    def __neg__(self) -> Literal: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Literal, /) -> bool: ...
    def __le__(self, other: Literal, /) -> bool: ...
    def __gt__(self, other: Literal, /) -> bool: ...
    def __ge__(self, other: Literal, /) -> bool: ...

class Clause:
    """A disjunction of literals."""

    literals: list[int]

    def __init__(self, literals: Sequence[int], /) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

class Formula:
    """A conjunction of clauses."""

    clauses: list[Clause]
    max_variable: int

    def __init__(self, clauses: Sequence[Clause], /) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...

class RatGroup:
    """One explicitly delimited RAT resolvent check."""

    opposing_clause_id: int
    resolvent_rup_hints: list[int]

    def __init__(
        self, opposing_clause_id: int, resolvent_rup_hints: Sequence[int], /
    ) -> None: ...
    def __repr__(self) -> str: ...

class Step:
    """One typed LRAT proof step."""

    kind: str
    id: int | None
    clause: Clause | None
    ids: list[int] | None
    ordered_hints: list[int] | None

    @staticmethod
    def rup(id: int, clause: Clause, ordered_hints: Sequence[int], /) -> Step: ...
    @staticmethod
    def rat(
        id: int,
        clause: Clause,
        pivot: Literal,
        prefix_rup_hints: Sequence[int],
        groups: Sequence[RatGroup],
        /,
    ) -> Step: ...
    @staticmethod
    def forget(ids: Sequence[int], /) -> Step: ...

class Kernel:
    """A parser-independent typed LRAT clause kernel."""

    def __init__(self, initial: Formula, /) -> None: ...
    @property
    def refuted(self) -> bool: ...
    @property
    def high_water(self) -> int: ...
    def clause(self, id: int, /) -> list[int] | None: ...
    def learn_rup(
        self, id: int, clause: Clause, ordered_hints: Sequence[int], /
    ) -> None: ...
    def learn_rat(
        self,
        id: int,
        clause: Clause,
        pivot: Literal,
        prefix_rup_hints: Sequence[int],
        groups: Sequence[RatGroup],
        /,
    ) -> None: ...
    def forget(self, ids: Sequence[int], /) -> None: ...
    def verify(
        self,
        proof: str | Buffer | Iterable[Step],
        /,
    ) -> None: ...

def parse_text(text: str, /) -> list[Step]: ...
def parse_binary(proof: Buffer, /) -> list[Step]: ...

class Obj:
    """A fixed-width Covalence identifier, of no particular namespace.

    The base of every namespace class, and not instantiable itself. Comparison
    stops at the namespace boundary: `==` between two namespaces is `False` and
    `<` raises `TypeError`, whatever the bytes are.
    """

    def hex(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Obj, /) -> bool: ...
    def __le__(self, other: Obj, /) -> bool: ...
    def __gt__(self, other: Obj, /) -> bool: ...
    def __ge__(self, other: Obj, /) -> bool: ...

class O256(Obj):
    """A standard Covalence 256-bit object."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> O256: ...
    @staticmethod
    def from_base64(text: str, /) -> O256: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> O256: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> O256: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> O256: ...
    @staticmethod
    def keyed(key: O256, data: Buffer, /) -> O256: ...
    @staticmethod
    def derive_key(context: str, data: Buffer, /) -> O256: ...
    @staticmethod
    def with_context(key: ContextKey, data: Buffer, /) -> O256: ...
    @staticmethod
    def root() -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Blake3(Obj):
    """An unkeyed BLAKE3 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Blake3: ...
    @staticmethod
    def from_base64(text: str, /) -> Blake3: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Blake3: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Blake3: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Blake3: ...
    def to_o256(self) -> O256: ...

class Sha256(Obj):
    """A SHA-256 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha256: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha256: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Sha256: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Sha256: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha256: ...

class ContextKey(Obj):
    """A BLAKE3 derive-key context key."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> ContextKey: ...
    @staticmethod
    def from_base64(text: str, /) -> ContextKey: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> ContextKey: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> ContextKey: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def derive(context: str, /) -> ContextKey: ...
    def root(self) -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Sha1(Obj):
    """A raw SHA-1 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha1: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha1: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Sha1: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Sha1: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha1: ...
    def to_git(self) -> GitHash: ...

class GitHash(Obj):
    """A traditional Git SHA-1 object name."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> GitHash: ...
    @staticmethod
    def from_base64(text: str, /) -> GitHash: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> GitHash: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> GitHash: ...
    def to_raw_cid(self) -> str: ...
    def to_sha1(self) -> Sha1: ...

def git_object(object_type: str, data: Buffer, /) -> GitHash: ...
def git_blob(data: Buffer, /) -> GitHash: ...
