"""Compiled primitives exposed through the public Covalence modules."""

# PyO3 does not emit stubs, so this file is maintained alongside
# `crates/ffi/python/src`. `tests/test_typing.py` checks both directions for
# drift between the declarations and the compiled module.
#
# Buffer intentionally accepts bytes, bytearray, memoryview, and other
# contiguous buffer exporters.

from collections.abc import Buffer, Iterable, Sequence

__version__: str

class Cbor:
    """An immutable, structurally shared CBOR value."""

    kind: str
    value: (
        int
        | bytes
        | str
        | tuple[Cbor, ...]
        | tuple[int, Cbor]
        | tuple[tuple[Cbor, Cbor], ...]
    )
    __hash__: None

    def __init__(self, value: object, /) -> None: ...
    @staticmethod
    def from_python(value: object, /) -> Cbor: ...
    @staticmethod
    def integer(value: int, /) -> Cbor: ...
    @staticmethod
    def bytes(value: Buffer, /) -> Cbor: ...
    @staticmethod
    def text(value: str, /) -> Cbor: ...
    @staticmethod
    def simple(value: int, /) -> Cbor: ...
    @staticmethod
    def bool(value: bool, /) -> Cbor: ...
    @staticmethod
    def null() -> Cbor: ...
    @staticmethod
    def undefined() -> Cbor: ...
    @staticmethod
    def float16(bits: int, /) -> Cbor: ...
    @staticmethod
    def float32(bits: int, /) -> Cbor: ...
    @staticmethod
    def float64(bits: int, /) -> Cbor: ...
    @staticmethod
    def tag(tag: int, value: Cbor, /) -> Cbor: ...
    @staticmethod
    def array(values: Sequence[Cbor], /) -> Cbor: ...
    @staticmethod
    def map(entries: Sequence[tuple[Cbor, Cbor]], /) -> Cbor: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...

COV: ContextKey
COV_ROOT: O256
COV_ROOT_CTX_KEY: str

class InvalidLengthError(ValueError):
    """A value had the wrong number of bytes or encoded characters."""

class InvalidHexError(ValueError):
    """A hexadecimal string contained something that is not a hexadecimal digit."""

class InvalidBase64Error(ValueError):
    """A Base64 string was outside the alphabet, mispadded, or non-canonical."""

class CasCheckError(ValueError):
    """A CAS assertion or proof failed validation."""

class CasDigestMismatchError(CasCheckError):
    """A whole-object CAS assertion carried the wrong content hash."""

class CasLookupError(LookupError):
    """A CAS lookup failed."""

class CasNotFoundError(CasLookupError):
    """A CAS does not contain the requested address."""

class CasAddressMismatchError(CasLookupError):
    """A CAS returned a checked fact for another address."""

class LratError(ValueError):
    """A typed LRAT operation was rejected."""

class MetamathError(ValueError):
    """A Metamath database could not be parsed or validated."""

class Expression:
    """A typecode followed by a flat Metamath symbol sequence."""

    typecode: str
    body: list[str]
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Assertion:
    """An inspectable Metamath axiom or theorem."""

    label: str
    conclusion: Expression
    hypothesis_labels: list[str]
    disjoint_pairs: list[tuple[str, str]]
    proof_encoding: str | None
    is_theorem: bool
    def __repr__(self) -> str: ...

class Database:
    """A parsed Metamath database."""

    statement_count: int
    assertion_count: int
    theorem_count: int
    @staticmethod
    def parse(source: str, /) -> Database: ...
    @staticmethod
    def load(path: str, /) -> Database: ...
    def validate(self) -> int: ...
    def symbols(self, kind: str | None = None, /) -> list[str]: ...
    def labels(self) -> list[str]: ...
    def assertion(self, label: str, /) -> Assertion | None: ...
    def assertions(self) -> list[Assertion]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class CnfError(ValueError):
    """A conjunctive-normal-form value was malformed."""

class Literal:
    """A signed, nonzero propositional literal."""

    value: int
    variable: int

    def __init__(self, value: int, /) -> None: ...
    def __int__(self) -> int: ...
    def __neg__(self) -> Literal: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Literal, /) -> bool: ...
    def __le__(self, other: Literal, /) -> bool: ...
    def __gt__(self, other: Literal, /) -> bool: ...
    def __ge__(self, other: Literal, /) -> bool: ...

class Clause:
    """A disjunction of literals."""

    literals: list[int]

    def __init__(self, literals: Sequence[int], /) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Clause, /) -> bool: ...
    def __le__(self, other: Clause, /) -> bool: ...
    def __gt__(self, other: Clause, /) -> bool: ...
    def __ge__(self, other: Clause, /) -> bool: ...

class Formula:
    """A conjunction of clauses."""

    clauses: list[Clause]
    max_variable: int

    def __init__(self, clauses: Sequence[Clause], /) -> None: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Formula, /) -> bool: ...
    def __le__(self, other: Formula, /) -> bool: ...
    def __gt__(self, other: Formula, /) -> bool: ...
    def __ge__(self, other: Formula, /) -> bool: ...

class RatGroup:
    """One explicitly delimited RAT resolvent check."""

    opposing_clause_id: int
    resolvent_rup_hints: list[int]

    def __init__(
        self, opposing_clause_id: int, resolvent_rup_hints: Sequence[int], /
    ) -> None: ...
    def __repr__(self) -> str: ...

class Step:
    """One typed LRAT proof step."""

    kind: str
    id: int | None
    clause: Clause | None
    ids: list[int] | None
    ordered_hints: list[int] | None

    @staticmethod
    def rup(id: int, clause: Clause, ordered_hints: Sequence[int], /) -> Step: ...
    @staticmethod
    def rat(
        id: int,
        clause: Clause,
        pivot: Literal,
        prefix_rup_hints: Sequence[int],
        groups: Sequence[RatGroup],
        /,
    ) -> Step: ...
    @staticmethod
    def forget(ids: Sequence[int], /) -> Step: ...

class Kernel:
    """A parser-independent typed LRAT clause kernel."""

    def __init__(self, initial: Formula, /) -> None: ...
    @property
    def refuted(self) -> bool: ...
    @property
    def high_water(self) -> int: ...
    def clause(self, id: int, /) -> list[int] | None: ...
    def learn_rup(
        self, id: int, clause: Clause, ordered_hints: Sequence[int], /
    ) -> None: ...
    def learn_rat(
        self,
        id: int,
        clause: Clause,
        pivot: Literal,
        prefix_rup_hints: Sequence[int],
        groups: Sequence[RatGroup],
        /,
    ) -> None: ...
    def forget(self, ids: Sequence[int], /) -> None: ...
    def verify(
        self,
        proof: str | Buffer | Iterable[Step],
        /,
    ) -> None: ...

def parse_text(text: str, /) -> list[Step]: ...
def parse_binary(proof: Buffer, /) -> list[Step]: ...

class Obj:
    """A fixed-width Covalence identifier, of no particular namespace.

    The base of every namespace class, and not instantiable itself. Comparison
    stops at the namespace boundary: `==` between two namespaces is `False` and
    `<` raises `TypeError`, whatever the bytes are.
    """

    def hex(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Obj, /) -> bool: ...
    def __le__(self, other: Obj, /) -> bool: ...
    def __gt__(self, other: Obj, /) -> bool: ...
    def __ge__(self, other: Obj, /) -> bool: ...

class O256(Obj):
    """A standard Covalence 256-bit object."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> O256: ...
    @staticmethod
    def from_base64(text: str, /) -> O256: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> O256: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> O256: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> O256: ...
    @staticmethod
    def keyed(key: O256, data: Buffer, /) -> O256: ...
    @staticmethod
    def derive_key(context: str, data: Buffer, /) -> O256: ...
    @staticmethod
    def with_context(key: ContextKey, data: Buffer, /) -> O256: ...
    @staticmethod
    def root() -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Blake3(Obj):
    """An unkeyed BLAKE3 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Blake3: ...
    @staticmethod
    def from_base64(text: str, /) -> Blake3: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Blake3: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Blake3: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Blake3: ...
    def to_o256(self) -> O256: ...

class Sha256(Obj):
    """A SHA-256 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha256: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha256: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Sha256: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Sha256: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha256: ...

class ContextKey(Obj):
    """A BLAKE3 derive-key context key."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> ContextKey: ...
    @staticmethod
    def from_base64(text: str, /) -> ContextKey: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> ContextKey: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> ContextKey: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def derive(context: str, /) -> ContextKey: ...
    def root(self) -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Sha1(Obj):
    """A raw SHA-1 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha1: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha1: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> Sha1: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> Sha1: ...
    def to_raw_cid(self) -> str: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha1: ...
    def to_git(self) -> GitHash: ...

class GitHash(Obj):
    """A traditional Git SHA-1 object name."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> GitHash: ...
    @staticmethod
    def from_base64(text: str, /) -> GitHash: ...
    @staticmethod
    def from_multihash(data: Buffer, /) -> GitHash: ...
    def to_multihash(self) -> bytes: ...
    @staticmethod
    def from_raw_cid(text: str, /) -> GitHash: ...
    def to_raw_cid(self) -> str: ...
    def to_sha1(self) -> Sha1: ...

def git_object(object_type: str, data: Buffer, /) -> GitHash: ...
def git_blob(data: Buffer, /) -> GitHash: ...

class CasAssertion:
    """An ordinary unchecked claim about one complete CAS blob."""

    hash: O256
    blob: bytes
    def __init__(self, hash: O256, blob: Buffer, /) -> None: ...
    def check(self) -> CasFact: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...

class CasFact:
    """An opaque checked fact about one complete CAS blob."""

    hash: O256
    blob: bytes
    assertion: CasAssertion
    def __init__(self, hash: O256, blob: Buffer, /) -> None: ...
    @staticmethod
    def from_assertion(assertion: CasAssertion, /) -> CasFact: ...
    @staticmethod
    def from_bytes(blob: Buffer, /) -> CasFact: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...

class IndexCas:
    """An insertion-ordered userspace CAS with stable integer IDs."""

    def __init__(self) -> None: ...
    def put(self, blob: Buffer, /) -> int: ...
    def insert(self, fact: CasFact, /) -> int: ...
    def id(self, address: O256, /) -> int | None: ...
    def id_bytes(self, blob: Buffer, /) -> int | None: ...
    def fact(self, id: int, /) -> CasFact | None: ...
    def get(self, address: O256, /) -> bytes: ...
    def get_fact(self, address: O256, /) -> CasFact: ...
    def contains(self, address: O256, /) -> bool: ...
    def remove(self, address: O256, /) -> bool: ...
    def items(self) -> list[tuple[int, CasFact]]: ...
    def __len__(self) -> int: ...

def get_checked(provider: object, address: O256, /) -> CasFact: ...
