"""Type information for the compiled module.

PyO3 does not emit stubs, so this file is written by hand and has to be kept in
step with `crates/ffi/python/src`. `tests/test_typing.py` checks that every name
the module exports appears here, and that every member declared here exists on
the class that is built.

`Buffer` rather than `bytes` for byte input: `bytes`, `bytearray`, `memoryview`,
and anything else exporting a contiguous buffer are all accepted.
"""

from collections.abc import Buffer, Iterator
from typing import NoReturn

__version__: str

COV: ContextKey
COV_ROOT: O256
COV_ROOT_CTX_KEY: str

class InvalidLengthError(ValueError):
    """A value had the wrong number of bytes or encoded characters."""

class InvalidHexError(ValueError):
    """A hexadecimal string contained something that is not a hexadecimal digit."""

class InvalidBase64Error(ValueError):
    """A Base64 string was outside the alphabet, mispadded, or non-canonical."""

class Obj:
    """A fixed-width Covalence identifier, of no particular namespace.

    The base of every namespace class, and not instantiable itself. Comparison
    stops at the namespace boundary: `==` between two namespaces is `False` and
    `<` raises `TypeError`, whatever the bytes are.
    """

    def hex(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Obj, /) -> bool: ...
    def __le__(self, other: Obj, /) -> bool: ...
    def __gt__(self, other: Obj, /) -> bool: ...
    def __ge__(self, other: Obj, /) -> bool: ...

class O256(Obj):
    """A standard Covalence 256-bit object."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> O256: ...
    @staticmethod
    def from_base64(text: str, /) -> O256: ...
    @staticmethod
    def hash(data: Buffer, /) -> O256: ...
    @staticmethod
    def keyed(key: O256, data: Buffer, /) -> O256: ...
    @staticmethod
    def derive_key(context: str, data: Buffer, /) -> O256: ...
    @staticmethod
    def with_context(key: ContextKey, data: Buffer, /) -> O256: ...
    @staticmethod
    def root() -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Blake3(Obj):
    """An unkeyed BLAKE3 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Blake3: ...
    @staticmethod
    def from_base64(text: str, /) -> Blake3: ...
    @staticmethod
    def hash(data: Buffer, /) -> Blake3: ...
    def to_o256(self) -> O256: ...

class Sha256(Obj):
    """A SHA-256 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha256: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha256: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha256: ...

class ContextKey(Obj):
    """A BLAKE3 derive-key context key."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> ContextKey: ...
    @staticmethod
    def from_base64(text: str, /) -> ContextKey: ...
    @staticmethod
    def derive(context: str, /) -> ContextKey: ...
    def root(self) -> O256: ...
    def tag(self, data: Buffer, /) -> O256: ...

class Sha1(Obj):
    """A raw SHA-1 digest."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> Sha1: ...
    @staticmethod
    def from_base64(text: str, /) -> Sha1: ...
    @staticmethod
    def hash(data: Buffer, /) -> Sha1: ...
    def to_git(self) -> GitHash: ...

class GitHash(Obj):
    """A traditional Git SHA-1 object name."""

    BYTES: int

    def __init__(self, data: Buffer, /) -> None: ...
    @staticmethod
    def from_hex(text: str, /) -> GitHash: ...
    @staticmethod
    def from_base64(text: str, /) -> GitHash: ...
    def to_sha1(self) -> Sha1: ...

def git_object(object_type: str, data: Buffer, /) -> GitHash: ...
def git_blob(data: Buffer, /) -> GitHash: ...

class InvalidJsonError(ValueError):
    """Text was not strict JSON: malformed, trailing, or a duplicate key."""

class Json:
    """An immutable JSON document that acts like dicts and lists.

    Access unwraps leaves and wraps containers: indexing a nested object or
    array returns another `Json` sharing the same tree, and anything else
    returns the plain Python value.
    """

    def __init__(self, value: object, /) -> None: ...
    @staticmethod
    def loads(text: str, /) -> Json: ...
    def dumps(self, *, pretty: bool = False) -> str: ...
    def unwrap(self) -> object: ...
    @property
    def kind(self) -> str: ...
    def get(self, key: str, default: object = None, /) -> object: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[object]: ...
    def items(self) -> list[tuple[str, object]]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: str | int, /) -> object: ...
    def __contains__(self, item: object, /) -> bool: ...
    def __iter__(self) -> Iterator[object]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    # JSON values are unordered; PyO3 registers the slots, which raise.
    def __lt__(self, other: object, /) -> NoReturn: ...
    def __le__(self, other: object, /) -> NoReturn: ...
    def __gt__(self, other: object, /) -> NoReturn: ...
    def __ge__(self, other: object, /) -> NoReturn: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
