[package]
name = "covalence-lib-cbor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CBOR serialization for Nucleus"
publish = false

[features]
default = ["serde", "drisl"]
serde = ["dep:ciborium"]
drisl = ["dep:ipld-core", "dep:serde_ipld_dagcbor"]

[dependencies]
ciborium = { version = "0.2.2", optional = true }
ipld-core = { version = "0.4.3", features = ["serde"], optional = true }
serde_ipld_dagcbor = { version = "0.7.0", optional = true }

[lints]
workspace = true
