use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use cargo_lock::Lockfile;
use cargo_metadata::{DependencyKind, Metadata, Node, Package, PackageId, Target, TargetKind};
use color_eyre::eyre::{Result, WrapErr, bail};
use minijinja::{Environment, context};
use serde::Serialize;

use crate::cargo;

const HEADER: &str = "# @generated by `glu buck sync`; do not edit.\n\
                      # Cargo.toml and Cargo.lock are authoritative.\n";

const WORKSPACE_TEMPLATE: &str = r#"{{ header }}
_PACKAGE_FILES = glob(
    ["**"],
    exclude = ["BUCK", "target/**"],
)

# Every file in the package, because `include_bytes!` and `include_str!` can
# name any of them and a glob by extension silently misses the ones it did not
# think of. Coarser invalidation than listing extensions, and correct.
_RUST_SOURCES = glob(
    ["**"],
    exclude = ["BUCK", "target/**"],
)

filegroup(
    name = "package_files",
    srcs = _PACKAGE_FILES,
    visibility = ["PUBLIC"],
)

{% for target in targets -%}
{{ target.rule }}(
    name = {{ target.name|tojson }},
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.features %}
    features = [
{%- for feature in target.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if target.unit_test %}
    tests = [":{{ target.name }}-unit-test"],
{%- endif %}
{%- if target.proc_macro %}
    proc_macro = True,
{%- endif %}
{%- if target.named_deps %}
    named_deps = {
{%- for name, dependency in target.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
    visibility = ["PUBLIC"],
)

{% if target.unit_test -%}
rust_test(
    name = "{{ target.name }}-unit-test",
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.features %}
    features = [
{%- for feature in target.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if target.test_named_deps %}
    named_deps = {
{%- for name, dependency in target.test_named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
    visibility = ["PUBLIC"],
)

{% endif -%}
{% endfor -%}
"#;

const EXTERNAL_TEMPLATE: &str = r#"{{ header }}
load(":dependencies.json", dependencies = "value")
load("//buck/cargo:dependencies.bzl", "declare_cargo_dependencies")

export_file(
    name = "crates-json",
    src = "crates.json",
    visibility = ["PUBLIC"],
)

export_file(
    name = "dependencies-json",
    src = "dependencies.json",
    visibility = ["PUBLIC"],
)

declare_cargo_dependencies(dependencies)
"#;

#[derive(Serialize)]
struct RustTarget {
    rule: &'static str,
    name: String,
    crate_name: String,
    crate_root: String,
    edition: String,
    features: Vec<String>,
    named_deps: Vec<(String, String)>,
    /// What the test rule links: the same plus `[dev-dependencies]`.
    ///
    /// Kept separate so a dev-dependency cannot leak into the library, which
    /// is the whole reason Cargo distinguishes them.
    test_named_deps: Vec<(String, String)>,
    proc_macro: bool,
    buildscript: Option<String>,
    env: Vec<(String, String)>,
    /// What the test rule gets: the same plus `CARGO_BIN_EXE_*`.
    ///
    /// Separate from `env` because pointing the *library* at its package's
    /// binary makes the library depend on the binary that depends on it.
    test_env: Vec<(String, String)>,
    unit_test: bool,
}

#[derive(Serialize)]
struct ExternalPackage {
    id: String,
    name: String,
    version: String,
    checksum: String,
    edition: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    features: Vec<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    env: BTreeMap<String, String>,
    targets: Vec<ExternalTarget>,
    #[serde(skip_serializing_if = "Option::is_none")]
    buildscript: Option<Buildscript>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ExternalDependencies {
    generated_by: &'static str,
    packages: Vec<ExternalPackage>,
    roots: Vec<DependencyRoot>,
    edges: Vec<DependencyEdge>,
}

#[derive(Serialize)]
struct DependencyRoot {
    id: String,
    name: String,
    category: &'static str,
    dependencies: Vec<String>,
}

#[derive(Serialize)]
struct ExternalTarget {
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_root: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    named_deps: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    proc_macro: bool,
}

#[derive(Serialize)]
struct Buildscript {
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_root: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    named_deps: BTreeMap<String, String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WorkspaceData {
    generated_by: &'static str,
    crates: Vec<WorkspaceCrate>,
    edges: Vec<DependencyEdge>,
}

#[derive(Serialize)]
struct WorkspaceCrate {
    id: String,
    name: String,
    version: String,
    path: String,
    category: &'static str,
    targets: Vec<WorkspaceCrateTarget>,
}

#[derive(Serialize)]
struct WorkspaceCrateTarget {
    name: String,
    kinds: Vec<String>,
}

#[derive(Serialize)]
struct DependencyEdge {
    source: String,
    target: String,
    kinds: Vec<String>,
}

struct Graph<'a> {
    metadata: &'a Metadata,
    nodes: BTreeMap<&'a PackageId, &'a Node>,
    packages: BTreeMap<&'a PackageId, &'a Package>,
    workspace: BTreeSet<&'a PackageId>,
    dependency_cell: &'a str,
}

pub(crate) fn sync(root: &Path) -> Result<usize> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut changed = 0;
    for (path, contents) in files {
        let path = root.join(path);
        if fs::read_to_string(&path).ok().as_deref() == Some(&contents) {
            continue;
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .wrap_err_with(|| format!("could not create {}", parent.display()))?;
        }
        fs::write(&path, contents)
            .wrap_err_with(|| format!("could not write {}", path.display()))?;
        changed += 1;
    }
    for path in discovered_generated_files(root)?.difference(&expected) {
        fs::remove_file(root.join(path))
            .wrap_err_with(|| format!("could not remove stale {}", path.display()))?;
        changed += 1;
    }
    Ok(changed)
}

pub(crate) fn check(root: &Path) -> Result<()> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut stale = files
        .into_iter()
        .filter_map(|(path, expected)| {
            let actual = fs::read_to_string(root.join(&path)).ok();
            (actual.as_deref() != Some(&expected)).then_some(path)
        })
        .collect::<Vec<_>>();
    stale.extend(
        discovered_generated_files(root)?
            .difference(&expected)
            .cloned(),
    );
    stale.sort();
    if !stale.is_empty() {
        bail!(
            "generated Buck files are stale:\n{}\nrun `glu buck sync`",
            stale
                .iter()
                .map(|path| format!("  - {}", path.display()))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    Ok(())
}

fn discovered_generated_files(root: &Path) -> Result<BTreeSet<PathBuf>> {
    let mut directories = ["crates", "tools/glu", "buck/cargo"]
        .map(|path| root.join(path))
        .to_vec();
    let mut files = BTreeSet::new();
    while let Some(directory) = directories.pop() {
        for entry in fs::read_dir(&directory)
            .wrap_err_with(|| format!("could not read {}", directory.display()))?
        {
            let entry = entry.wrap_err("could not read Buck source directory")?;
            let path = entry.path();
            if entry
                .file_type()
                .wrap_err_with(|| format!("could not inspect {}", path.display()))?
                .is_dir()
            {
                if entry.file_name() != "target" {
                    directories.push(path);
                }
            } else if entry.file_name() == "BUCK"
                && fs::read_to_string(&path).is_ok_and(|contents| contents.starts_with(HEADER))
            {
                files.insert(
                    path.strip_prefix(root)
                        .expect("discovered path is inside the repository")
                        .to_owned(),
                );
            }
        }
    }
    Ok(files)
}

fn generated_files(root: &Path) -> Result<Vec<(PathBuf, String)>> {
    let mut files = Vec::new();
    files.extend(generate_workspace(
        root,
        &root.join("Cargo.toml"),
        "buck/cargo/production",
    )?);
    files.extend(generate_workspace(
        root,
        &root.join("tools/glu/Cargo.toml"),
        "buck/cargo/glu",
    )?);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(files)
}

fn generate_workspace(
    root: &Path,
    manifest: &Path,
    dependency_cell: &str,
) -> Result<Vec<(PathBuf, String)>> {
    let metadata = cargo::load_manifest(root, manifest)?;
    let graph = Graph::new(&metadata, dependency_cell)?;
    let lockfile = Lockfile::load(
        manifest
            .parent()
            .expect("manifest has a parent")
            .join("Cargo.lock"),
    )
    .wrap_err_with(|| format!("could not read lockfile for {}", manifest.display()))?;
    let checksums = lockfile
        .packages
        .iter()
        .filter_map(|package| {
            package.checksum.as_ref().map(|checksum| {
                (
                    (package.name.to_string(), package.version.to_string()),
                    checksum.to_string(),
                )
            })
        })
        .collect::<BTreeMap<_, _>>();

    let mut files = Vec::new();
    for package in graph.workspace_packages() {
        let directory = package_directory(root, package)?;
        let targets = package
            .targets
            .iter()
            .filter_map(|target| graph.workspace_target(package, target).transpose())
            .collect::<Result<Vec<_>>>()?;
        files.push((
            directory.join("BUCK"),
            render(
                WORKSPACE_TEMPLATE,
                context!(header => HEADER, targets => targets),
            )?,
        ));
    }

    let dependencies = graph.external_dependencies(&checksums)?;
    files.push((
        PathBuf::from(dependency_cell).join("BUCK"),
        render(EXTERNAL_TEMPLATE, context!(header => HEADER))?,
    ));
    files.push((
        PathBuf::from(dependency_cell).join("dependencies.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&dependencies)
                .wrap_err("could not serialize Buck dependency data")?
        ),
    ));
    files.push((
        PathBuf::from(dependency_cell).join("crates.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&graph.workspace_data(root)?)
                .wrap_err("could not serialize workspace crate data")?
        ),
    ));
    Ok(files)
}

impl<'a> Graph<'a> {
    fn new(metadata: &'a Metadata, dependency_cell: &'a str) -> Result<Self> {
        let resolve = metadata.resolve.as_ref().ok_or_else(|| {
            color_eyre::eyre::eyre!("Cargo metadata did not include a resolve graph")
        })?;
        Ok(Self {
            metadata,
            nodes: resolve.nodes.iter().map(|node| (&node.id, node)).collect(),
            packages: metadata
                .packages
                .iter()
                .map(|package| (&package.id, package))
                .collect(),
            workspace: metadata.workspace_members.iter().collect(),
            dependency_cell,
        })
    }

    fn workspace_packages(&self) -> Vec<&'a Package> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| self.workspace.contains(&package.id))
            .collect::<Vec<_>>();
        packages.sort_by_key(|package| package.name.as_str());
        packages
    }

    fn workspace_target(&self, package: &Package, target: &Target) -> Result<Option<RustTarget>> {
        let Some(rule) = target_rule(target, false) else {
            return Ok(None);
        };
        let package_root = package
            .manifest_path
            .as_std_path()
            .parent()
            .expect("manifest has a parent");
        let crate_root = target
            .src_path
            .as_std_path()
            .strip_prefix(package_root)
            .wrap_err("crate root is outside its package")?
            .to_string_lossy()
            .into_owned();
        let mut named_deps = self.dependencies(&package.id, DependencyKind::Normal, true);

        // Anything that compiles test code also needs `[dev-dependencies]`.
        // Leaving them out is invisible to `cargo test`, which has them, and
        // shows up only as a Buck-only "unresolved import" for a crate that is
        // plainly in `Cargo.toml`.
        let mut test_named_deps = named_deps.clone();
        test_named_deps.extend(self.dependencies(&package.id, DependencyKind::Development, true));
        test_named_deps.sort();
        test_named_deps.dedup();

        if target.kind.contains(&TargetKind::Test)
            && let Some(library) = package
                .targets
                .iter()
                .find(|candidate| is_library(candidate))
        {
            let link = (library.name.replace('-', "_"), format!(":{}", library.name));
            named_deps.push(link.clone());
            named_deps.sort();
            test_named_deps.push(link);
            test_named_deps.sort();
            test_named_deps.dedup();
        }

        // An integration test *is* a test target, so it links the test set.
        if target.kind.contains(&TargetKind::Test) {
            named_deps.clone_from(&test_named_deps);
        }

        // A binary in a package that also has a library links that library,
        // the way `cargo` does. Without this a `src/main.rs` calling into its
        // own `src/lib.rs` builds under cargo and not under Buck.
        if target.kind.contains(&TargetKind::Bin)
            && let Some(library) = package
                .targets
                .iter()
                .find(|candidate| is_library(candidate))
        {
            let link = (library.name.replace('-', "_"), format!(":{}", library.name));
            named_deps.push(link.clone());
            named_deps.sort();
            named_deps.dedup();
            // The binary's own unit tests compile the same `main.rs`.
            test_named_deps.push(link);
            test_named_deps.sort();
            test_named_deps.dedup();
        }

        // `CARGO_BIN_EXE_<name>`, which cargo defines for test targets so an
        // integration test can run the binary it is testing. Buck does not,
        // so the test fails to *compile* on a missing environment variable.
        // `$(location …)` is the Buck spelling of the same thing.
        //
        // Test targets only. A binary already links its package's library, so
        // giving the library a `$(location)` on that binary would be a cycle.
        let env = cargo_package_env(package);
        let mut test_env = env.clone();
        if !target.kind.contains(&TargetKind::Bin) {
            for binary in package
                .targets
                .iter()
                .filter(|candidate| candidate.kind.contains(&TargetKind::Bin))
            {
                test_env.push((
                    format!("CARGO_BIN_EXE_{}", binary.name),
                    format!("$(location :{})", binary.name),
                ));
            }
        }
        let mut features: Vec<String> = self
            .nodes
            .get(&package.id)
            .map(|node| node.features.iter().map(ToString::to_string).collect())
            .unwrap_or_default();
        features.sort();
        Ok(Some(RustTarget {
            rule,
            name: target.name.clone(),
            crate_name: target.name.replace('-', "_"),
            crate_root,
            edition: package.edition.to_string(),
            features,
            named_deps,
            test_named_deps,
            proc_macro: target.kind.contains(&TargetKind::ProcMacro),
            buildscript: None,
            env: if target.kind.contains(&TargetKind::Test) {
                test_env.clone()
            } else {
                env
            },
            test_env,
            unit_test: is_library(target) || target.kind.contains(&TargetKind::Bin),
        }))
    }

    fn external_packages(
        &self,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<Vec<ExternalPackage>> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| !self.workspace.contains(&package.id))
            .map(|package| self.external_package(package, checksums))
            .collect::<Result<Vec<_>>>()?;
        packages.sort_by(|left, right| {
            left.name
                .cmp(&right.name)
                .then_with(|| left.version.cmp(&right.version))
        });
        Ok(packages)
    }

    fn external_dependencies(
        &self,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<ExternalDependencies> {
        let packages = self.external_packages(checksums)?;
        let external = self
            .packages
            .keys()
            .filter(|package| !self.workspace.contains(*package))
            .copied()
            .collect::<BTreeSet<_>>();
        let tools = self.dependency_cell.ends_with("/glu");
        let root = self.metadata.workspace_root.as_std_path();
        let mut roots = self
            .workspace_packages()
            .into_iter()
            .filter_map(|package| {
                let mut dependencies = self
                    .nodes
                    .get(&package.id)?
                    .deps
                    .iter()
                    .filter(|dependency| external.contains(&dependency.pkg))
                    .map(|dependency| dependency.pkg.repr.clone())
                    .collect::<Vec<_>>();
                if dependencies.is_empty() {
                    return None;
                }
                dependencies.sort();
                dependencies.dedup();
                let category = if tools {
                    "tool"
                } else if package
                    .manifest_path
                    .as_std_path()
                    .strip_prefix(root)
                    .is_ok_and(|path| path.starts_with("crates/bin"))
                {
                    "product"
                } else {
                    "tcb"
                };
                Some(DependencyRoot {
                    id: stable_workspace_id(package),
                    name: package.name.to_string(),
                    category,
                    dependencies,
                })
            })
            .collect::<Vec<_>>();
        roots.sort_by(|left, right| left.name.cmp(&right.name));
        let edges = self.dependency_edges(|source, target| {
            external.contains(source) && external.contains(target)
        });
        Ok(ExternalDependencies {
            generated_by: concat!("glu ", env!("CARGO_PKG_VERSION")),
            packages,
            roots,
            edges,
        })
    }

    fn external_package(
        &self,
        package: &Package,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<ExternalPackage> {
        if package
            .source
            .as_ref()
            .is_none_or(|source| !source.is_crates_io())
        {
            bail!(
                "{} {} is not from crates.io and cannot be acquired by Buck",
                package.name,
                package.version
            );
        }
        let name = package.name.to_string();
        let version = package.version.to_string();
        let checksum = checksums
            .get(&(name.clone(), version.clone()))
            .cloned()
            .ok_or_else(|| {
                color_eyre::eyre::eyre!("missing registry checksum for {name} {version}")
            })?;
        let features = self
            .nodes
            .get(&package.id)
            .map(|node| {
                let mut features = node
                    .features
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                features.sort();
                features
            })
            .unwrap_or_default();
        let build_target = package
            .targets
            .iter()
            .find(|target| target.kind.contains(&TargetKind::CustomBuild));
        let buildscript = build_target.map(|target| Buildscript {
            crate_root: (relative_target_path(package, target) != "build.rs")
                .then(|| relative_target_path(package, target)),
            named_deps: self
                .dependencies(&package.id, DependencyKind::Build, false)
                .into_iter()
                .collect(),
        });
        let targets = package
            .targets
            .iter()
            .filter_map(|target| {
                target_rule(target, true)?;
                let crate_name = target.name.replace('-', "_");
                let default_crate_name = package.name.replace('-', "_");
                let crate_root = relative_target_path(package, target);
                Some(ExternalTarget {
                    crate_name: (crate_name != default_crate_name).then_some(crate_name),
                    crate_root: (crate_root != "src/lib.rs").then_some(crate_root),
                    named_deps: self
                        .dependencies(&package.id, DependencyKind::Normal, false)
                        .into_iter()
                        .collect(),
                    proc_macro: target.kind.contains(&TargetKind::ProcMacro),
                })
            })
            .collect();

        Ok(ExternalPackage {
            id: package.id.repr.clone(),
            name,
            version,
            checksum,
            edition: package.edition.to_string(),
            features,
            env: external_package_env(package),
            targets,
            buildscript,
        })
    }

    fn workspace_data(&self, root: &Path) -> Result<WorkspaceData> {
        let tools = self.dependency_cell.ends_with("/glu");
        let mut crates = self
            .workspace_packages()
            .into_iter()
            .map(|package| {
                let path = package_directory(root, package)?;
                let category = if tools {
                    "tool"
                } else if path.starts_with("crates/bin") {
                    "product"
                } else {
                    "tcb"
                };
                let mut targets = package
                    .targets
                    .iter()
                    .filter(|target| target_rule(target, false).is_some())
                    .map(|target| {
                        let mut kinds = target
                            .kind
                            .iter()
                            .map(ToString::to_string)
                            .collect::<Vec<_>>();
                        kinds.sort();
                        WorkspaceCrateTarget {
                            name: target.name.clone(),
                            kinds,
                        }
                    })
                    .collect::<Vec<_>>();
                targets.sort_by(|left, right| left.name.cmp(&right.name));
                Ok(WorkspaceCrate {
                    id: stable_workspace_id(package),
                    name: package.name.to_string(),
                    version: package.version.to_string(),
                    path: path.to_string_lossy().into_owned(),
                    category,
                    targets,
                })
            })
            .collect::<Result<Vec<_>>>()?;
        crates.sort_by(|left, right| left.name.cmp(&right.name));

        let edges = self.dependency_edges(|source, target| {
            self.workspace.contains(source) && self.workspace.contains(target)
        });

        Ok(WorkspaceData {
            generated_by: concat!("glu ", env!("CARGO_PKG_VERSION")),
            crates,
            edges,
        })
    }

    fn dependency_edges(
        &self,
        include: impl Fn(&PackageId, &PackageId) -> bool,
    ) -> Vec<DependencyEdge> {
        let mut edges = self
            .nodes
            .values()
            .flat_map(|node| {
                node.deps
                    .iter()
                    .filter(|dependency| include(&node.id, &dependency.pkg))
                    .map(|dependency| {
                        let mut kinds = dependency
                            .dep_kinds
                            .iter()
                            .map(|kind| {
                                let target = kind
                                    .target
                                    .as_ref()
                                    .map(|target| format!(" ({target})"))
                                    .unwrap_or_default();
                                format!("{}{target}", kind.kind)
                            })
                            .collect::<Vec<_>>();
                        kinds.sort();
                        kinds.dedup();
                        DependencyEdge {
                            source: self.stable_id(&node.id),
                            target: self.stable_id(&dependency.pkg),
                            kinds,
                        }
                    })
            })
            .collect::<Vec<_>>();
        edges.sort_by(|left, right| {
            left.source
                .cmp(&right.source)
                .then_with(|| left.target.cmp(&right.target))
                .then_with(|| left.kinds.cmp(&right.kinds))
        });
        edges
    }

    fn stable_id(&self, id: &PackageId) -> String {
        self.packages.get(id).map_or_else(
            || id.repr.clone(),
            |package| {
                if self.workspace.contains(id) {
                    stable_workspace_id(package)
                } else {
                    id.repr.clone()
                }
            },
        )
    }

    fn dependencies(
        &self,
        package: &PackageId,
        kind: DependencyKind,
        qualified: bool,
    ) -> Vec<(String, String)> {
        let mut dependencies = self
            .nodes
            .get(package)
            .into_iter()
            .flat_map(|node| &node.deps)
            .filter(|dependency| {
                dependency
                    .dep_kinds
                    .iter()
                    .any(|dependency_kind| dependency_kind.kind == kind)
            })
            .filter_map(|dependency| {
                self.packages.get(&dependency.pkg).map(|package| {
                    let target = package
                        .targets
                        .iter()
                        .find(|target| is_library(target))
                        .map_or_else(
                            || label(package),
                            |target| {
                                if self.workspace.contains(&package.id) {
                                    target.name.clone()
                                } else {
                                    label(package)
                                }
                            },
                        );
                    let value = if self.workspace.contains(&package.id) {
                        let directory =
                            package_directory(self.metadata.workspace_root.as_std_path(), package)
                                .expect("workspace package is inside workspace");
                        format!("nucleus//{}:{target}", directory.display())
                    } else if qualified {
                        format!("nucleus//{}:{target}", self.dependency_cell)
                    } else {
                        format!(":{target}")
                    };
                    (dependency.name.clone(), value)
                })
            })
            .collect::<Vec<_>>();
        dependencies.sort();
        dependencies
    }
}

fn render(template: &str, context: minijinja::Value) -> Result<String> {
    let mut environment = Environment::new();
    environment
        .add_template("BUCK", template)
        .wrap_err("invalid Buck template")?;
    let mut output = environment
        .get_template("BUCK")
        .wrap_err("missing Buck template")?
        .render(context)
        .wrap_err("could not render Buck template")?;
    output.truncate(output.trim_end().len());
    output.push('\n');
    Ok(output)
}

fn target_rule(target: &Target, external: bool) -> Option<&'static str> {
    if target.kind.contains(&TargetKind::Bin) && !external {
        Some("rust_binary")
    } else if target.kind.contains(&TargetKind::Test) && !external {
        Some("rust_test")
    } else if is_library(target) {
        Some(if external {
            "cargo.rust_library"
        } else {
            "rust_library"
        })
    } else {
        None
    }
}

fn is_library(target: &Target) -> bool {
    target.kind.iter().any(|kind| {
        matches!(
            kind,
            TargetKind::Lib
                | TargetKind::RLib
                | TargetKind::CDyLib
                | TargetKind::StaticLib
                | TargetKind::DyLib
                | TargetKind::ProcMacro
        )
    })
}

fn label(package: &Package) -> String {
    format!("{}-{}", package.name, package.version)
}

fn stable_workspace_id(package: &Package) -> String {
    format!("workspace#{}@{}", package.name, package.version)
}

fn relative_target_path(package: &Package, target: &Target) -> String {
    target
        .src_path
        .as_std_path()
        .strip_prefix(
            package
                .manifest_path
                .as_std_path()
                .parent()
                .expect("manifest has a parent"),
        )
        .expect("target is inside package")
        .to_string_lossy()
        .into_owned()
}

fn package_directory(root: &Path, package: &Package) -> Result<PathBuf> {
    package
        .manifest_path
        .as_std_path()
        .parent()
        .and_then(|path| path.strip_prefix(root).ok())
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            color_eyre::eyre::eyre!("{} is outside the repository", package.manifest_path)
        })
}

fn cargo_package_env(package: &Package) -> Vec<(String, String)> {
    let version = &package.version;
    [
        ("CARGO_PKG_AUTHORS", package.authors.join(":")),
        (
            "CARGO_PKG_DESCRIPTION",
            package.description.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_HOMEPAGE",
            package.homepage.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE",
            package.license.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE_FILE",
            package
                .license_file
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("CARGO_PKG_NAME", package.name.to_string()),
        ("CARGO_PKG_README", String::new()),
        (
            "CARGO_PKG_REPOSITORY",
            package.repository.clone().unwrap_or_default(),
        ),
        ("CARGO_PKG_RUST_VERSION", String::new()),
        ("CARGO_PKG_VERSION", version.to_string()),
        ("CARGO_PKG_VERSION_MAJOR", version.major.to_string()),
        ("CARGO_PKG_VERSION_MINOR", version.minor.to_string()),
        ("CARGO_PKG_VERSION_PATCH", version.patch.to_string()),
        ("CARGO_PKG_VERSION_PRE", version.pre.to_string()),
    ]
    .into_iter()
    .map(|(name, value)| (name.to_owned(), value))
    .collect()
}

fn external_package_env(package: &Package) -> BTreeMap<String, String> {
    cargo_package_env(package)
        .into_iter()
        .filter(|(name, value)| {
            !value.is_empty()
                && !matches!(
                    name.as_str(),
                    "CARGO_PKG_NAME"
                        | "CARGO_PKG_VERSION"
                        | "CARGO_PKG_VERSION_MAJOR"
                        | "CARGO_PKG_VERSION_MINOR"
                        | "CARGO_PKG_VERSION_PATCH"
                )
        })
        .collect()
}
