use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use cargo_lock::Lockfile;
use cargo_metadata::{DependencyKind, Metadata, Node, Package, PackageId, Target, TargetKind};
use color_eyre::eyre::{Result, WrapErr, bail};
use minijinja::{Environment, context};
use serde::Serialize;

use crate::cargo;

const HEADER: &str = "# @generated by `glu buck sync`; do not edit.\n\
                      # Cargo.toml and Cargo.lock are authoritative.\n";

const WORKSPACE_TEMPLATE: &str = r#"{{ header }}
{%- if buildscript %}
load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
{% endif %}
_PACKAGE_FILES = glob(
    ["**"],
    exclude = ["BUCK", "target/**"],
)

# Every file in the package, because `include_bytes!` and `include_str!` can
# name any of them and a glob by extension silently misses the ones it did not
# think of. Coarser invalidation than listing extensions, and correct.
_RUST_SOURCES = glob(
    ["**"],
    exclude = ["BUCK", "target/**"],
)

filegroup(
    name = "package_files",
    srcs = _PACKAGE_FILES,
    visibility = ["PUBLIC"],
)

{% if manifest_files -%}
# Some compile-time macros read shared workspace files relative to
# `CARGO_MANIFEST_DIR`. Recreate that part of the workspace as one declared
# Buck input tree so Cargo and Buck resolve the same relative paths.
_MANIFEST_FILES = {
    {{ manifest_files.package_source|tojson }}.format(source): source
    for source in _PACKAGE_FILES
}
_MANIFEST_FILES.update({
{%- for source, destination in manifest_files.mapped_srcs %}
    {{ destination|tojson }}: {{ source|tojson }},
{%- endfor %}
})

filegroup(
    name = "manifest_files",
    srcs = _MANIFEST_FILES,
    visibility = [],
)

{% endif -%}
{% if buildscript -%}
# `build.rs`, compiled and run the way cargo runs it. `buildscript_run` turns
# the script's `cargo::` directives into an `OUT_DIR` and a rustc argument file,
# which every target in this package then consumes; without it the script never
# runs under Buck and its effects — generated sources, `--cfg` flags, native
# libraries it compiled — are silently missing from an otherwise successful
# build.
rust_binary(
    name = "{{ buildscript.name }}-build-script-build",
    crate = "build_script_build",
    crate_root = {{ buildscript.crate_root|tojson }},
    edition = {{ buildscript.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if buildscript.features %}
    features = [
{%- for feature in buildscript.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if buildscript.named_deps %}
    named_deps = {
{%- for name, dependency in buildscript.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
    env = {
{%- for name, value in buildscript.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
    visibility = [],
)

buildscript_run(
    name = "{{ buildscript.name }}-build-script-run",
    package_name = {{ buildscript.package_name|tojson }},
    version = {{ buildscript.version|tojson }},
    buildscript_rule = ":{{ buildscript.name }}-build-script-build",
    # Cargo runs a build script with the package directory as its working
    # directory, so relative paths in `build.rs` have to resolve against the
    # whole package, not against the source files rustc happens to read.
    manifest_dir = ":package_files",
    rustc_link_lib = True,
    rustc_link_search = True,
{%- if buildscript.features %}
    features = [
{%- for feature in buildscript.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
    env = {
{%- for name, value in buildscript.run_env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
)

{% endif -%}
{% for target in targets -%}
{{ target.rule }}(
    name = {{ target.name|tojson }},
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.features %}
    features = [
{%- for feature in target.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if target.unit_test %}
    tests = [":{{ target.name }}-unit-test"],
{%- endif %}
{%- if target.proc_macro %}
    proc_macro = True,
{%- endif %}
{%- if target.named_deps %}
    named_deps = {
{%- for name, dependency in target.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.buildscript %}
    rustc_flags = [
        "@$(location :{{ target.buildscript }}[rustc_flags])",
    ],
{%- endif %}
    visibility = ["PUBLIC"],
)

{% if target.unit_test -%}
rust_test(
    name = "{{ target.name }}-unit-test",
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.test_mapped_srcs %}
    mapped_srcs = {
{%- for source, destination in target.test_mapped_srcs %}
        {{ source|tojson }}: {{ destination|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.test_features %}
    features = [
{%- for feature in target.test_features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if target.test_named_deps %}
    named_deps = {
{%- for name, dependency in target.test_named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.buildscript %}
    rustc_flags = [
        "@$(location :{{ target.buildscript }}[rustc_flags])",
    ],
{%- endif %}
    visibility = ["PUBLIC"],
)

{% endif -%}
{% endfor -%}
"#;

const EXTERNAL_TEMPLATE: &str = r#"{{ header }}
load(":dependencies.json", dependencies = "value")
load("//buck/cargo:dependencies.bzl", "declare_cargo_dependencies")

export_file(
    name = "crates-json",
    src = "crates.json",
    visibility = ["PUBLIC"],
)

export_file(
    name = "dependencies-json",
    src = "dependencies.json",
    visibility = ["PUBLIC"],
)

declare_cargo_dependencies(dependencies)
"#;

#[derive(Serialize)]
struct RustTarget {
    rule: &'static str,
    name: String,
    crate_name: String,
    crate_root: String,
    edition: String,
    features: Vec<String>,
    named_deps: Vec<(String, String)>,
    /// What the test rule links: the same plus `[dev-dependencies]`.
    ///
    /// Kept separate so a dev-dependency cannot leak into the library, which
    /// is the whole reason Cargo distinguishes them.
    test_named_deps: Vec<(String, String)>,
    test_features: Vec<String>,
    proc_macro: bool,
    buildscript: Option<String>,
    env: Vec<(String, String)>,
    /// What the test rule gets: the same plus `CARGO_BIN_EXE_*`.
    ///
    /// Separate from `env` because pointing the *library* at its package's
    /// binary makes the library depend on the binary that depends on it.
    test_env: Vec<(String, String)>,
    /// Additional sources and their local paths needed only by test code.
    test_mapped_srcs: Vec<(String, String)>,
    unit_test: bool,
}

#[derive(Serialize)]
struct ManifestFiles {
    /// Destination of a package file in the synthetic workspace tree.
    package_source: String,
    /// Additional Buck sources and their workspace-relative destinations.
    mapped_srcs: Vec<(String, String)>,
}

/// A path a `links` package publishes to its dependents' build scripts.
///
/// Cargo hands a build script `DEP_<LINKS>_<KEY>` for every `cargo::metadata=`
/// line printed by the build script of a direct dependency declaring `links`.
/// Buck's prelude keeps only the directives it can turn into rustc arguments —
/// `--cfg`, `-l`, `-L`, `--env-set` — and discards the rest, so nothing
/// propagates. There is no way to recover a value computed at build time, so
/// the ones this workspace consumes are restated here as Buck labels.
///
/// A missing entry is not silent: the dependent build script fails on the
/// absent variable, the way cas-shell's does, rather than compiling against
/// the wrong header.
struct LinksMetadata {
    /// The `links` value of the package that publishes it.
    links: &'static str,
    /// The `DEP_<LINKS>_<KEY>` suffix, spelled as cargo spells it.
    key: &'static str,
    /// Where it points, relative to the publishing crate's own source tree.
    path: &'static str,
}

const LINKS_METADATA: &[LinksMetadata] = &[LinksMetadata {
    links: "sqlite3",
    key: "INCLUDE",
    // `libsqlite3-sys` prints `cargo:include=$CARGO_MANIFEST_DIR/sqlite3` from
    // its bundled path: the amalgamation directory inside its own crate, which
    // is where the `sqlite3.h` matching the linked library lives.
    path: "sqlite3",
}];

/// A workspace package's `build.rs`, as the pair of rules Buck wants.
///
/// One per package, not one per target: cargo runs a build script once and
/// every target in the package sees the same `OUT_DIR` and the same flags.
#[derive(Serialize)]
struct WorkspaceBuildscript {
    /// The label prefix shared by `-build-script-build` and
    /// `-build-script-run`, which is also what targets reference.
    name: String,
    package_name: String,
    version: String,
    crate_root: String,
    edition: String,
    features: Vec<String>,
    named_deps: Vec<(String, String)>,
    /// What compiling `build.rs` sees, for the `env!` it reads at compile time.
    env: Vec<(String, String)>,
    /// What running it sees: the same plus `DEP_<LINKS>_<KEY>`.
    ///
    /// Kept off the compile rule because those are `$(location)` on a
    /// dependency's source archive, and the compile rule is re-configured once
    /// per Reindeer platform. Putting them there would fetch and configure
    /// that archive once per platform for a variable no compilation reads.
    run_env: Vec<(String, String)>,
}

#[derive(Serialize)]
struct ExternalPackage {
    id: String,
    name: String,
    version: String,
    checksum: String,
    edition: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    features: Vec<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    env: BTreeMap<String, String>,
    targets: Vec<ExternalTarget>,
    #[serde(skip_serializing_if = "Option::is_none")]
    buildscript: Option<Buildscript>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ExternalDependencies {
    generated_by: &'static str,
    packages: Vec<ExternalPackage>,
    roots: Vec<DependencyRoot>,
    edges: Vec<DependencyEdge>,
}

#[derive(Serialize)]
struct DependencyRoot {
    id: String,
    name: String,
    category: &'static str,
    dependencies: Vec<String>,
}

#[derive(Serialize)]
struct ExternalTarget {
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_root: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    named_deps: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    proc_macro: bool,
}

#[derive(Serialize)]
struct Buildscript {
    #[serde(skip_serializing_if = "Option::is_none")]
    crate_root: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    named_deps: BTreeMap<String, String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WorkspaceData {
    generated_by: &'static str,
    crates: Vec<WorkspaceCrate>,
    edges: Vec<DependencyEdge>,
}

#[derive(Serialize)]
struct WorkspaceCrate {
    id: String,
    name: String,
    version: String,
    path: String,
    category: &'static str,
    targets: Vec<WorkspaceCrateTarget>,
}

#[derive(Serialize)]
struct WorkspaceCrateTarget {
    name: String,
    kinds: Vec<String>,
}

#[derive(Serialize)]
struct DependencyEdge {
    source: String,
    target: String,
    kinds: Vec<String>,
}

struct Graph<'a> {
    metadata: &'a Metadata,
    nodes: BTreeMap<&'a PackageId, &'a Node>,
    packages: BTreeMap<&'a PackageId, &'a Package>,
    workspace: BTreeSet<&'a PackageId>,
    dependency_cell: &'a str,
}

pub(crate) fn sync(root: &Path) -> Result<usize> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut changed = 0;
    for (path, contents) in files {
        let path = root.join(path);
        if fs::read_to_string(&path).ok().as_deref() == Some(&contents) {
            continue;
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .wrap_err_with(|| format!("could not create {}", parent.display()))?;
        }
        fs::write(&path, contents)
            .wrap_err_with(|| format!("could not write {}", path.display()))?;
        changed += 1;
    }
    for path in discovered_generated_files(root)?.difference(&expected) {
        fs::remove_file(root.join(path))
            .wrap_err_with(|| format!("could not remove stale {}", path.display()))?;
        changed += 1;
    }
    Ok(changed)
}

pub(crate) fn check(root: &Path) -> Result<()> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut stale = files
        .into_iter()
        .filter_map(|(path, expected)| {
            let actual = fs::read_to_string(root.join(&path)).ok();
            (actual.as_deref() != Some(&expected)).then_some(path)
        })
        .collect::<Vec<_>>();
    stale.extend(
        discovered_generated_files(root)?
            .difference(&expected)
            .cloned(),
    );
    stale.sort();
    if !stale.is_empty() {
        bail!(
            "generated Buck files are stale:\n{}\nrun `glu buck sync`",
            stale
                .iter()
                .map(|path| format!("  - {}", path.display()))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    Ok(())
}

fn discovered_generated_files(root: &Path) -> Result<BTreeSet<PathBuf>> {
    let mut directories = ["crates", "tools/glu", "buck/cargo"]
        .map(|path| root.join(path))
        .to_vec();
    let mut files = BTreeSet::new();
    while let Some(directory) = directories.pop() {
        for entry in fs::read_dir(&directory)
            .wrap_err_with(|| format!("could not read {}", directory.display()))?
        {
            let entry = entry.wrap_err("could not read Buck source directory")?;
            let path = entry.path();
            if entry
                .file_type()
                .wrap_err_with(|| format!("could not inspect {}", path.display()))?
                .is_dir()
            {
                if entry.file_name() != "target" {
                    directories.push(path);
                }
            } else if entry.file_name() == "BUCK"
                && fs::read_to_string(&path).is_ok_and(|contents| contents.starts_with(HEADER))
            {
                files.insert(
                    path.strip_prefix(root)
                        .expect("discovered path is inside the repository")
                        .to_owned(),
                );
            }
        }
    }
    Ok(files)
}

fn generated_files(root: &Path) -> Result<Vec<(PathBuf, String)>> {
    let mut files = Vec::new();
    files.extend(generate_workspace(
        root,
        &root.join("Cargo.toml"),
        "buck/cargo/production",
    )?);
    files.extend(generate_workspace(
        root,
        &root.join("tools/glu/Cargo.toml"),
        "buck/cargo/glu",
    )?);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(files)
}

fn generate_workspace(
    root: &Path,
    manifest: &Path,
    dependency_cell: &str,
) -> Result<Vec<(PathBuf, String)>> {
    let metadata = cargo::load_manifest(root, manifest)?;
    let graph = Graph::new(&metadata, dependency_cell)?;
    let lockfile = Lockfile::load(
        manifest
            .parent()
            .expect("manifest has a parent")
            .join("Cargo.lock"),
    )
    .wrap_err_with(|| format!("could not read lockfile for {}", manifest.display()))?;
    let checksums = lockfile
        .packages
        .iter()
        .filter_map(|package| {
            package.checksum.as_ref().map(|checksum| {
                (
                    (package.name.to_string(), package.version.to_string()),
                    checksum.to_string(),
                )
            })
        })
        .collect::<BTreeMap<_, _>>();

    let mut files = Vec::new();
    for package in graph.workspace_packages() {
        if !buck_builds(package) {
            continue;
        }
        let directory = package_directory(root, package)?;
        let manifest_mapped_srcs = buck_manifest_mapped_srcs(package)?;
        let manifest_files = if manifest_mapped_srcs.is_empty() {
            None
        } else {
            Some(ManifestFiles {
                package_source: format!("{}/{{}}", directory.to_string_lossy()),
                mapped_srcs: manifest_mapped_srcs,
            })
        };
        let manifest_dir = manifest_files.as_ref().map_or_else(
            || "$(location :package_files)".to_owned(),
            |_| {
                format!(
                    "$(location :manifest_files)/{}",
                    directory.to_string_lossy()
                )
            },
        );
        let buildscript = graph.workspace_buildscript(package, &manifest_dir);
        let targets = package
            .targets
            .iter()
            .filter_map(|target| {
                graph
                    .workspace_target(package, target, buildscript.as_ref(), &manifest_dir)
                    .transpose()
            })
            .collect::<Result<Vec<_>>>()?;
        files.push((
            directory.join("BUCK"),
            render(
                WORKSPACE_TEMPLATE,
                context!(
                    header => HEADER,
                    targets => targets,
                    buildscript => buildscript,
                    manifest_files => manifest_files,
                ),
            )?,
        ));
    }

    let dependencies = graph.external_dependencies(&checksums)?;
    files.push((
        PathBuf::from(dependency_cell).join("BUCK"),
        render(EXTERNAL_TEMPLATE, context!(header => HEADER))?,
    ));
    files.push((
        PathBuf::from(dependency_cell).join("dependencies.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&dependencies)
                .wrap_err("could not serialize Buck dependency data")?
        ),
    ));
    files.push((
        PathBuf::from(dependency_cell).join("crates.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&graph.workspace_data(root)?)
                .wrap_err("could not serialize workspace crate data")?
        ),
    ));
    Ok(files)
}

impl<'a> Graph<'a> {
    fn new(metadata: &'a Metadata, dependency_cell: &'a str) -> Result<Self> {
        let resolve = metadata.resolve.as_ref().ok_or_else(|| {
            color_eyre::eyre::eyre!("Cargo metadata did not include a resolve graph")
        })?;
        Ok(Self {
            metadata,
            nodes: resolve.nodes.iter().map(|node| (&node.id, node)).collect(),
            packages: metadata
                .packages
                .iter()
                .map(|package| (&package.id, package))
                .collect(),
            workspace: metadata.workspace_members.iter().collect(),
            dependency_cell,
        })
    }

    fn workspace_packages(&self) -> Vec<&'a Package> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| self.workspace.contains(&package.id))
            .collect::<Vec<_>>();
        packages.sort_by_key(|package| package.name.as_str());
        packages
    }

    /// The `build.rs` rules for a workspace package, if it has one.
    fn workspace_buildscript(
        &self,
        package: &Package,
        manifest_dir: &str,
    ) -> Option<WorkspaceBuildscript> {
        let target = package
            .targets
            .iter()
            .find(|target| target.kind.contains(&TargetKind::CustomBuild))?;
        let mut env = cargo_package_env(package);
        env.extend(
            [
                // Cargo's contract with a build script: the package directory,
                // and a description of the profile it is being built for.
                ("CARGO_MANIFEST_DIR", manifest_dir),
                ("DEBUG", "true"),
                ("OPT_LEVEL", "0"),
                ("PROFILE", "debug"),
            ]
            .into_iter()
            .map(|(name, value)| (name.to_owned(), value.to_owned())),
        );
        let mut run_env = env.clone();
        run_env.extend(self.links_metadata(&package.id));
        Some(WorkspaceBuildscript {
            name: package.name.to_string(),
            package_name: package.name.to_string(),
            version: package.version.to_string(),
            crate_root: relative_target_path(package, target),
            edition: package.edition.to_string(),
            features: self.features(&package.id),
            named_deps: self.dependencies(&package.id, DependencyKind::Build, true),
            env,
            run_env,
        })
    }

    fn workspace_target(
        &self,
        package: &Package,
        target: &Target,
        buildscript: Option<&WorkspaceBuildscript>,
        manifest_dir: &str,
    ) -> Result<Option<RustTarget>> {
        let Some(rule) = target_rule(target, false) else {
            return Ok(None);
        };
        let package_root = package
            .manifest_path
            .as_std_path()
            .parent()
            .expect("manifest has a parent");
        let crate_root = target
            .src_path
            .as_std_path()
            .strip_prefix(package_root)
            .wrap_err("crate root is outside its package")?
            .to_string_lossy()
            .into_owned();
        let mut named_deps = self.dependencies(&package.id, DependencyKind::Normal, true);

        // Anything that compiles test code also needs `[dev-dependencies]`.
        // Leaving them out is invisible to `cargo test`, which has them, and
        // shows up only as a Buck-only "unresolved import" for a crate that is
        // plainly in `Cargo.toml`.
        let mut test_named_deps = named_deps.clone();
        test_named_deps.extend(self.dependencies(&package.id, DependencyKind::Development, true));
        test_named_deps.sort();
        test_named_deps.dedup();

        if target.kind.contains(&TargetKind::Test)
            && let Some(library) = package
                .targets
                .iter()
                .find(|candidate| is_library(candidate))
        {
            let link = (library.name.replace('-', "_"), format!(":{}", library.name));
            named_deps.push(link.clone());
            named_deps.sort();
            test_named_deps.push(link);
            test_named_deps.sort();
            test_named_deps.dedup();
        }

        // An integration test *is* a test target, so it links the test set.
        if target.kind.contains(&TargetKind::Test) {
            named_deps.clone_from(&test_named_deps);
        }

        // A binary in a package that also has a library links that library,
        // the way `cargo` does. Without this a `src/main.rs` calling into its
        // own `src/lib.rs` builds under cargo and not under Buck.
        if target.kind.contains(&TargetKind::Bin)
            && let Some(library) = package
                .targets
                .iter()
                .find(|candidate| is_library(candidate))
        {
            let link = (library.name.replace('-', "_"), format!(":{}", library.name));
            named_deps.push(link.clone());
            named_deps.sort();
            named_deps.dedup();
            // The binary's own unit tests compile the same `main.rs`.
            test_named_deps.push(link);
            test_named_deps.sort();
            test_named_deps.dedup();
        }

        // `CARGO_BIN_EXE_<name>`, which cargo defines for test targets so an
        // integration test can run the binary it is testing. Buck does not,
        // so the test fails to *compile* on a missing environment variable.
        // `$(location …)` is the Buck spelling of the same thing.
        //
        // Test targets only. A binary already links its package's library, so
        // giving the library a `$(location)` on that binary would be a cycle.
        let mut env = cargo_package_env(package);
        // Cargo exposes the package directory to build-time code.
        env.push(("CARGO_MANIFEST_DIR".to_owned(), manifest_dir.to_owned()));
        // What `include!(concat!(env!("OUT_DIR"), …))` reads. The rest of what
        // the script emitted arrives as `rustc_flags`, which the template adds
        // alongside this.
        if let Some(buildscript) = buildscript {
            env.push((
                "OUT_DIR".to_owned(),
                format!(
                    "$(location :{}-build-script-run[out_dir])",
                    buildscript.name
                ),
            ));
        }
        let mut test_env = env.clone();
        if !target.kind.contains(&TargetKind::Bin) {
            for binary in package
                .targets
                .iter()
                .filter(|candidate| candidate.kind.contains(&TargetKind::Bin))
            {
                test_env.push((
                    format!("CARGO_BIN_EXE_{}", binary.name),
                    format!("$(location :{})", binary.name),
                ));
            }
        }
        let (features, test_features) = buck_features(package, self.features(&package.id))?;
        Ok(Some(RustTarget {
            rule,
            name: target.name.clone(),
            crate_name: target.name.replace('-', "_"),
            crate_root,
            edition: package.edition.to_string(),
            features,
            named_deps,
            test_named_deps,
            test_features,
            proc_macro: target.kind.contains(&TargetKind::ProcMacro),
            buildscript: buildscript
                .map(|buildscript| format!("{}-build-script-run", buildscript.name)),
            env: if target.kind.contains(&TargetKind::Test) {
                test_env.clone()
            } else {
                env
            },
            test_env,
            test_mapped_srcs: buck_test_mapped_srcs(package)?,
            unit_test: is_library(target) || target.kind.contains(&TargetKind::Bin),
        }))
    }

    fn external_packages(
        &self,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<Vec<ExternalPackage>> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| !self.workspace.contains(&package.id))
            .map(|package| self.external_package(package, checksums))
            .collect::<Result<Vec<_>>>()?;
        packages.sort_by(|left, right| {
            left.name
                .cmp(&right.name)
                .then_with(|| left.version.cmp(&right.version))
        });
        Ok(packages)
    }

    fn external_dependencies(
        &self,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<ExternalDependencies> {
        let packages = self.external_packages(checksums)?;
        let external = self
            .packages
            .keys()
            .filter(|package| !self.workspace.contains(*package))
            .copied()
            .collect::<BTreeSet<_>>();
        let tools = self.dependency_cell.ends_with("/glu");
        let root = self.metadata.workspace_root.as_std_path();
        let mut roots = self
            .workspace_packages()
            .into_iter()
            .filter_map(|package| {
                let mut dependencies = self
                    .nodes
                    .get(&package.id)?
                    .deps
                    .iter()
                    .filter(|dependency| external.contains(&dependency.pkg))
                    .map(|dependency| dependency.pkg.repr.clone())
                    .collect::<Vec<_>>();
                if dependencies.is_empty() {
                    return None;
                }
                dependencies.sort();
                dependencies.dedup();
                let category = if tools {
                    "tool"
                } else if package
                    .manifest_path
                    .as_std_path()
                    .strip_prefix(root)
                    .is_ok_and(|path| path.starts_with("crates/bin"))
                {
                    "product"
                } else {
                    "tcb"
                };
                Some(DependencyRoot {
                    id: stable_workspace_id(package),
                    name: package.name.to_string(),
                    category,
                    dependencies,
                })
            })
            .collect::<Vec<_>>();
        roots.sort_by(|left, right| left.name.cmp(&right.name));
        let edges = self.dependency_edges(|source, target| {
            external.contains(source) && external.contains(target)
        });
        Ok(ExternalDependencies {
            generated_by: concat!("glu ", env!("CARGO_PKG_VERSION")),
            packages,
            roots,
            edges,
        })
    }

    fn external_package(
        &self,
        package: &Package,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<ExternalPackage> {
        if package
            .source
            .as_ref()
            .is_none_or(|source| !source.is_crates_io())
        {
            bail!(
                "{} {} is not from crates.io and cannot be acquired by Buck",
                package.name,
                package.version
            );
        }
        let name = package.name.to_string();
        let version = package.version.to_string();
        let checksum = checksums
            .get(&(name.clone(), version.clone()))
            .cloned()
            .ok_or_else(|| {
                color_eyre::eyre::eyre!("missing registry checksum for {name} {version}")
            })?;
        let features = self.features(&package.id);
        let build_target = package
            .targets
            .iter()
            .find(|target| target.kind.contains(&TargetKind::CustomBuild));
        let buildscript = build_target.map(|target| Buildscript {
            crate_root: (relative_target_path(package, target) != "build.rs")
                .then(|| relative_target_path(package, target)),
            named_deps: self
                .dependencies(&package.id, DependencyKind::Build, false)
                .into_iter()
                .collect(),
        });
        let targets = package
            .targets
            .iter()
            .filter_map(|target| {
                target_rule(target, true)?;
                let crate_name = target.name.replace('-', "_");
                let default_crate_name = package.name.replace('-', "_");
                let crate_root = relative_target_path(package, target);
                Some(ExternalTarget {
                    crate_name: (crate_name != default_crate_name).then_some(crate_name),
                    crate_root: (crate_root != "src/lib.rs").then_some(crate_root),
                    named_deps: self
                        .dependencies(&package.id, DependencyKind::Normal, false)
                        .into_iter()
                        .collect(),
                    proc_macro: target.kind.contains(&TargetKind::ProcMacro),
                })
            })
            .collect();

        Ok(ExternalPackage {
            id: package.id.repr.clone(),
            name,
            version,
            checksum,
            edition: package.edition.to_string(),
            features,
            env: external_package_env(package),
            targets,
            buildscript,
        })
    }

    fn workspace_data(&self, root: &Path) -> Result<WorkspaceData> {
        let tools = self.dependency_cell.ends_with("/glu");
        let mut crates = self
            .workspace_packages()
            .into_iter()
            .map(|package| {
                let path = package_directory(root, package)?;
                let category = if tools {
                    "tool"
                } else if path.starts_with("crates/bin") {
                    "product"
                } else {
                    "tcb"
                };
                let mut targets = package
                    .targets
                    .iter()
                    .filter(|target| target_rule(target, false).is_some())
                    .map(|target| {
                        let mut kinds = target
                            .kind
                            .iter()
                            .map(ToString::to_string)
                            .collect::<Vec<_>>();
                        kinds.sort();
                        WorkspaceCrateTarget {
                            name: target.name.clone(),
                            kinds,
                        }
                    })
                    .collect::<Vec<_>>();
                targets.sort_by(|left, right| left.name.cmp(&right.name));
                Ok(WorkspaceCrate {
                    id: stable_workspace_id(package),
                    name: package.name.to_string(),
                    version: package.version.to_string(),
                    path: path.to_string_lossy().into_owned(),
                    category,
                    targets,
                })
            })
            .collect::<Result<Vec<_>>>()?;
        crates.sort_by(|left, right| left.name.cmp(&right.name));

        let edges = self.dependency_edges(|source, target| {
            self.workspace.contains(source) && self.workspace.contains(target)
        });

        Ok(WorkspaceData {
            generated_by: concat!("glu ", env!("CARGO_PKG_VERSION")),
            crates,
            edges,
        })
    }

    fn dependency_edges(
        &self,
        include: impl Fn(&PackageId, &PackageId) -> bool,
    ) -> Vec<DependencyEdge> {
        let mut edges = self
            .nodes
            .values()
            .flat_map(|node| {
                node.deps
                    .iter()
                    .filter(|dependency| include(&node.id, &dependency.pkg))
                    .map(|dependency| {
                        let mut kinds = dependency
                            .dep_kinds
                            .iter()
                            .map(|kind| {
                                let target = kind
                                    .target
                                    .as_ref()
                                    .map(|target| format!(" ({target})"))
                                    .unwrap_or_default();
                                format!("{}{target}", kind.kind)
                            })
                            .collect::<Vec<_>>();
                        kinds.sort();
                        kinds.dedup();
                        DependencyEdge {
                            source: self.stable_id(&node.id),
                            target: self.stable_id(&dependency.pkg),
                            kinds,
                        }
                    })
            })
            .collect::<Vec<_>>();
        edges.sort_by(|left, right| {
            left.source
                .cmp(&right.source)
                .then_with(|| left.target.cmp(&right.target))
                .then_with(|| left.kinds.cmp(&right.kinds))
        });
        edges
    }

    fn stable_id(&self, id: &PackageId) -> String {
        self.packages.get(id).map_or_else(
            || id.repr.clone(),
            |package| {
                if self.workspace.contains(id) {
                    stable_workspace_id(package)
                } else {
                    id.repr.clone()
                }
            },
        )
    }

    /// `DEP_<LINKS>_<KEY>` for each direct dependency that declares `links`.
    ///
    /// Only crates.io dependencies: a `links` package inside the workspace
    /// would need a different label, and there are none.
    fn links_metadata(&self, package: &PackageId) -> Vec<(String, String)> {
        let mut metadata = self
            .nodes
            .get(package)
            .into_iter()
            .flat_map(|node| &node.deps)
            .filter(|dependency| {
                dependency
                    .dep_kinds
                    .iter()
                    .any(|kind| kind.kind == DependencyKind::Normal)
            })
            .filter(|dependency| !self.workspace.contains(&dependency.pkg))
            .filter_map(|dependency| self.packages.get(&dependency.pkg))
            .filter_map(|package| Some((*package, package.links.as_deref()?)))
            .flat_map(|(package, links)| {
                LINKS_METADATA
                    .iter()
                    .filter(move |entry| entry.links == links)
                    .map(move |entry| {
                        (
                            // Cargo's `envify`: uppercase, dashes to
                            // underscores.
                            format!(
                                "DEP_{}_{}",
                                links.to_uppercase().replace('-', "_"),
                                entry.key
                            ),
                            format!(
                                "$(location nucleus//{}:{}.crate)/{}",
                                self.dependency_cell,
                                label(package),
                                entry.path
                            ),
                        )
                    })
            })
            .collect::<Vec<_>>();
        metadata.sort();
        metadata
    }

    /// The features cargo resolved for a package, which is what its build
    /// script reads as `CARGO_FEATURE_*` and what its targets compile with.
    fn features(&self, package: &PackageId) -> Vec<String> {
        let mut features = self
            .nodes
            .get(package)
            .map(|node| {
                node.features
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();
        features.sort();
        features
    }

    fn dependencies(
        &self,
        package: &PackageId,
        kind: DependencyKind,
        qualified: bool,
    ) -> Vec<(String, String)> {
        let mut dependencies = self
            .nodes
            .get(package)
            .into_iter()
            .flat_map(|node| &node.deps)
            .filter(|dependency| {
                dependency
                    .dep_kinds
                    .iter()
                    .any(|dependency_kind| dependency_kind.kind == kind)
            })
            .filter_map(|dependency| {
                self.packages.get(&dependency.pkg).map(|package| {
                    let target = package
                        .targets
                        .iter()
                        .find(|target| is_library(target))
                        .map_or_else(
                            || label(package),
                            |target| {
                                if self.workspace.contains(&package.id) {
                                    target.name.clone()
                                } else {
                                    label(package)
                                }
                            },
                        );
                    let value = if self.workspace.contains(&package.id) {
                        let directory =
                            package_directory(self.metadata.workspace_root.as_std_path(), package)
                                .expect("workspace package is inside workspace");
                        format!("nucleus//{}:{target}", directory.display())
                    } else if qualified {
                        format!("nucleus//{}:{target}", self.dependency_cell)
                    } else {
                        format!(":{target}")
                    };
                    (dependency.name.clone(), value)
                })
            })
            .collect::<Vec<_>>();
        dependencies.sort();
        dependencies
    }
}

fn render(template: &str, context: minijinja::Value) -> Result<String> {
    let mut environment = Environment::new();
    environment
        .add_template("BUCK", template)
        .wrap_err("invalid Buck template")?;
    let mut output = environment
        .get_template("BUCK")
        .wrap_err("missing Buck template")?
        .render(context)
        .wrap_err("could not render Buck template")?;
    output.truncate(output.trim_end().len());
    output.push('\n');
    Ok(output)
}

fn target_rule(target: &Target, external: bool) -> Option<&'static str> {
    if target.kind.contains(&TargetKind::Bin) && !external {
        Some("rust_binary")
    } else if target.kind.contains(&TargetKind::Test) && !external {
        Some("rust_test")
    } else if is_library(target) {
        Some(if external {
            "cargo.rust_library"
        } else {
            "rust_library"
        })
    } else {
        None
    }
}

/// Whether Buck's Rust rules build this package, as opposed to cargo behind a
/// `genrule`.
///
/// A package opts out with `[package.metadata.glu] buck = false`, and then gets
/// no generated `BUCK` file at all: `//crates/...` stops naming it, and
/// whichever artifact rule wants it compiles it through cargo. Two kinds of
/// package need that, and the Python bindings are both:
///
/// - The output is not a Rust library. `rust_library` produces an rlib, so
///   there is no rule here that emits a Python extension module.
/// - A dependency's build script needs cargo's `links` metadata. Buck's prelude
///   keeps only the directives it can turn into rustc arguments, so `pyo3`
///   never receives the interpreter configuration `pyo3-ffi` computed, and
///   restating it the way `LINKS_METADATA` does would mean reproducing another
///   project's build script rather than pointing at a file.
///
/// Opting out costs the package Buck's caching and its `rust_test` targets, so
/// it is worth doing only when one of those two applies. Cargo and Nix still
/// build and test the package either way.
fn buck_builds(package: &Package) -> bool {
    package
        .metadata
        .get("glu")
        .and_then(|glu| glu.get("buck"))
        .and_then(serde_json::Value::as_bool)
        .unwrap_or(true)
}

fn buck_metadata_strings(package: &Package, key: &str) -> Result<Vec<String>> {
    let Some(value) = package.metadata.get("glu").and_then(|glu| glu.get(key)) else {
        return Ok(Vec::new());
    };
    let values = value.as_array().ok_or_else(|| {
        color_eyre::eyre::eyre!(
            "package {} metadata.glu.{key} must be an array",
            package.name,
        )
    })?;
    values
        .iter()
        .map(|value| {
            value.as_str().map(ToOwned::to_owned).ok_or_else(|| {
                color_eyre::eyre::eyre!(
                    "package {} metadata.glu.{key} entries must be strings",
                    package.name,
                )
            })
        })
        .collect()
}

fn buck_features(package: &Package, features: Vec<String>) -> Result<(Vec<String>, Vec<String>)> {
    let mut test_features = features.clone();
    test_features.extend(buck_metadata_strings(package, "buck-test-features")?);
    test_features.sort();
    test_features.dedup();
    Ok((features, test_features))
}

fn buck_mapped_srcs(package: &Package, key: &str) -> Result<Vec<(String, String)>> {
    let Some(value) = package.metadata.get("glu").and_then(|glu| glu.get(key)) else {
        return Ok(Vec::new());
    };
    let values = value.as_object().ok_or_else(|| {
        color_eyre::eyre::eyre!(
            "package {} metadata.glu.{key} must be a table",
            package.name,
        )
    })?;
    values
        .iter()
        .map(|(source, destination)| {
            destination.as_str().map_or_else(
                || {
                    Err(color_eyre::eyre::eyre!(
                        "package {} metadata.glu.{key} values must be strings",
                        package.name,
                    ))
                },
                |destination| Ok((source.clone(), destination.to_owned())),
            )
        })
        .collect::<Result<_>>()
}

/// Extra sources and their local paths needed to compile test code under Buck.
fn buck_test_mapped_srcs(package: &Package) -> Result<Vec<(String, String)>> {
    buck_mapped_srcs(package, "buck-test-mapped-srcs")
}

/// Shared workspace files read relative to `CARGO_MANIFEST_DIR` at compile time.
fn buck_manifest_mapped_srcs(package: &Package) -> Result<Vec<(String, String)>> {
    buck_mapped_srcs(package, "buck-manifest-mapped-srcs")
}

fn is_library(target: &Target) -> bool {
    target.kind.iter().any(|kind| {
        matches!(
            kind,
            TargetKind::Lib
                | TargetKind::RLib
                | TargetKind::CDyLib
                | TargetKind::StaticLib
                | TargetKind::DyLib
                | TargetKind::ProcMacro
        )
    })
}

fn label(package: &Package) -> String {
    format!("{}-{}", package.name, package.version)
}

fn stable_workspace_id(package: &Package) -> String {
    format!("workspace#{}@{}", package.name, package.version)
}

fn relative_target_path(package: &Package, target: &Target) -> String {
    target
        .src_path
        .as_std_path()
        .strip_prefix(
            package
                .manifest_path
                .as_std_path()
                .parent()
                .expect("manifest has a parent"),
        )
        .expect("target is inside package")
        .to_string_lossy()
        .into_owned()
}

fn package_directory(root: &Path, package: &Package) -> Result<PathBuf> {
    package
        .manifest_path
        .as_std_path()
        .parent()
        .and_then(|path| path.strip_prefix(root).ok())
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            color_eyre::eyre::eyre!("{} is outside the repository", package.manifest_path)
        })
}

fn cargo_package_env(package: &Package) -> Vec<(String, String)> {
    let version = &package.version;
    [
        ("CARGO_PKG_AUTHORS", package.authors.join(":")),
        (
            "CARGO_PKG_DESCRIPTION",
            package.description.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_HOMEPAGE",
            package.homepage.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE",
            package.license.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE_FILE",
            package
                .license_file
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("CARGO_PKG_NAME", package.name.to_string()),
        ("CARGO_PKG_README", String::new()),
        (
            "CARGO_PKG_REPOSITORY",
            package.repository.clone().unwrap_or_default(),
        ),
        ("CARGO_PKG_RUST_VERSION", String::new()),
        ("CARGO_PKG_VERSION", version.to_string()),
        ("CARGO_PKG_VERSION_MAJOR", version.major.to_string()),
        ("CARGO_PKG_VERSION_MINOR", version.minor.to_string()),
        ("CARGO_PKG_VERSION_PATCH", version.patch.to_string()),
        ("CARGO_PKG_VERSION_PRE", version.pre.to_string()),
    ]
    .into_iter()
    .map(|(name, value)| (name.to_owned(), value))
    .collect()
}

fn external_package_env(package: &Package) -> BTreeMap<String, String> {
    cargo_package_env(package)
        .into_iter()
        .filter(|(name, value)| {
            !value.is_empty()
                && !matches!(
                    name.as_str(),
                    "CARGO_PKG_NAME"
                        | "CARGO_PKG_VERSION"
                        | "CARGO_PKG_VERSION_MAJOR"
                        | "CARGO_PKG_VERSION_MINOR"
                        | "CARGO_PKG_VERSION_PATCH"
                )
        })
        .collect()
}
