use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use cargo_lock::Lockfile;
use cargo_metadata::{DependencyKind, Metadata, Node, Package, PackageId, Target, TargetKind};
use color_eyre::eyre::{Result, WrapErr, bail};
use minijinja::{Environment, context};
use serde::Serialize;

use crate::cargo;

const HEADER: &str = "# @generated by `glu buck sync`; do not edit.\n\
                      # Cargo.toml and Cargo.lock are authoritative.\n";

const WORKSPACE_TEMPLATE: &str = r#"{{ header }}
_PACKAGE_FILES = glob(
    ["**"],
    exclude = ["BUCK", "target/**"],
)

_RUST_SOURCES = glob(
    ["**/*.rs"],
    exclude = ["target/**"],
)

filegroup(
    name = "package_files",
    srcs = _PACKAGE_FILES,
    visibility = ["PUBLIC"],
)

{% for target in targets -%}
{{ target.rule }}(
    name = {{ target.name|tojson }},
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.unit_test %}
    tests = [":{{ target.name }}-unit-test"],
{%- endif %}
{%- if target.proc_macro %}
    proc_macro = True,
{%- endif %}
{%- if target.named_deps %}
    named_deps = {
{%- for name, dependency in target.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
    visibility = ["PUBLIC"],
)

{% if target.unit_test -%}
rust_test(
    name = "{{ target.name }}-unit-test",
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
    srcs = _RUST_SOURCES,
{%- if target.named_deps %}
    named_deps = {
{%- for name, dependency in target.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
    visibility = ["PUBLIC"],
)

{% endif -%}
{% endfor -%}
"#;

const EXTERNAL_TEMPLATE: &str = r#"{{ header }}
load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")

{% for package in packages -%}
http_archive(
    name = {{ package.archive|tojson }},
    sha256 = {{ package.checksum|tojson }},
    strip_prefix = {{ package.archive_prefix|tojson }},
    urls = [{{ package.url|tojson }}],
    visibility = [],
)

{% for target in package.targets -%}
{{ target.rule }}(
    name = {{ target.name|tojson }},
    srcs = [{{ package.archive_label|tojson }}],
    crate = {{ target.crate_name|tojson }},
    crate_root = {{ target.crate_root|tojson }},
    edition = {{ target.edition|tojson }},
{%- if target.features %}
    features = [
{%- for feature in target.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if target.proc_macro %}
    proc_macro = True,
{%- endif %}
{%- if target.env %}
    env = {
{%- for name, value in target.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if target.buildscript %}
    rustc_flags = ["@$(location :{{ target.buildscript }}[rustc_flags])"],
{%- endif %}
{%- if target.named_deps %}
    named_deps = {
{%- for name, dependency in target.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
    visibility = ["PUBLIC"],
)

{% endfor -%}
{% if package.buildscript -%}
cargo.rust_binary(
    name = {{ package.buildscript.name|tojson }},
    srcs = [{{ package.archive_label|tojson }}],
    crate = "build_script_build",
    crate_root = {{ package.buildscript.crate_root|tojson }},
    edition = {{ package.buildscript.edition|tojson }},
{%- if package.buildscript.features %}
    features = [
{%- for feature in package.buildscript.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
{%- if package.buildscript.named_deps %}
    named_deps = {
{%- for name, dependency in package.buildscript.named_deps %}
        {{ name|tojson }}: {{ dependency|tojson }},
{%- endfor %}
    },
{%- endif %}
    env = {
{%- for name, value in package.buildscript.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
    visibility = [],
)

buildscript_run(
    name = {{ package.buildscript.run_name|tojson }},
    package_name = {{ package.name|tojson }},
    buildscript_rule = ":{{ package.buildscript.name }}",
    rustc_link_lib = True,
    rustc_link_search = True,
    version = {{ package.version|tojson }},
{%- if package.buildscript.env %}
    env = {
{%- for name, value in package.buildscript.env %}
        {{ name|tojson }}: {{ value|tojson }},
{%- endfor %}
    },
{%- endif %}
{%- if package.buildscript.features %}
    features = [
{%- for feature in package.buildscript.features %}
        {{ feature|tojson }},
{%- endfor %}
    ],
{%- endif %}
)

{% endif -%}
{% endfor -%}
"#;

#[derive(Serialize)]
struct RustTarget {
    rule: &'static str,
    name: String,
    crate_name: String,
    crate_root: String,
    edition: String,
    features: Vec<String>,
    named_deps: Vec<(String, String)>,
    proc_macro: bool,
    buildscript: Option<String>,
    env: Vec<(String, String)>,
    unit_test: bool,
}

#[derive(Serialize)]
struct ExternalPackage {
    name: String,
    version: String,
    archive: String,
    archive_prefix: String,
    archive_label: String,
    checksum: String,
    url: String,
    targets: Vec<RustTarget>,
    buildscript: Option<Buildscript>,
}

#[derive(Serialize)]
struct Buildscript {
    name: String,
    run_name: String,
    crate_root: String,
    edition: String,
    features: Vec<String>,
    named_deps: Vec<(String, String)>,
    env: Vec<(String, String)>,
}

struct Graph<'a> {
    metadata: &'a Metadata,
    nodes: BTreeMap<&'a PackageId, &'a Node>,
    packages: BTreeMap<&'a PackageId, &'a Package>,
    workspace: BTreeSet<&'a PackageId>,
    dependency_cell: &'a str,
}

pub(crate) fn sync(root: &Path) -> Result<usize> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut changed = 0;
    for (path, contents) in files {
        let path = root.join(path);
        if fs::read_to_string(&path).ok().as_deref() == Some(&contents) {
            continue;
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .wrap_err_with(|| format!("could not create {}", parent.display()))?;
        }
        fs::write(&path, contents)
            .wrap_err_with(|| format!("could not write {}", path.display()))?;
        changed += 1;
    }
    for path in discovered_generated_files(root)?.difference(&expected) {
        fs::remove_file(root.join(path))
            .wrap_err_with(|| format!("could not remove stale {}", path.display()))?;
        changed += 1;
    }
    Ok(changed)
}

pub(crate) fn check(root: &Path) -> Result<()> {
    let files = generated_files(root)?;
    let expected = files
        .iter()
        .map(|(path, _)| path.clone())
        .collect::<BTreeSet<_>>();
    let mut stale = files
        .into_iter()
        .filter_map(|(path, expected)| {
            let actual = fs::read_to_string(root.join(&path)).ok();
            (actual.as_deref() != Some(&expected)).then_some(path)
        })
        .collect::<Vec<_>>();
    stale.extend(
        discovered_generated_files(root)?
            .difference(&expected)
            .cloned(),
    );
    stale.sort();
    if !stale.is_empty() {
        bail!(
            "generated Buck files are stale:\n{}\nrun `glu buck sync`",
            stale
                .iter()
                .map(|path| format!("  - {}", path.display()))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
    Ok(())
}

fn discovered_generated_files(root: &Path) -> Result<BTreeSet<PathBuf>> {
    let mut directories = ["crates", "tools/glu", "buck/cargo"]
        .map(|path| root.join(path))
        .to_vec();
    let mut files = BTreeSet::new();
    while let Some(directory) = directories.pop() {
        for entry in fs::read_dir(&directory)
            .wrap_err_with(|| format!("could not read {}", directory.display()))?
        {
            let entry = entry.wrap_err("could not read Buck source directory")?;
            let path = entry.path();
            if entry
                .file_type()
                .wrap_err_with(|| format!("could not inspect {}", path.display()))?
                .is_dir()
            {
                if entry.file_name() != "target" {
                    directories.push(path);
                }
            } else if entry.file_name() == "BUCK"
                && fs::read_to_string(&path).is_ok_and(|contents| contents.starts_with(HEADER))
            {
                files.insert(
                    path.strip_prefix(root)
                        .expect("discovered path is inside the repository")
                        .to_owned(),
                );
            }
        }
    }
    Ok(files)
}

fn generated_files(root: &Path) -> Result<Vec<(PathBuf, String)>> {
    let mut files = Vec::new();
    files.extend(generate_workspace(
        root,
        &root.join("Cargo.toml"),
        "buck/cargo/production",
    )?);
    files.extend(generate_workspace(
        root,
        &root.join("tools/glu/Cargo.toml"),
        "buck/cargo/glu",
    )?);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(files)
}

fn generate_workspace(
    root: &Path,
    manifest: &Path,
    dependency_cell: &str,
) -> Result<Vec<(PathBuf, String)>> {
    let metadata = cargo::load_manifest(root, manifest)?;
    let graph = Graph::new(&metadata, dependency_cell)?;
    let lockfile = Lockfile::load(
        manifest
            .parent()
            .expect("manifest has a parent")
            .join("Cargo.lock"),
    )
    .wrap_err_with(|| format!("could not read lockfile for {}", manifest.display()))?;
    let checksums = lockfile
        .packages
        .iter()
        .filter_map(|package| {
            package.checksum.as_ref().map(|checksum| {
                (
                    (package.name.to_string(), package.version.to_string()),
                    checksum.to_string(),
                )
            })
        })
        .collect::<BTreeMap<_, _>>();

    let mut files = Vec::new();
    for package in graph.workspace_packages() {
        let directory = package_directory(root, package)?;
        let targets = package
            .targets
            .iter()
            .filter_map(|target| graph.workspace_target(package, target).transpose())
            .collect::<Result<Vec<_>>>()?;
        files.push((
            directory.join("BUCK"),
            render(
                WORKSPACE_TEMPLATE,
                context!(header => HEADER, targets => targets),
            )?,
        ));
    }

    let packages = graph
        .external_packages(&checksums)?
        .into_iter()
        .collect::<Vec<_>>();
    files.push((
        PathBuf::from(dependency_cell).join("BUCK"),
        render(
            EXTERNAL_TEMPLATE,
            context!(header => HEADER, packages => packages),
        )?,
    ));
    Ok(files)
}

impl<'a> Graph<'a> {
    fn new(metadata: &'a Metadata, dependency_cell: &'a str) -> Result<Self> {
        let resolve = metadata.resolve.as_ref().ok_or_else(|| {
            color_eyre::eyre::eyre!("Cargo metadata did not include a resolve graph")
        })?;
        Ok(Self {
            metadata,
            nodes: resolve.nodes.iter().map(|node| (&node.id, node)).collect(),
            packages: metadata
                .packages
                .iter()
                .map(|package| (&package.id, package))
                .collect(),
            workspace: metadata.workspace_members.iter().collect(),
            dependency_cell,
        })
    }

    fn workspace_packages(&self) -> Vec<&'a Package> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| self.workspace.contains(&package.id))
            .collect::<Vec<_>>();
        packages.sort_by_key(|package| package.name.as_str());
        packages
    }

    fn workspace_target(&self, package: &Package, target: &Target) -> Result<Option<RustTarget>> {
        let Some(rule) = target_rule(target, false) else {
            return Ok(None);
        };
        let package_root = package
            .manifest_path
            .as_std_path()
            .parent()
            .expect("manifest has a parent");
        let crate_root = target
            .src_path
            .as_std_path()
            .strip_prefix(package_root)
            .wrap_err("crate root is outside its package")?
            .to_string_lossy()
            .into_owned();
        let mut named_deps = self.dependencies(&package.id, DependencyKind::Normal, true);
        if target.kind.contains(&TargetKind::Test)
            && let Some(library) = package
                .targets
                .iter()
                .find(|candidate| is_library(candidate))
        {
            named_deps.push((library.name.replace('-', "_"), format!(":{}", library.name)));
            named_deps.sort();
        }
        Ok(Some(RustTarget {
            rule,
            name: target.name.clone(),
            crate_name: target.name.replace('-', "_"),
            crate_root,
            edition: package.edition.to_string(),
            features: Vec::new(),
            named_deps,
            proc_macro: target.kind.contains(&TargetKind::ProcMacro),
            buildscript: None,
            env: cargo_package_env(package),
            unit_test: is_library(target) || target.kind.contains(&TargetKind::Bin),
        }))
    }

    fn external_packages(
        &self,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<Vec<ExternalPackage>> {
        let mut packages = self
            .metadata
            .packages
            .iter()
            .filter(|package| !self.workspace.contains(&package.id))
            .map(|package| self.external_package(package, checksums))
            .collect::<Result<Vec<_>>>()?;
        packages.sort_by(|left, right| {
            left.name
                .cmp(&right.name)
                .then_with(|| left.version.cmp(&right.version))
        });
        Ok(packages)
    }

    fn external_package(
        &self,
        package: &Package,
        checksums: &BTreeMap<(String, String), String>,
    ) -> Result<ExternalPackage> {
        if package
            .source
            .as_ref()
            .is_none_or(|source| !source.is_crates_io())
        {
            bail!(
                "{} {} is not from crates.io and cannot be acquired by Buck",
                package.name,
                package.version
            );
        }
        let name = package.name.to_string();
        let version = package.version.to_string();
        let label = label(package);
        let archive = format!("{label}.crate");
        let archive_prefix = format!("{name}-{version}");
        let checksum = checksums
            .get(&(name.clone(), version.clone()))
            .cloned()
            .ok_or_else(|| {
                color_eyre::eyre::eyre!("missing registry checksum for {name} {version}")
            })?;
        let features = self
            .nodes
            .get(&package.id)
            .map(|node| {
                let mut features = node
                    .features
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>();
                features.sort();
                features
            })
            .unwrap_or_default();
        let build_target = package
            .targets
            .iter()
            .find(|target| target.kind.contains(&TargetKind::CustomBuild));
        let buildscript = build_target.map(|target| {
            let mut env = cargo_package_env(package);
            env.push((
                "CARGO_MANIFEST_DIR".to_owned(),
                format!("$(location :{archive})"),
            ));
            env.extend([
                ("DEBUG".to_owned(), "true".to_owned()),
                ("OPT_LEVEL".to_owned(), "0".to_owned()),
                ("PROFILE".to_owned(), "debug".to_owned()),
            ]);
            Buildscript {
                name: format!("{label}-build-script-build"),
                run_name: format!("{label}-build-script-run"),
                crate_root: format!("{archive}/{}", relative_target_path(package, target)),
                edition: package.edition.to_string(),
                features: features.clone(),
                named_deps: self.dependencies(&package.id, DependencyKind::Build, false),
                env,
            }
        });
        let targets = package
            .targets
            .iter()
            .filter_map(|target| {
                let rule = target_rule(target, true)?;
                let target_buildscript = buildscript.as_ref().map(|script| script.run_name.clone());
                let mut env = cargo_package_env(package);
                if let Some(run_name) = &target_buildscript {
                    env.push((
                        "OUT_DIR".to_owned(),
                        format!("$(location :{run_name}[out_dir])"),
                    ));
                }
                Some(RustTarget {
                    rule,
                    name: label.clone(),
                    crate_name: target.name.replace('-', "_"),
                    crate_root: format!("{archive}/{}", relative_target_path(package, target)),
                    edition: package.edition.to_string(),
                    features: features.clone(),
                    named_deps: self.dependencies(&package.id, DependencyKind::Normal, false),
                    proc_macro: target.kind.contains(&TargetKind::ProcMacro),
                    buildscript: target_buildscript,
                    env,
                    unit_test: false,
                })
            })
            .collect();

        Ok(ExternalPackage {
            name: name.clone(),
            version: version.clone(),
            archive: archive.clone(),
            archive_prefix,
            archive_label: format!(":{archive}"),
            checksum,
            url: format!("https://crates.io/api/v1/crates/{name}/{version}/download"),
            targets,
            buildscript,
        })
    }

    fn dependencies(
        &self,
        package: &PackageId,
        kind: DependencyKind,
        qualified: bool,
    ) -> Vec<(String, String)> {
        let mut dependencies = self
            .nodes
            .get(package)
            .into_iter()
            .flat_map(|node| &node.deps)
            .filter(|dependency| {
                dependency
                    .dep_kinds
                    .iter()
                    .any(|dependency_kind| dependency_kind.kind == kind)
            })
            .filter_map(|dependency| {
                self.packages.get(&dependency.pkg).map(|package| {
                    let target = package
                        .targets
                        .iter()
                        .find(|target| is_library(target))
                        .map_or_else(
                            || label(package),
                            |target| {
                                if self.workspace.contains(&package.id) {
                                    target.name.clone()
                                } else {
                                    label(package)
                                }
                            },
                        );
                    let value = if self.workspace.contains(&package.id) {
                        let directory =
                            package_directory(self.metadata.workspace_root.as_std_path(), package)
                                .expect("workspace package is inside workspace");
                        format!("nucleus//{}:{target}", directory.display())
                    } else if qualified {
                        format!("nucleus//{}:{target}", self.dependency_cell)
                    } else {
                        format!(":{target}")
                    };
                    (dependency.name.clone(), value)
                })
            })
            .collect::<Vec<_>>();
        dependencies.sort();
        dependencies
    }
}

fn render(template: &str, context: minijinja::Value) -> Result<String> {
    let mut environment = Environment::new();
    environment
        .add_template("BUCK", template)
        .wrap_err("invalid Buck template")?;
    let mut output = environment
        .get_template("BUCK")
        .wrap_err("missing Buck template")?
        .render(context)
        .wrap_err("could not render Buck template")?;
    output.truncate(output.trim_end().len());
    output.push('\n');
    Ok(output)
}

fn target_rule(target: &Target, external: bool) -> Option<&'static str> {
    if target.kind.contains(&TargetKind::Bin) && !external {
        Some("rust_binary")
    } else if target.kind.contains(&TargetKind::Test) && !external {
        Some("rust_test")
    } else if is_library(target) {
        Some(if external {
            "cargo.rust_library"
        } else {
            "rust_library"
        })
    } else {
        None
    }
}

fn is_library(target: &Target) -> bool {
    target.kind.iter().any(|kind| {
        matches!(
            kind,
            TargetKind::Lib
                | TargetKind::RLib
                | TargetKind::CDyLib
                | TargetKind::StaticLib
                | TargetKind::DyLib
                | TargetKind::ProcMacro
        )
    })
}

fn label(package: &Package) -> String {
    format!("{}-{}", package.name, package.version)
}

fn relative_target_path(package: &Package, target: &Target) -> String {
    target
        .src_path
        .as_std_path()
        .strip_prefix(
            package
                .manifest_path
                .as_std_path()
                .parent()
                .expect("manifest has a parent"),
        )
        .expect("target is inside package")
        .to_string_lossy()
        .into_owned()
}

fn package_directory(root: &Path, package: &Package) -> Result<PathBuf> {
    package
        .manifest_path
        .as_std_path()
        .parent()
        .and_then(|path| path.strip_prefix(root).ok())
        .map(Path::to_path_buf)
        .ok_or_else(|| {
            color_eyre::eyre::eyre!("{} is outside the repository", package.manifest_path)
        })
}

fn cargo_package_env(package: &Package) -> Vec<(String, String)> {
    let version = &package.version;
    [
        ("CARGO_PKG_AUTHORS", package.authors.join(":")),
        (
            "CARGO_PKG_DESCRIPTION",
            package.description.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_HOMEPAGE",
            package.homepage.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE",
            package.license.clone().unwrap_or_default(),
        ),
        (
            "CARGO_PKG_LICENSE_FILE",
            package
                .license_file
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("CARGO_PKG_NAME", package.name.to_string()),
        ("CARGO_PKG_README", String::new()),
        (
            "CARGO_PKG_REPOSITORY",
            package.repository.clone().unwrap_or_default(),
        ),
        ("CARGO_PKG_RUST_VERSION", String::new()),
        ("CARGO_PKG_VERSION", version.to_string()),
        ("CARGO_PKG_VERSION_MAJOR", version.major.to_string()),
        ("CARGO_PKG_VERSION_MINOR", version.minor.to_string()),
        ("CARGO_PKG_VERSION_PATCH", version.patch.to_string()),
        ("CARGO_PKG_VERSION_PRE", version.pre.to_string()),
    ]
    .into_iter()
    .map(|(name, value)| (name.to_owned(), value))
    .collect()
}
