use std::{
    cell::Cell,
    collections::BTreeMap,
    env,
    ffi::{OsStr, OsString},
    fs,
    io::{self, BufRead, BufReader, Write},
    path::{Path, PathBuf},
    process::{Child, Command, Output, Stdio},
    time::Instant,
};

use color_eyre::eyre::{Result, WrapErr, bail, eyre};

use crate::{BuildTarget, buck, cargo, loc};

const BUCK_CONFIG_HEADER: &str = "# @generated by `glu buck configure`; do not edit.";

pub(crate) struct Runner {
    root: PathBuf,
    verbose: u8,
    buck_checked: Cell<bool>,
}

impl Runner {
    pub(crate) const fn new(root: PathBuf, verbose: u8) -> Self {
        Self {
            root,
            verbose,
            buck_checked: Cell::new(false),
        }
    }

    fn command<I, S>(&self, phase: &str, program: &str, args: I) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        self.command_with_env(phase, program, args, &[])
    }

    fn command_with_env<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, &OsStr)],
    ) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let args: Vec<OsString> = args.into_iter().map(|arg| arg.as_ref().into()).collect();
        if self.verbose > 0 {
            eprintln!(
                "  $ {program} {}",
                args.iter()
                    .map(|arg| arg.to_string_lossy())
                    .collect::<Vec<_>>()
                    .join(" ")
            );
        }

        Command::new(program)
            .args(&args)
            .env("CC_wasm32_unknown_unknown", "nucleus-wasm-clang")
            .env("CC_wasm32_wasip1", "wasm32-unknown-wasi-cc")
            .env("CC_wasm32_wasip2", "wasm32-unknown-wasi-cc")
            .envs(environment.iter().copied())
            .current_dir(&self.root)
            .output()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))
    }

    pub(crate) fn run<I, S>(&self, phase: &str, program: &str, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        self.run_with_env(phase, program, args, &[])
    }

    pub(crate) fn run_with_env<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, &OsStr)],
    ) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let started = Instant::now();
        eprint!("• {phase}…");
        let output = self.command_with_env(phase, program, args, environment)?;

        if self.verbose > 1 || !output.status.success() {
            eprintln!();
            print!("{}", String::from_utf8_lossy(&output.stdout));
            eprint!("{}", String::from_utf8_lossy(&output.stderr));
        }
        if !output.status.success() {
            bail!("{phase} failed with {}", output.status);
        }

        eprintln!(" done ({:.2?})", started.elapsed());
        Ok(())
    }

    pub(crate) fn root(&self) -> &Path {
        &self.root
    }

    pub(crate) const fn verbose(&self) -> u8 {
        self.verbose
    }

    fn exec<I, S>(&self, phase: &str, program: &str, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let status = Command::new(program)
            .args(args)
            .current_dir(&self.root)
            .status()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))?;
        if !status.success() {
            bail!("{phase} failed with {status}");
        }
        Ok(())
    }

    fn cargo(&self, phase: &str, args: &[&str]) -> Result<()> {
        let mut full = vec!["--locked"];
        full.extend_from_slice(args);
        self.run(phase, "cargo", full)
    }

    fn cargo_streaming(&self, phase: &str, args: &[&str]) -> Result<()> {
        let started = Instant::now();
        let mut full = vec!["--locked"];
        full.extend_from_slice(args);
        eprintln!("• {phase}…");
        let status = Command::new("cargo")
            .args(full)
            .current_dir(&self.root)
            .status()
            .wrap_err_with(|| format!("{phase}: could not run cargo"))?;
        if !status.success() {
            bail!("{phase} failed with {status}");
        }
        eprintln!("• {phase} done ({:.2?})", started.elapsed());
        Ok(())
    }

    fn tool_cargo(&self, phase: &str, args: &[&str]) -> Result<()> {
        let (command, rest) = args.split_first().expect("Cargo command is present");
        let mut full = vec![*command];
        if *command != "fmt" {
            full.push("--locked");
        }
        full.extend(["--manifest-path", "tools/glu/Cargo.toml"]);
        full.extend_from_slice(rest);
        self.run(phase, "cargo", full)
    }

    fn pnpm(&self, phase: &str, args: &[&str]) -> Result<()> {
        self.run(phase, "pnpm", args)
    }

    pub(crate) fn fmt(&self, check: bool) -> Result<()> {
        let cargo_args = if check {
            &["fmt", "--all", "--", "--check"][..]
        } else {
            &["fmt", "--all"][..]
        };
        self.cargo("format production", cargo_args)?;
        self.tool_cargo("format glu", cargo_args)?;
        self.pnpm(
            "format web",
            &[
                "exec",
                "prettier",
                if check { "--check" } else { "--write" },
                ".",
            ],
        )
    }

    pub(crate) fn lint(&self) -> Result<()> {
        self.cargo(
            "lint production",
            &[
                "clippy",
                "--workspace",
                "--all-targets",
                "--",
                "-D",
                "warnings",
            ],
        )?;
        self.tool_cargo(
            "lint glu",
            &["clippy", "--all-targets", "--", "-D", "warnings"],
        )?;
        self.build(BuildTarget::Wasm)?;
        self.pnpm("lint web", &["run", "lint"])
    }

    pub(crate) fn test(&self, container: bool, cargo: bool) -> Result<()> {
        if container && env::var_os("NUCLEUS_DEVCONTAINER").is_none() {
            let root = self.root.to_string_lossy();
            self.run(
                "start dev container",
                "devcontainer",
                ["up", "--workspace-folder", root.as_ref()],
            )?;
            let mut arguments = vec!["exec", "--workspace-folder", root.as_ref(), "glu", "test"];
            if cargo {
                arguments.push("--cargo");
            }
            return self.exec("test in dev container", "devcontainer", arguments);
        }

        if cargo {
            self.cargo_streaming("test Cargo compatibility", &["test", "--workspace"])?;
            self.run_with_env(
                "test JavaScript-hosted Wasm randomness",
                "cargo",
                [
                    "test",
                    "--locked",
                    "-p",
                    "covalence-lib-rand",
                    "--target",
                    "wasm32-unknown-unknown",
                ],
                &[(
                    "CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER",
                    OsStr::new("wasm-bindgen-test-runner"),
                )],
            )?;
        }
        self.exec("test Buck Rust targets", "buck2", ["test", "//crates/..."])?;
        self.build(BuildTarget::Wasm)?;
        self.pnpm("test web", &["run", "test"])?;
        self.test_components()?;
        let cli = self.buck_output("//crates/bin/nucleus:nucleus")?;
        let cli = cli.to_string_lossy();
        let output = self.command("test nucleus CLI", cli.as_ref(), std::iter::empty::<&str>())?;
        expect_output(
            "nucleus CLI smoke test",
            &output,
            "hello from nucleus: SQLite returned 42",
        )?;
        eprintln!("• test nucleus CLI… done");
        Ok(())
    }

    pub(crate) fn build(&self, target: BuildTarget) -> Result<()> {
        match target {
            BuildTarget::All => self.build_all(),
            BuildTarget::Native => {
                self.buck_check()?;
                self.run("build native targets", "buck2", ["build", "//crates/..."])
            }
            BuildTarget::Wasm => {
                self.buck_check()?;
                let source = self.buck_output("//:wasm")?;
                self.materialize_wasm(&source)?;
                eprintln!("• build Wasm package… done");
                Ok(())
            }
            BuildTarget::Docs => self.docs(),
        }
    }

    fn build_all(&self) -> Result<()> {
        self.buck_check()?;
        let mut arguments = vec![
            "build".to_owned(),
            "//crates/...".to_owned(),
            "//:wasm".to_owned(),
            "//:docs".to_owned(),
        ];
        arguments.extend(self.docs_config()?);
        arguments.push("--show-full-json-output".to_owned());
        let outputs = self.buck_outputs("build all targets", &arguments)?;
        self.materialize_wasm(required_output(&outputs, "nucleus//:wasm")?)?;
        replace_dir(
            required_output(&outputs, "nucleus//:docs")?,
            &self.root.join("apps/docs/build"),
        )?;
        eprintln!("• build all targets… done");
        Ok(())
    }

    fn materialize_wasm(&self, source: &Path) -> Result<()> {
        replace_dir(
            &source.join("generated"),
            &self.root.join("packages/nucleus/generated"),
        )?;
        replace_dir(
            &source.join("dist"),
            &self.root.join("packages/nucleus/dist"),
        )
    }

    pub(crate) fn check(&self) -> Result<()> {
        self.fmt(true)?;
        self.lint()?;
        self.deps_check()?;
        self.loc()?;
        self.test(false, true)?;
        self.build(BuildTarget::All)
    }

    pub(crate) fn ci(&self) -> Result<()> {
        self.check()
    }

    pub(crate) fn deps_check(&self) -> Result<()> {
        let summary = cargo::check(&self.root)?;
        eprintln!(
            "dependencies: {} workspace packages, {} external packages, {} edges",
            summary.workspace_packages, summary.external_packages, summary.edges
        );
        Ok(())
    }

    pub(crate) fn loc(&self) -> Result<()> {
        println!("{}", loc::count(&self.root, self.verbose > 0)?);
        io::stdout()
            .flush()
            .wrap_err("could not flush LoC report")?;
        Ok(())
    }

    pub(crate) fn status(&self) -> Result<()> {
        println!("{}", loc::count(&self.root, self.verbose > 0)?.headline());
        io::stdout()
            .flush()
            .wrap_err("could not flush status report")?;
        Ok(())
    }

    pub(crate) fn buck_sync(&self) -> Result<()> {
        let changed = buck::sync(&self.root)?;
        self.buck_checked.set(false);
        if changed == 0 {
            eprintln!("Buck files are up to date");
        } else {
            eprintln!("updated {changed} generated Buck file(s)");
        }
        Ok(())
    }

    pub(crate) fn buck_check(&self) -> Result<()> {
        if !self.buck_checked.get() {
            buck::check(&self.root)?;
            self.buck_checked.set(true);
        }
        Ok(())
    }

    pub(crate) fn buck_configure(&self) -> Result<()> {
        self.write_buck_configuration()?;
        eprintln!("configured Buck tool paths");
        Ok(())
    }

    fn write_buck_configuration(&self) -> Result<()> {
        let path = self.root.join(".buckconfig.local");
        let configuration = Self::buck_configuration()?;
        if path.exists() {
            let current = fs::read_to_string(&path).wrap_err("could not read .buckconfig.local")?;
            let generated = matches!(
                current.lines().next(),
                Some(BUCK_CONFIG_HEADER | "# Generated by `glu buck configure`.")
            );
            if current != configuration && !generated {
                bail!(
                    "{} already exists and was not generated by glu",
                    path.display()
                );
            }
        }
        fs::write(&path, configuration)
            .wrap_err_with(|| format!("could not write {}", path.display()))
    }

    fn buck_configuration() -> Result<String> {
        let ar = command_path("ar")?;
        let cc = command_path("clang")?;
        let cxx = command_path("clang++")?;
        Ok(format!(
            "{BUCK_CONFIG_HEADER}\n\
             [nucleus]\n\
               ar = {}\n\
               cc = {}\n\
               cxx = {}\n",
            ar.display(),
            cc.display(),
            cxx.display(),
        ))
    }

    pub(crate) fn doctor(&self) -> Result<()> {
        for tool in [
            "buck2",
            "caddy",
            "cargo",
            "chromium",
            "devcontainer",
            "rustc",
            "node",
            "pnpm",
            "python3",
            "scc",
            "git",
            "wasm-bindgen",
            "wasm-tools",
            "wasmtime",
        ] {
            self.run(tool, tool, ["--version"])?;
        }
        self.run("cargo component", "cargo", ["component", "--version"])
    }

    pub(crate) fn docs(&self) -> Result<()> {
        self.buck_check()?;
        let mut arguments = vec!["build".to_owned(), "//:docs".to_owned()];
        arguments.extend(self.docs_config()?);
        arguments.push("--show-full-simple-output".to_owned());
        self.build_and_materialize_with_args(
            "build documentation site",
            &arguments,
            &self.root.join("apps/docs/build"),
        )
    }

    fn docs_config(&self) -> Result<Vec<String>> {
        let mut arguments = Vec::new();
        if let Ok(base_path) = env::var("BASE_PATH") {
            if !valid_base_path(&base_path) {
                bail!("BASE_PATH must be empty or a slash followed by a URL-safe path");
            }
            arguments.extend(["--config".to_owned(), format!("docs.base_path={base_path}")]);
        }
        let commit = self
            .command("read source commit", "git", ["rev-parse", "HEAD"])?
            .stdout;
        let commit = String::from_utf8(commit)
            .unwrap_or_else(|_| "unknown".to_owned())
            .trim()
            .to_owned();
        let commit = if commit.len() == 40
            && commit
                .chars()
                .all(|character| character.is_ascii_hexdigit())
        {
            commit
        } else {
            "unknown".to_owned()
        };
        let status = self.command("read source status", "git", ["status", "--porcelain"])?;
        let dirty = !status.status.success() || !status.stdout.is_empty();
        arguments.extend([
            "--config".to_owned(),
            format!("docs.commit={commit}"),
            "--config".to_owned(),
            format!("docs.dirty={dirty}"),
        ]);
        Ok(arguments)
    }

    /// Builds the browser demo, starts a kernel behind it, and serves it.
    ///
    /// Three things have to line up for the demo to be interesting, and doing
    /// them by hand is three chances to get one wrong: the wasm has to be
    /// built, an HTTP kernel has to be holding a database, and the page has to
    /// know that database's address. This does all three and prints the
    /// address, so the only manual step left is pasting it.
    ///
    /// Both servers are children of this process and share its process group,
    /// so Ctrl-C stops all three. The kernel is also killed explicitly when
    /// the page server exits normally. A signal delivered to this process
    /// alone rather than to the group would leave them running, which is a
    /// limitation of not being able to use `prctl` here: this crate forbids
    /// `unsafe`.
    ///
    /// # Errors
    ///
    /// Returns an error if the build fails, no database can be served, or
    /// either server cannot start.
    pub(crate) fn demo(
        &self,
        files: &[PathBuf],
        port: u16,
        kernel_port: u16,
        open: bool,
        no_build: bool,
    ) -> Result<()> {
        // The committed fixture, so `glu demo` with no arguments still shows
        // something rather than an empty store.
        let default = self.root.join("packages/nucleus/test/fixture.sqlite");
        let files: Vec<PathBuf> = if files.is_empty() {
            vec![default]
        } else {
            files.to_vec()
        };
        for file in &files {
            if !file.is_file() {
                bail!("{} is not a file", file.display());
            }
        }

        if !no_build {
            self.pnpm("build browser demo", &["--dir", "packages/nucleus", "build"])?;
            self.cargo("build demo kernel", &["build", "-p", "covalence-bin-cas-serve"])?;
        }

        let mut kernel = self.start_kernel(&files, kernel_port)?;
        let page = format!("http://127.0.0.1:{port}/demo.html");

        eprintln!();
        eprintln!("  demo      {page}");
        eprintln!("  kernel    http://127.0.0.1:{kernel_port}");
        eprintln!();
        eprintln!("  Sections 1 and 3 need only a file from your disk.");
        eprintln!("  For section 2, paste an address above into the page.");
        eprintln!();

        if open {
            // A failure here is not worth stopping for; the URL is printed.
            let _ = self.run("open demo", "xdg-open", [page.as_str()]);
        }

        let served = self.exec(
            "serve demo",
            "caddy",
            [
                OsStr::new("file-server"),
                OsStr::new("--root"),
                self.root.join("packages/nucleus").as_os_str(),
                OsStr::new("--listen"),
                OsStr::new(&format!("127.0.0.1:{port}")),
            ],
        );

        // The kernel is a child of this process, so it must not outlive it.
        let _ = kernel.kill();
        let _ = kernel.wait();
        served
    }

    /// Starts the HTTP kernel and reports the addresses it admitted.
    ///
    /// The kernel prints one `address path` line per file and then its base
    /// URL, so reading until the URL both collects the addresses and confirms
    /// it is listening.
    fn start_kernel(&self, files: &[PathBuf], port: u16) -> Result<Child> {
        let binary = self.root.join("target/debug/covalence-cas-serve");
        let mut child = Command::new(&binary)
            .arg("--port")
            .arg(port.to_string())
            .args(files)
            .current_dir(&self.root)
            .stdout(Stdio::piped())
            .spawn()
            .wrap_err_with(|| format!("could not start {}", binary.display()))?;

        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| eyre!("demo kernel produced no output"))?;
        let mut reader = BufReader::new(stdout);
        let mut line = String::new();
        loop {
            line.clear();
            if reader.read_line(&mut line)? == 0 {
                let _ = child.kill();
                bail!("demo kernel exited before it started listening");
            }
            let line = line.trim_end();
            if line.starts_with("http://") {
                break;
            }
            eprintln!("  {line}");
        }
        Ok(child)
    }

    pub(crate) fn serve_docs(&self, port: u16, open: bool) -> Result<()> {
        let address = format!("127.0.0.1:{port}");
        if open {
            self.run(
                "open documentation",
                "xdg-open",
                [format!("http://{address}")],
            )?;
        }
        self.exec(
            "serve documentation",
            "caddy",
            [
                OsStr::new("file-server"),
                OsStr::new("--root"),
                self.root.join("apps/docs/build").as_os_str(),
                OsStr::new("--listen"),
                OsStr::new(&address),
            ],
        )
    }

    fn test_components(&self) -> Result<()> {
        let component = self.buck_output("//:component")?;
        let output = self.command(
            "test nucleus component",
            "wasmtime",
            [
                OsString::from("run"),
                OsString::from("--invoke"),
                OsString::from("smoke()"),
                component.into_os_string(),
            ],
        )?;
        expect_output("nucleus component smoke test", &output, "42")?;

        let cli = self.buck_output("//:cli-component")?;
        let output = self.command("test CLI component", "wasmtime", [cli.as_os_str()])?;
        expect_output(
            "CLI component smoke test",
            &output,
            "hello from nucleus: SQLite returned 42",
        )?;
        eprintln!("• test Wasm components… done");
        Ok(())
    }

    fn buck_output(&self, target: &str) -> Result<PathBuf> {
        self.buck_path(
            "build Buck prerequisite",
            ["build", target, "--show-full-simple-output"],
        )
    }

    fn build_and_materialize_with_args(
        &self,
        phase: &str,
        arguments: &[String],
        destination: &Path,
    ) -> Result<()> {
        let source = self.buck_path(phase, arguments)?;
        replace_dir(&source, destination)?;
        eprintln!("• {phase} done");
        Ok(())
    }

    fn buck_path<I, S>(&self, phase: &str, arguments: I) -> Result<PathBuf>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = self.buck_command(phase, arguments)?;
        let path =
            String::from_utf8(output.stdout).wrap_err("Buck returned a non-UTF-8 output path")?;
        let mut paths = path.lines().filter(|path| !path.is_empty());
        let path = paths
            .next()
            .ok_or_else(|| color_eyre::eyre::eyre!("{phase} produced no output"))?;
        if paths.next().is_some() {
            bail!("{phase} produced more than one output");
        }
        Ok(PathBuf::from(path))
    }

    fn buck_outputs<I, S>(&self, phase: &str, arguments: I) -> Result<BTreeMap<String, PathBuf>>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = self.buck_command(phase, arguments)?;
        serde_json::from_slice(&output.stdout).wrap_err("Buck returned invalid JSON output")
    }

    fn buck_command<I, S>(&self, phase: &str, arguments: I) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = Command::new("buck2")
            .args(arguments)
            .current_dir(&self.root)
            .stderr(Stdio::inherit())
            .output()
            .wrap_err_with(|| format!("{phase}: could not run buck2"))?;
        if !output.status.success() {
            bail!(
                "{phase} failed with {}\n{}",
                output.status,
                String::from_utf8_lossy(&output.stdout)
            );
        }
        Ok(output)
    }
}

fn required_output<'a>(outputs: &'a BTreeMap<String, PathBuf>, target: &str) -> Result<&'a Path> {
    outputs.get(target).map(PathBuf::as_path).ok_or_else(|| {
        color_eyre::eyre::eyre!("Buck did not report an output for required target {target}")
    })
}

fn expect_output(phase: &str, output: &Output, expected: &str) -> Result<()> {
    if output.status.success() && String::from_utf8_lossy(&output.stdout).trim() == expected {
        return Ok(());
    }
    bail!(
        "{phase} failed\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

fn command_path(name: &str) -> Result<PathBuf> {
    let path = env::var_os("PATH").ok_or_else(|| color_eyre::eyre::eyre!("PATH is not set"))?;
    env::split_paths(&path)
        .map(|directory| directory.join(name))
        .find(|candidate| candidate.is_file())
        .ok_or_else(|| color_eyre::eyre::eyre!("could not find {name} on PATH"))
}

fn valid_base_path(path: &str) -> bool {
    path.is_empty()
        || (path.starts_with('/')
            && path[1..].chars().all(|character| {
                character.is_ascii_alphanumeric()
                    || matches!(character, '-' | '.' | '_' | '~' | '/')
            }))
}

fn replace_dir(source: &Path, target: &Path) -> Result<()> {
    if target.exists() {
        fs::remove_dir_all(target)
            .wrap_err_with(|| format!("could not replace {}", target.display()))?;
    }
    copy_dir(source, target)
}

pub(crate) fn copy_dir(source: &Path, target: &Path) -> Result<()> {
    fs::create_dir_all(target)
        .wrap_err_with(|| format!("could not create {}", target.display()))?;
    for entry in
        fs::read_dir(source).wrap_err_with(|| format!("could not read {}", source.display()))?
    {
        let entry = entry.wrap_err("could not read directory entry")?;
        let destination = target.join(entry.file_name());
        if entry
            .file_type()
            .wrap_err("could not inspect directory entry")?
            .is_dir()
        {
            copy_dir(&entry.path(), &destination)?;
        } else {
            fs::copy(entry.path(), &destination).wrap_err_with(|| {
                format!(
                    "could not copy {} to {}",
                    entry.path().display(),
                    destination.display()
                )
            })?;
        }
    }
    Ok(())
}
