use std::{
    cell::Cell,
    collections::BTreeMap,
    env,
    ffi::{OsStr, OsString},
    fs,
    io::{self, BufRead, BufReader, Write},
    path::{Path, PathBuf},
    process::{Child, Command, Output, Stdio},
    time::Instant,
};

use color_eyre::eyre::{Result, WrapErr, bail, eyre};

use crate::{BuildTarget, buck, cargo, loc};

const BUCK_CONFIG_HEADER: &str = "# @generated by `glu buck configure`; do not edit.";

#[derive(Clone, Copy)]
pub(crate) struct DemoOptions {
    pub(crate) port: u16,
    pub(crate) kernel_port: u16,
    pub(crate) sat_port: u16,
    pub(crate) open: bool,
    pub(crate) no_build: bool,
    pub(crate) tls: bool,
}

pub(crate) struct Runner {
    root: PathBuf,
    verbose: u8,
    buck_checked: Cell<bool>,
}

impl Runner {
    pub(crate) const fn new(root: PathBuf, verbose: u8) -> Self {
        Self {
            root,
            verbose,
            buck_checked: Cell::new(false),
        }
    }

    fn command<I, S>(&self, phase: &str, program: &str, args: I) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        self.command_with_env(phase, program, args, &[])
    }

    fn command_with_env<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, &OsStr)],
    ) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let args: Vec<OsString> = args.into_iter().map(|arg| arg.as_ref().into()).collect();
        if self.verbose > 0 {
            eprintln!(
                "  $ {program} {}",
                args.iter()
                    .map(|arg| arg.to_string_lossy())
                    .collect::<Vec<_>>()
                    .join(" ")
            );
        }

        Command::new(program)
            .args(&args)
            .env("CC_wasm32_unknown_unknown", "nucleus-wasm-clang")
            .env("CC_wasm32_wasip1", "wasm32-unknown-wasi-cc")
            .env("CC_wasm32_wasip2", "wasm32-unknown-wasi-cc")
            .envs(environment.iter().copied())
            .current_dir(&self.root)
            .output()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))
    }

    pub(crate) fn run<I, S>(&self, phase: &str, program: &str, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        self.run_with_env(phase, program, args, &[])
    }

    pub(crate) fn run_with_env<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, &OsStr)],
    ) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let started = Instant::now();
        eprint!("• {phase}…");
        let output = self.command_with_env(phase, program, args, environment)?;

        if self.verbose > 1 || !output.status.success() {
            eprintln!();
            print!("{}", String::from_utf8_lossy(&output.stdout));
            eprint!("{}", String::from_utf8_lossy(&output.stderr));
        }
        if !output.status.success() {
            bail!("{phase} failed with {}", output.status);
        }

        eprintln!(" done ({:.2?})", started.elapsed());
        Ok(())
    }

    pub(crate) fn root(&self) -> &Path {
        &self.root
    }

    pub(crate) const fn verbose(&self) -> u8 {
        self.verbose
    }

    fn exec<I, S>(&self, phase: &str, program: &str, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        self.exec_with_env(phase, program, args, &[])
    }

    /// Run a program with this process's streams, so it can be interactive.
    fn exec_with_env<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, &OsStr)],
    ) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let status = Command::new(program)
            .args(args)
            .envs(environment.iter().copied())
            .current_dir(&self.root)
            .status()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))?;
        if !status.success() {
            bail!("{phase} failed with {status}");
        }
        Ok(())
    }

    /// Runs a program to completion with extra environment variables.
    fn exec_with_environment<I, S>(
        &self,
        phase: &str,
        program: &str,
        args: I,
        environment: &[(&str, String)],
    ) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let mut command = Command::new(program);
        command.args(args).current_dir(&self.root);
        for (name, value) in environment {
            command.env(name, value);
        }
        let status = command
            .status()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))?;
        if !status.success() {
            bail!("{phase} failed with {status}");
        }
        Ok(())
    }

    fn cargo(&self, phase: &str, args: &[&str]) -> Result<()> {
        let mut full = vec!["--locked"];
        full.extend_from_slice(args);
        self.run(phase, "cargo", full)
    }

    fn cargo_streaming(&self, phase: &str, args: &[&str]) -> Result<()> {
        let started = Instant::now();
        let mut full = vec!["--locked"];
        full.extend_from_slice(args);
        eprintln!("• {phase}…");
        let status = Command::new("cargo")
            .args(full)
            .current_dir(&self.root)
            .status()
            .wrap_err_with(|| format!("{phase}: could not run cargo"))?;
        if !status.success() {
            bail!("{phase} failed with {status}");
        }
        eprintln!("• {phase} done ({:.2?})", started.elapsed());
        Ok(())
    }

    fn tool_cargo(&self, phase: &str, args: &[&str]) -> Result<()> {
        let (command, rest) = args.split_first().expect("Cargo command is present");
        let mut full = vec![*command];
        if *command != "fmt" {
            full.push("--locked");
        }
        full.extend(["--manifest-path", "tools/glu/Cargo.toml"]);
        full.extend_from_slice(rest);
        self.run(phase, "cargo", full)
    }

    fn pnpm(&self, phase: &str, args: &[&str]) -> Result<()> {
        self.run(phase, "pnpm", args)
    }

    pub(crate) fn fmt(&self, check: bool) -> Result<()> {
        let cargo_args = if check {
            &["fmt", "--all", "--", "--check"][..]
        } else {
            &["fmt", "--all"][..]
        };
        self.cargo("format production", cargo_args)?;
        self.tool_cargo("format glu", cargo_args)?;
        let ruff_args = if check {
            &["format", "--check", "."][..]
        } else {
            &["format", "."][..]
        };
        self.run("format Python", "ruff", ruff_args)?;
        self.pnpm(
            "format web",
            &[
                "exec",
                "prettier",
                if check { "--check" } else { "--write" },
                ".",
            ],
        )
    }

    pub(crate) fn lint(&self) -> Result<()> {
        self.cargo(
            "lint production",
            &[
                "clippy",
                "--workspace",
                "--all-targets",
                "--",
                "-D",
                "warnings",
            ],
        )?;
        self.tool_cargo(
            "lint glu",
            &["clippy", "--all-targets", "--", "-D", "warnings"],
        )?;
        self.build(BuildTarget::Wasm)?;
        self.run("lint Python", "ruff", ["check", "."])?;
        self.pnpm("lint web", &["run", "lint"])
    }

    pub(crate) fn test(&self, container: bool, cargo: bool) -> Result<()> {
        if container && env::var_os("NUCLEUS_DEVCONTAINER").is_none() {
            let root = self.root.to_string_lossy();
            self.run(
                "start dev container",
                "devcontainer",
                ["up", "--workspace-folder", root.as_ref()],
            )?;
            let mut arguments = vec!["exec", "--workspace-folder", root.as_ref(), "glu", "test"];
            if cargo {
                arguments.push("--cargo");
            }
            return self.exec("test in dev container", "devcontainer", arguments);
        }

        if cargo {
            self.cargo_streaming("test Cargo compatibility", &["test", "--workspace"])?;
            self.run_with_env(
                "test JavaScript-hosted Wasm randomness",
                "cargo",
                [
                    "test",
                    "--locked",
                    "-p",
                    "covalence-lib-rand",
                    "--target",
                    "wasm32-unknown-unknown",
                ],
                &[(
                    "CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER",
                    OsStr::new("wasm-bindgen-test-runner"),
                )],
            )?;
        }
        self.exec("test Buck Rust targets", "buck2", ["test", "//crates/..."])?;
        self.build(BuildTarget::Wasm)?;
        self.build(BuildTarget::Component)?;
        self.pnpm("test web", &["run", "test"])?;
        self.test_python()?;
        self.test_components()?;
        let cli = self.buck_output("//crates/bin/nucleus:nucleus")?;
        let cli = cli.to_string_lossy();
        let output = self.command("test nucleus CLI", cli.as_ref(), std::iter::empty::<&str>())?;
        expect_output(
            "nucleus CLI smoke test",
            &output,
            "nucleus: content-addressed SQLite. Store mounted as vfs=cas. (help) for commands.\nnucleus>",
        )?;
        eprintln!("• test nucleus CLI… done");
        Ok(())
    }

    pub(crate) fn build(&self, target: BuildTarget) -> Result<()> {
        match target {
            BuildTarget::All => self.build_all(),
            BuildTarget::Native => {
                self.buck_check()?;
                self.run("build native targets", "buck2", ["build", "//crates/..."])
            }
            BuildTarget::Wasm => {
                self.buck_check()?;
                let source = self.buck_output("//:wasm")?;
                self.materialize_wasm(&source)?;
                eprintln!("• build Wasm package… done");
                Ok(())
            }
            BuildTarget::Python => {
                self.python_package()?;
                eprintln!("• build Python package… done");
                Ok(())
            }
            BuildTarget::Component => {
                self.buck_check()?;
                let source = self.buck_output("//:component-js")?;
                self.materialize_component_js(&source)?;
                eprintln!("• build transpiled component… done");
                Ok(())
            }
            BuildTarget::Docs => self.docs(),
        }
    }

    fn build_all(&self) -> Result<()> {
        self.buck_check()?;
        let mut arguments = vec![
            "build".to_owned(),
            "//crates/...".to_owned(),
            "//:wasm".to_owned(),
            "//:component-js".to_owned(),
            "//:python".to_owned(),
            "//:docs".to_owned(),
        ];
        arguments.extend(self.docs_config()?);
        arguments.push("--show-full-json-output".to_owned());
        let outputs = self.buck_outputs("build all targets", &arguments)?;
        self.materialize_wasm(required_output(&outputs, "nucleus//:wasm")?)?;
        self.materialize_component_js(required_output(&outputs, "nucleus//:component-js")?)?;
        replace_dir(
            required_output(&outputs, "nucleus//:python")?,
            &self.python_root(),
        )?;
        replace_dir(
            required_output(&outputs, "nucleus//:docs")?,
            &self.root.join("apps/docs/build"),
        )?;
        eprintln!("• build all targets… done");
        Ok(())
    }

    fn materialize_wasm(&self, source: &Path) -> Result<()> {
        replace_dir(
            &source.join("generated"),
            &self.root.join("packages/nucleus/generated"),
        )?;
        replace_dir(
            &source.join("dist"),
            &self.root.join("packages/nucleus/dist"),
        )
    }

    /// Stage the transpiled component beside the `wasm-bindgen` output.
    ///
    /// Its own directory rather than a subdirectory of `generated`, because the
    /// two are produced by independent Buck targets and `materialize_wasm`
    /// replaces `generated` wholesale.
    fn materialize_component_js(&self, source: &Path) -> Result<()> {
        replace_dir(source, &self.root.join("packages/nucleus/component"))
    }

    /// Where the importable `covalence` package is staged.
    ///
    /// Outside the source tree deliberately. Dropping a built `.so` into
    /// `crates/ffi/python/python/covalence` would put a build output inside a
    /// directory Buck globs as a source.
    fn python_root(&self) -> PathBuf {
        self.root().join("target/python")
    }

    /// Build the Python package and return the directory to import it from.
    fn python_package(&self) -> Result<PathBuf> {
        let source = self.buck_output("//:python")?;
        let root = self.python_root();
        replace_dir(&source, &root)?;
        Ok(root)
    }

    /// Run the interpreter with the Covalence package importable.
    ///
    /// `glu python` on its own is a REPL that can `import covalence`; anything
    /// after it is passed through, so `glu python -c …` and `glu python
    /// script.py` work as expected.
    ///
    /// This runs whichever `python3` is on `PATH` rather than a fixed one, so
    /// that an activated virtual environment — the way to reach a package
    /// nixpkgs does not carry — layers on top of the pinned interpreter
    /// without any further configuration.
    pub(crate) fn python<I, S>(&self, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let root = self.python_package()?;
        self.exec_with_env(
            "run Python",
            "python3",
            args,
            &[("PYTHONPATH", root.as_os_str())],
        )
    }

    fn test_python(&self) -> Result<()> {
        let root = self.python_package()?;
        // `python3 -m pytest` rather than the `pytest` script, so the tests run
        // under the same interpreter the extension was staged for.
        self.run_with_env(
            "test Python package",
            "python3",
            // `no:cacheprovider` because the run is disposable and the cache
            // would otherwise land in the source tree.
            [
                "-m",
                "pytest",
                "crates/ffi/python/tests",
                "-q",
                "-p",
                "no:cacheprovider",
            ],
            &[("PYTHONPATH", root.as_os_str())],
        )
    }

    pub(crate) fn check(&self) -> Result<()> {
        self.fmt(true)?;
        self.lint()?;
        self.deps_check()?;
        self.loc()?;
        self.test(false, true)?;
        self.build(BuildTarget::All)
    }

    pub(crate) fn ci(&self) -> Result<()> {
        self.check()
    }

    pub(crate) fn deps_check(&self) -> Result<()> {
        let summary = cargo::check(&self.root)?;
        eprintln!(
            "dependencies: {} workspace packages, {} external packages, {} edges",
            summary.workspace_packages, summary.external_packages, summary.edges
        );
        Ok(())
    }

    /// Build every Lean development under `lean/`.
    ///
    /// Deliberately outside `build`, `check`, and `ci`: the Lean sources are a
    /// specification of what the kernel implements, not an input to anything
    /// that gets built, and they carry a Mathlib dependency nothing else
    /// needs. For the same reason this shells out to `lake` instead of going
    /// through Buck.
    ///
    /// `lake build` rather than a bare elaboration, because building is what
    /// reports errors and `sorry` warnings across a whole library.
    pub(crate) fn lean(&self, list: bool, cache: bool, jobs: Option<u16>) -> Result<()> {
        let projects = lean_projects(&self.root.join("lean"))?;
        if projects.is_empty() {
            eprintln!("no Lean developments found under lean/");
            return Ok(());
        }

        for project in &projects {
            let name = project
                .strip_prefix(&self.root)
                .unwrap_or(project)
                .display()
                .to_string();
            if list {
                println!("{name}");
                continue;
            }

            // Mathlib publishes prebuilt artifacts for every revision. Without
            // them `lake build` compiles all of Mathlib from source, which is
            // hours rather than minutes, so this is not really optional on a
            // cold checkout. `cache get` is cheap once the store is populated.
            if cache && requires_mathlib(project)? {
                self.run_in(
                    &format!("fetch Mathlib cache for {name}"),
                    project,
                    "lake",
                    ["exe", "cache", "get"],
                    &[],
                )?;
            }
            self.run_in(
                &format!("build {name}"),
                project,
                "lake",
                ["build"],
                &lake_jobs_env(jobs),
            )?;
        }
        Ok(())
    }

    /// Generate API documentation for every Lean development that has a
    /// `docbuild` companion project.
    ///
    /// Each development is staged into `out/<name>/`: doc-gen4's HTML tree,
    /// plus its `SQLite` database, which lands beside the tree rather than
    /// inside it and so has to be collected explicitly. The database is worth
    /// publishing on its own — upstream does not deploy one, so there is no
    /// hosted Mathlib equivalent to point tooling at.
    ///
    /// `docbuild` is doc-gen4's documented pattern: a nested project that
    /// depends on both the library and the generator, keeping the generator
    /// out of the library's own dependency set.
    pub(crate) fn lean_docs(&self, out: &Path, cache: bool, jobs: Option<u16>) -> Result<()> {
        let out = if out.is_absolute() {
            out.to_path_buf()
        } else {
            self.root.join(out)
        };
        if out.exists() {
            fs::remove_dir_all(&out)
                .wrap_err_with(|| format!("could not clear {}", out.display()))?;
        }

        let mut generated = 0;
        for project in lean_projects(&self.root.join("lean"))? {
            let docbuild = project.join("docbuild");
            if !docbuild.join("lakefile.toml").is_file() {
                continue;
            }
            let name = project
                .file_name()
                .map(|name| name.to_string_lossy().into_owned())
                .ok_or_else(|| color_eyre::eyre::eyre!("Lean development has no name"))?;
            let label = project
                .strip_prefix(&self.root)
                .unwrap_or(&project)
                .display()
                .to_string();

            if cache && requires_mathlib(&project)? {
                self.run_in(
                    &format!("fetch Mathlib cache for {label}"),
                    &project,
                    "lake",
                    ["exe", "cache", "get"],
                    &[],
                )?;
            }
            // Materialise the documentation dependencies before patching one
            // of them. `lake build` clones what the manifest names as part of
            // resolution, which would land after the patch and silently undo
            // it; loading the workspace resolves at the pinned revisions
            // without rewriting the manifest.
            self.run_in(
                &format!("resolve documentation dependencies for {label}"),
                &docbuild,
                "lake",
                ["env", "true"],
                &[],
            )?;
            unguard_unicode_extern_lib(&project)?;
            self.run_in(
                &format!("document {label}"),
                &docbuild,
                "lake",
                ["build", &format!("{name}:docs")],
                &lake_jobs_env(jobs),
            )?;

            let build = docbuild.join(".lake/build");
            let staged = out.join(&name);
            copy_dir(&build.join("doc"), &staged)?;
            fs::copy(build.join("api-docs.db"), staged.join("api-docs.db"))
                .wrap_err("could not publish the doc-gen4 database")?;
            generated += 1;
        }

        if generated == 0 {
            eprintln!("no Lean development under lean/ has a docbuild project");
        }
        Ok(())
    }

    fn run_in<I, S>(
        &self,
        phase: &str,
        directory: &Path,
        program: &str,
        args: I,
        environment: &[(&str, OsString)],
    ) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let args: Vec<OsString> = args.into_iter().map(|arg| arg.as_ref().into()).collect();
        if self.verbose > 0 {
            eprintln!(
                "  $ (cd {} && {program} {})",
                directory.display(),
                args.iter()
                    .map(|arg| arg.to_string_lossy())
                    .collect::<Vec<_>>()
                    .join(" ")
            );
        }

        let started = Instant::now();
        eprint!("• {phase}…");
        let output = Command::new(program)
            .args(&args)
            .envs(environment.iter().map(|(key, value)| (*key, value)))
            .current_dir(directory)
            .output()
            .wrap_err_with(|| format!("{phase}: could not run {program}"))?;

        if self.verbose > 1 || !output.status.success() {
            eprintln!();
            print!("{}", String::from_utf8_lossy(&output.stdout));
            eprint!("{}", String::from_utf8_lossy(&output.stderr));
        }
        if !output.status.success() {
            bail!("{phase} failed with {}", output.status);
        }

        eprintln!(" done ({:.2?})", started.elapsed());
        Ok(())
    }

    pub(crate) fn loc(&self) -> Result<()> {
        println!("{}", loc::count(&self.root, self.verbose > 0)?);
        io::stdout()
            .flush()
            .wrap_err("could not flush LoC report")?;
        Ok(())
    }

    pub(crate) fn status(&self) -> Result<()> {
        println!("{}", loc::count(&self.root, self.verbose > 0)?.headline());
        io::stdout()
            .flush()
            .wrap_err("could not flush status report")?;
        Ok(())
    }

    pub(crate) fn buck_sync(&self) -> Result<()> {
        let changed = buck::sync(&self.root)?;
        self.buck_checked.set(false);
        if changed == 0 {
            eprintln!("Buck files are up to date");
        } else {
            eprintln!("updated {changed} generated Buck file(s)");
        }
        Ok(())
    }

    pub(crate) fn buck_check(&self) -> Result<()> {
        if !self.buck_checked.get() {
            buck::check(&self.root)?;
            self.buck_checked.set(true);
        }
        Ok(())
    }

    pub(crate) fn buck_configure(&self) -> Result<()> {
        self.write_buck_configuration()?;
        eprintln!("configured Buck tool paths");
        Ok(())
    }

    fn write_buck_configuration(&self) -> Result<()> {
        let path = self.root.join(".buckconfig.local");
        let configuration = Self::buck_configuration()?;
        if path.exists() {
            let current = fs::read_to_string(&path).wrap_err("could not read .buckconfig.local")?;
            let generated = matches!(
                current.lines().next(),
                Some(BUCK_CONFIG_HEADER | "# Generated by `glu buck configure`.")
            );
            if current != configuration && !generated {
                bail!(
                    "{} already exists and was not generated by glu",
                    path.display()
                );
            }
        }
        fs::write(&path, configuration)
            .wrap_err_with(|| format!("could not write {}", path.display()))
    }

    fn buck_configuration() -> Result<String> {
        let ar = command_path("ar")?;
        let cc = command_path("clang")?;
        let cxx = command_path("clang++")?;
        Ok(format!(
            "{BUCK_CONFIG_HEADER}\n\
             [nucleus]\n\
               ar = {}\n\
               cc = {}\n\
               cxx = {}\n",
            ar.display(),
            cc.display(),
            cxx.display(),
        ))
    }

    pub(crate) fn doctor(&self) -> Result<()> {
        for tool in [
            "buck2",
            "caddy",
            "cargo",
            "chromium",
            "devcontainer",
            "rustc",
            "node",
            "pnpm",
            "pytest",
            "python3",
            "maturin",
            "ruff",
            "scc",
            "git",
            "wasm-bindgen",
            "wasm-tools",
            "wasmtime",
        ] {
            self.run(tool, tool, ["--version"])?;
        }
        self.run("cargo component", "cargo", ["component", "--version"])?;
        // jco comes from the pnpm workspace rather than the Nix shell, so it
        // is only reachable once `pnpm install` has run.
        self.pnpm(
            "jco",
            &["--filter", "@nucleus/nucleus", "exec", "jco", "--version"],
        )
    }

    pub(crate) fn docs(&self) -> Result<()> {
        self.buck_check()?;
        let mut arguments = vec!["build".to_owned(), "//:docs".to_owned()];
        arguments.extend(self.docs_config()?);
        arguments.push("--show-full-simple-output".to_owned());
        self.build_and_materialize_with_args(
            "build documentation site",
            &arguments,
            &self.root.join("apps/docs/build"),
        )
    }

    fn docs_config(&self) -> Result<Vec<String>> {
        let mut arguments = Vec::new();
        if let Ok(base_path) = env::var("BASE_PATH") {
            if !valid_base_path(&base_path) {
                bail!("BASE_PATH must be empty or a slash followed by a URL-safe path");
            }
            arguments.extend(["--config".to_owned(), format!("docs.base_path={base_path}")]);
        }
        let commit = self
            .command("read source commit", "git", ["rev-parse", "HEAD"])?
            .stdout;
        let commit = String::from_utf8(commit)
            .unwrap_or_else(|_| "unknown".to_owned())
            .trim()
            .to_owned();
        let commit = if commit.len() == 40
            && commit
                .chars()
                .all(|character| character.is_ascii_hexdigit())
        {
            commit
        } else {
            "unknown".to_owned()
        };
        let status = self.command("read source status", "git", ["status", "--porcelain"])?;
        let dirty = !status.status.success() || !status.stdout.is_empty();
        arguments.extend([
            "--config".to_owned(),
            format!("docs.commit={commit}"),
            "--config".to_owned(),
            format!("docs.dirty={dirty}"),
        ]);
        Ok(arguments)
    }

    /// Builds and serves the browser demo with an HTTP kernel.
    ///
    /// # Errors
    ///
    /// Returns an error if the build fails, no database can be served, or a
    /// service cannot start.
    pub(crate) fn demo(&self, files: &[PathBuf], options: DemoOptions) -> Result<()> {
        let DemoOptions {
            port,
            kernel_port,
            sat_port,
            open,
            no_build,
            tls,
        } = options;

        // Default to the committed fixture.
        let default = self.root.join("packages/nucleus/test/fixture.sqlite");
        let files: Vec<PathBuf> = if files.is_empty() {
            vec![default]
        } else {
            files.to_vec()
        };
        for file in &files {
            if !file.is_file() {
                bail!("{} is not a file", file.display());
            }
        }

        if !no_build {
            self.pnpm(
                "build browser demo",
                &["--dir", "packages/nucleus", "build"],
            )?;
            self.cargo(
                "build demo kernel",
                &["build", "-p", "covalence-bin-cas-serve"],
            )?;
        }

        let mut kernel = self.start_kernel(&files, kernel_port)?;
        let scheme = if tls { "https" } else { "http" };
        let host = if tls { "localhost" } else { "127.0.0.1" };
        let page = format!("{scheme}://{host}:{port}/");
        let mut sat = match self.start_sat_provider(sat_port) {
            Ok(sat) => sat,
            Err(error) => {
                let _ = kernel.kill();
                let _ = kernel.wait();
                return Err(error);
            }
        };

        eprintln!();
        eprintln!("  demo      {page}");
        eprintln!("  kernel    http://127.0.0.1:{kernel_port}");
        eprintln!("  SAT       http://127.0.0.1:{sat_port}");
        eprintln!();
        eprintln!("  The page is a REPL. Try:");
        eprintln!("    (help)");
        eprintln!("    (connect \"http://127.0.0.1:{kernel_port}\")");
        eprintln!("    (fetch ADDRESS)         (an address printed above)");
        eprintln!("    (sqlite ADDRESS \"-batch\" \".schema\")");
        eprintln!("    (sat-select full-adder-unsat)");
        eprintln!("    (sat-solve)");
        eprintln!();
        eprintln!("  Ctrl-C stops the page, kernel, and SAT provider.");
        eprintln!();

        if open {
            // The printed URL remains usable if opening fails.
            let _ = self.run("open demo", "xdg-open", [page.as_str()]);
        }

        let (config, environment) = self.demo_config(port, sat_port, tls);
        let served = self.exec_with_environment(
            "serve demo",
            "caddy",
            [
                OsStr::new("run"),
                OsStr::new("--adapter"),
                OsStr::new("caddyfile"),
                OsStr::new("--config"),
                config.as_os_str(),
            ],
            &environment,
        );

        // Do not leave the kernel running.
        let _ = kernel.kill();
        let _ = kernel.wait();
        let _ = sat.kill();
        let _ = sat.wait();
        served
    }

    /// Returns the tested demo server configuration and environment.
    fn demo_config(
        &self,
        port: u16,
        sat_port: u16,
        tls: bool,
    ) -> (PathBuf, Vec<(&'static str, String)>) {
        // Trusting Caddy's internal CA remains an explicit user action.
        let (address, tls_directive) = if tls {
            (format!("https://localhost:{port}"), "tls internal")
        } else {
            (format!("http://127.0.0.1:{port}"), "")
        };
        let package = self.root.join("packages/nucleus");
        (
            package.join("demo.caddyfile"),
            vec![
                ("NUCLEUS_ADDRESS", address),
                ("NUCLEUS_SAT", format!("127.0.0.1:{sat_port}")),
                ("NUCLEUS_ROOT", package.display().to_string()),
                (
                    "NUCLEUS_SAMPLES",
                    self.root.join("crates/repl/samples").display().to_string(),
                ),
                ("NUCLEUS_TLS", tls_directive.to_owned()),
            ],
        )
    }

    /// Starts the HTTP kernel and collects its admitted addresses.
    fn start_kernel(&self, files: &[PathBuf], port: u16) -> Result<Child> {
        let binary = self.root.join("target/debug/covalence-cas-serve");
        let mut child = Command::new(&binary)
            .arg("--port")
            .arg(port.to_string())
            .args(files)
            .current_dir(&self.root)
            .stdout(Stdio::piped())
            .spawn()
            .wrap_err_with(|| format!("could not start {}", binary.display()))?;

        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| eyre!("demo kernel produced no output"))?;
        let mut reader = BufReader::new(stdout);
        let mut line = String::new();
        loop {
            line.clear();
            if reader.read_line(&mut line)? == 0 {
                let _ = child.kill();
                bail!("demo kernel exited before it started listening");
            }
            let line = line.trim_end();
            if line.starts_with("http://") {
                break;
            }
            eprintln!("  {line}");
        }
        Ok(child)
    }

    /// Starts the ordinary HTTP adapter around the untrusted `CaDiCaL` process.
    fn start_sat_provider(&self, port: u16) -> Result<Child> {
        let script = self.root.join("packages/nucleus/dist/demo-sat.js");
        let mut child = Command::new("node")
            .arg(&script)
            .arg(port.to_string())
            .current_dir(&self.root)
            .stdout(Stdio::piped())
            .spawn()
            .wrap_err_with(|| format!("could not start {}", script.display()))?;

        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| eyre!("SAT provider produced no output"))?;
        let mut reader = BufReader::new(stdout);
        let mut line = String::new();
        if reader.read_line(&mut line)? == 0 || !line.starts_with("http://") {
            let _ = child.kill();
            let _ = child.wait();
            bail!("SAT provider exited before it started listening");
        }
        Ok(child)
    }

    pub(crate) fn serve_docs(&self, port: u16, open: bool) -> Result<()> {
        let address = format!("127.0.0.1:{port}");
        if open {
            self.run(
                "open documentation",
                "xdg-open",
                [format!("http://{address}")],
            )?;
        }
        self.exec(
            "serve documentation",
            "caddy",
            [
                OsStr::new("file-server"),
                OsStr::new("--root"),
                self.root.join("apps/docs/build").as_os_str(),
                OsStr::new("--listen"),
                OsStr::new(&address),
            ],
        )
    }

    fn test_components(&self) -> Result<()> {
        let component = self.buck_output("//:component")?;
        let output = self.command(
            "test nucleus component",
            "wasmtime",
            [
                OsString::from("run"),
                OsString::from("--invoke"),
                OsString::from("smoke()"),
                component.into_os_string(),
            ],
        )?;
        expect_output("nucleus component smoke test", &output, "42")?;

        // EOF after startup checks component initialization and mounting.
        let cli = self.buck_output("//:cli-component")?;
        let output = self.command("test CLI component", "wasmtime", [cli.as_os_str()])?;
        expect_output(
            "CLI component smoke test",
            &output,
            "nucleus: content-addressed SQLite. Store mounted as vfs=cas. (help) for commands.\nnucleus>",
        )?;
        eprintln!("• test Wasm components… done");
        Ok(())
    }

    fn buck_output(&self, target: &str) -> Result<PathBuf> {
        self.buck_path(
            "build Buck prerequisite",
            ["build", target, "--show-full-simple-output"],
        )
    }

    fn build_and_materialize_with_args(
        &self,
        phase: &str,
        arguments: &[String],
        destination: &Path,
    ) -> Result<()> {
        let source = self.buck_path(phase, arguments)?;
        replace_dir(&source, destination)?;
        eprintln!("• {phase} done");
        Ok(())
    }

    fn buck_path<I, S>(&self, phase: &str, arguments: I) -> Result<PathBuf>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = self.buck_command(phase, arguments)?;
        let path =
            String::from_utf8(output.stdout).wrap_err("Buck returned a non-UTF-8 output path")?;
        let mut paths = path.lines().filter(|path| !path.is_empty());
        let path = paths
            .next()
            .ok_or_else(|| color_eyre::eyre::eyre!("{phase} produced no output"))?;
        if paths.next().is_some() {
            bail!("{phase} produced more than one output");
        }
        Ok(PathBuf::from(path))
    }

    fn buck_outputs<I, S>(&self, phase: &str, arguments: I) -> Result<BTreeMap<String, PathBuf>>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = self.buck_command(phase, arguments)?;
        serde_json::from_slice(&output.stdout).wrap_err("Buck returned invalid JSON output")
    }

    fn buck_command<I, S>(&self, phase: &str, arguments: I) -> Result<Output>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = Command::new("buck2")
            .args(arguments)
            .current_dir(&self.root)
            .stderr(Stdio::inherit())
            .output()
            .wrap_err_with(|| format!("{phase}: could not run buck2"))?;
        if !output.status.success() {
            bail!(
                "{phase} failed with {}\n{}",
                output.status,
                String::from_utf8_lossy(&output.stdout)
            );
        }
        Ok(output)
    }
}

fn required_output<'a>(outputs: &'a BTreeMap<String, PathBuf>, target: &str) -> Result<&'a Path> {
    outputs.get(target).map(PathBuf::as_path).ok_or_else(|| {
        color_eyre::eyre::eyre!("Buck did not report an output for required target {target}")
    })
}

fn expect_output(phase: &str, output: &Output, expected: &str) -> Result<()> {
    if output.status.success() && String::from_utf8_lossy(&output.stdout).trim() == expected {
        return Ok(());
    }
    bail!(
        "{phase} failed\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

/// Directories at or below `directory` that hold a lakefile.
///
/// A lakefile marks the root of a development, so the walk stops descending
/// once it finds one: nested lakefiles belong to fetched dependencies, not to
/// this repository.
fn lean_projects(directory: &Path) -> Result<Vec<PathBuf>> {
    let mut found = Vec::new();
    collect_lean_projects(directory, &mut found)?;
    found.sort();
    Ok(found)
}

/// Environment capping Lake's build parallelism.
///
/// Lake has no parallelism flag; it schedules on Lean's task pool, so the pool
/// size is the knob.
fn lake_jobs_env(jobs: Option<u16>) -> Vec<(&'static str, OsString)> {
    jobs.map(|jobs| ("LEAN_NUM_THREADS", jobs.to_string().into()))
        .into_iter()
        .collect()
}

/// Drop the Windows guard on `UnicodeBasic`'s `extern_lib` declaration.
///
/// doc-gen4 depends on `UnicodeBasic`, whose native helpers are attached to the
/// library with `moreLinkObjs`. Lake does not link those into *precompiled
/// module dynlibs* — only an `extern_lib` reaches those — and `UnicodeBasic`
/// declares its `extern_lib` behind `meta if System.Platform.isWindows`,
/// commented "temporary fix for Windows". So on Linux the static library is
/// built correctly but never linked in, and loading the precompiled module
/// fails with `undefined symbol: unicode_script_to_abbrev`.
///
/// Removing the guard fixes it. Idempotent, and a silent no-op once upstream
/// drops the guard itself or the package stops being a dependency. The stale
/// dynlibs are deleted so they relink against the extern library.
fn unguard_unicode_extern_lib(project: &Path) -> Result<()> {
    let package = project.join(".lake/packages/UnicodeBasic");
    let lakefile = package.join("lakefile.lean");
    if !lakefile.is_file() {
        return Ok(());
    }

    let contents = fs::read_to_string(&lakefile)
        .wrap_err_with(|| format!("could not read {}", lakefile.display()))?;
    let guard = "meta if System.Platform.isWindows then\nextern_lib libunicodeclib";
    if !contents.contains(guard) {
        return Ok(());
    }

    fs::write(
        &lakefile,
        contents.replace(guard, "extern_lib libunicodeclib"),
    )
    .wrap_err_with(|| format!("could not patch {}", lakefile.display()))?;

    let libraries = package.join(".lake/build/lib/lean");
    if libraries.is_dir() {
        for entry in fs::read_dir(&libraries)
            .wrap_err_with(|| format!("could not read {}", libraries.display()))?
        {
            let path = entry
                .wrap_err_with(|| format!("could not read {}", libraries.display()))?
                .path();
            if path.extension().is_some_and(|extension| extension == "so") {
                fs::remove_file(&path)
                    .wrap_err_with(|| format!("could not remove {}", path.display()))?;
            }
        }
    }
    Ok(())
}

/// Whether a development depends on Mathlib, and so has a prebuilt cache to
/// fetch. `lake exe cache` is a Mathlib executable, so asking for it in a
/// development that does not require Mathlib is an error rather than a no-op.
fn requires_mathlib(project: &Path) -> Result<bool> {
    for lakefile in ["lakefile.toml", "lakefile.lean"] {
        let path = project.join(lakefile);
        if path.is_file() {
            let contents = fs::read_to_string(&path)
                .wrap_err_with(|| format!("could not read {}", path.display()))?;
            return Ok(contents.contains("mathlib"));
        }
    }
    Ok(false)
}

fn collect_lean_projects(directory: &Path, found: &mut Vec<PathBuf>) -> Result<()> {
    if !directory.is_dir() {
        return Ok(());
    }

    let mut subdirectories = Vec::new();
    for entry in fs::read_dir(directory)
        .wrap_err_with(|| format!("could not read {}", directory.display()))?
    {
        let entry = entry.wrap_err_with(|| format!("could not read {}", directory.display()))?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let file_type = entry
            .file_type()
            .wrap_err_with(|| format!("could not stat {}", entry.path().display()))?;

        if file_type.is_file() && matches!(&*name, "lakefile.toml" | "lakefile.lean") {
            found.push(directory.to_path_buf());
            return Ok(());
        }
        if file_type.is_dir() && !name.starts_with('.') {
            subdirectories.push(entry.path());
        }
    }

    for subdirectory in subdirectories {
        collect_lean_projects(&subdirectory, found)?;
    }
    Ok(())
}

fn command_path(name: &str) -> Result<PathBuf> {
    let path = env::var_os("PATH").ok_or_else(|| color_eyre::eyre::eyre!("PATH is not set"))?;
    env::split_paths(&path)
        .map(|directory| directory.join(name))
        .find(|candidate| candidate.is_file())
        .ok_or_else(|| color_eyre::eyre::eyre!("could not find {name} on PATH"))
}

fn valid_base_path(path: &str) -> bool {
    path.is_empty()
        || (path.starts_with('/')
            && path[1..].chars().all(|character| {
                character.is_ascii_alphanumeric()
                    || matches!(character, '-' | '.' | '_' | '~' | '/')
            }))
}

fn replace_dir(source: &Path, target: &Path) -> Result<()> {
    if target.exists() {
        fs::remove_dir_all(target)
            .wrap_err_with(|| format!("could not replace {}", target.display()))?;
    }
    copy_dir(source, target)
}

pub(crate) fn copy_dir(source: &Path, target: &Path) -> Result<()> {
    fs::create_dir_all(target)
        .wrap_err_with(|| format!("could not create {}", target.display()))?;
    for entry in
        fs::read_dir(source).wrap_err_with(|| format!("could not read {}", source.display()))?
    {
        let entry = entry.wrap_err("could not read directory entry")?;
        let destination = target.join(entry.file_name());
        if entry
            .file_type()
            .wrap_err("could not inspect directory entry")?
            .is_dir()
        {
            copy_dir(&entry.path(), &destination)?;
        } else {
            fs::copy(entry.path(), &destination).wrap_err_with(|| {
                format!(
                    "could not copy {} to {}",
                    entry.path().display(),
                    destination.display()
                )
            })?;
        }
    }
    Ok(())
}
