[package]
name = "covalence-data-cbor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Immutable CBOR data model for Nucleus"
publish = false

[dependencies]
covalence-data-num = { path = "../num" }
covalence-lib-cbor = { path = "../../lib/cbor", default-features = false, features = ["drisl"] }
covalence-lib-error = { path = "../../lib/error" }
covalence-lib-hash = { path = "../../lib/hash", default-features = false, features = ["blake3", "sha256"] }
covalence-lib-json = { path = "../../lib/json" }

[lints]
workspace = true
