import Nucleus.Classical.Tagged.Runtime.Allocator

/-!
# Canonical encoder for the tagged runtime

The canonical encoder lays live blocks densely in preorder beginning at word
four.  Every block uses the least power-of-two size class with room for its
one-word live header, all children, and a terminator.  Fresh canonical output
has no free blocks.

`pack?` validates the generated bytes with the ordinary runtime decoder before
returning the checked wrapper.  The raw builder remains public as the precise
normal-form definition and as the target for the completeness proof.
-/

namespace Nucleus.Classical.Tagged.Runtime.Encode

open Nucleus.Classical.Packed
open Nucleus.Classical.Tagged.Runtime
open Nucleus.Classical.Tagged.Runtime.Allocator

variable {payloadWidth : Nat}

/-- Bounded search for a size class whose capacity is strictly larger than
`needed`. -/
def sizeClassSearch (needed : Nat) : Nat → Nat → Nat
  | 0, candidate => candidate
  | fuel + 1, candidate =>
      if needed < 4 * 2 ^ candidate then candidate
      else sizeClassSearch needed fuel (candidate + 1)

/-- The first size class with room for a live header, `children` references,
and the mandatory terminator. -/
def leastSizeClass (children : Nat) : Nat :=
  sizeClassSearch (children + 1) (children + 2) 0

theorem sizeClassSearch_room {needed fuel candidate : Nat}
    (eventual : needed < 4 * 2 ^ (candidate + fuel)) :
    needed < 4 * 2 ^ sizeClassSearch needed fuel candidate := by
  induction fuel generalizing candidate with
  | zero => simpa [sizeClassSearch] using eventual
  | succ fuel ih =>
      unfold sizeClassSearch
      split
      · assumption
      · apply ih
        rw [show candidate + 1 + fuel = candidate + (fuel + 1) by omega]
        exact eventual

/-- The selected block always has room for the header, children, and
terminator. -/
theorem leastSizeClass_room (children : Nat) :
    children + 1 < 4 * 2 ^ leastSizeClass children := by
  apply sizeClassSearch_room
  have smaller : children + 1 < 2 ^ (children + 1) :=
    Nat.lt_two_pow_self
  have positive : 0 < 2 ^ children := Nat.two_pow_pos children
  simp only [Nat.zero_add, Nat.pow_succ]
  omega

/-! ## Public resource bound -/

mutual
  /-- Exact number of arena words occupied by one formula in canonical form.
Literals are stored directly in their parent reference slot. -/
  def formulaWords : Tagged.Formula Nat → Nat
    | .literal _ => 0
    | .and _ children | .or _ children | .sat _ children =>
        4 * 2 ^ leastSizeClass children.length + formulasWords children

  /-- Exact words occupied by a consecutive formula list. -/
  def formulasWords : List (Tagged.Formula Nat) → Nat
    | [] => 0
    | formula :: formulas => formulaWords formula + formulasWords formulas
end

mutual
  theorem formulaWords_aligned : ∀ formula : Tagged.Formula Nat,
      formulaWords formula % 4 = 0
    | .literal _ => by simp [formulaWords]
    | .and _ children | .or _ children | .sat _ children => by
        rw [formulaWords, Nat.add_mod, formulasWords_aligned children]
        simp

  theorem formulasWords_aligned : ∀ formulas : List (Tagged.Formula Nat),
      formulasWords formulas % 4 = 0
    | [] => by simp [formulasWords]
    | formula :: formulas => by
        rw [formulasWords, Nat.add_mod, formulaWords_aligned formula,
          formulasWords_aligned formulas]
end

mutual
  /-- Explicit sufficient conditions for encoding one formula at `base`.
Unlike `pack?`, this predicate does not call the encoder or decoder. -/
  def FitsFormula (payloadWidth base : Nat) : Tagged.Formula Nat → Prop
    | .literal value => 4 * value.atom + 3 < 2 ^ payloadWidth
    | .and _ children | .or _ children | .sat _ children =>
        let block : Block := ⟨base, leastSizeClass children.length⟩
        block.Aligned ∧
        block.stop ≤ 2 ^ payloadWidth ∧
        block.sizeClass + 2 ≤ payloadWidth ∧
        FitsFormulas payloadWidth block.stop children

  /-- Explicit bounds for a consecutive formula list. -/
def FitsFormulas (payloadWidth base : Nat) :
      List (Tagged.Formula Nat) → Prop
    | [] => True
    | formula :: formulas =>
        FitsFormula payloadWidth base formula ∧
        FitsFormulas payloadWidth (base + formulaWords formula) formulas
end

/-- Exact words occupied by one canonical sequent. -/
def sequentWords (sequent : Tagged.Sequent Nat) : Nat :=
  formulaWords sequent.premise + formulaWords sequent.conclusion

/-- Exact words occupied by a canonical sequent table, excluding the reserved
four-word prefix. -/
def tableWords : List (Tagged.Sequent Nat) → Nat
  | [] => 0
  | sequent :: sequents => sequentWords sequent + tableWords sequents

/-- Explicit bounds for a complete sequent table. -/
def FitsSequents (payloadWidth : Nat) : Nat → List (Tagged.Sequent Nat) → Prop
  | _, [] => True
  | base, sequent :: sequents =>
      FitsFormula payloadWidth base sequent.premise ∧
      FitsFormula payloadWidth (base + formulaWords sequent.premise)
        sequent.conclusion ∧
      FitsSequents payloadWidth
        (base + formulaWords sequent.premise + formulaWords sequent.conclusion)
        sequents

/-- Public, non-circular condition under which the canonical packer is
required to succeed.  The prefix bound matters for the empty arena. -/
def Fits (payloadWidth : Nat) (input : List (Tagged.Sequent Nat)) : Prop :=
  4 ≤ 2 ^ payloadWidth ∧ FitsSequents payloadWidth 4 input

mutual
  /-- A fitting formula cannot extend beyond the fixed-width address space. -/
  theorem FitsFormula.end_le {payloadWidth base : Nat}
      {formula : Tagged.Formula Nat}
      (baseBound : base ≤ 2 ^ payloadWidth)
      (fits : FitsFormula payloadWidth base formula) :
      base + formulaWords formula ≤ 2 ^ payloadWidth := by
    cases formula with
    | literal value => simpa [formulaWords] using baseBound
    | and negative children | or negative children | sat negative children =>
        let block : Block := ⟨base, leastSizeClass children.length⟩
        change block.Aligned ∧ block.stop ≤ 2 ^ payloadWidth ∧
          block.sizeClass + 2 ≤ payloadWidth ∧
          FitsFormulas payloadWidth block.stop children at fits
        have childrenEnd := FitsFormulas.end_le fits.2.1 fits.2.2.2
        simpa [formulaWords, block, Block.stop, Block.capacity,
          Nat.add_assoc] using childrenEnd

  /-- A fitting consecutive formula list stays inside the address space. -/
  theorem FitsFormulas.end_le {payloadWidth base : Nat}
      {formulas : List (Tagged.Formula Nat)}
      (baseBound : base ≤ 2 ^ payloadWidth)
      (fits : FitsFormulas payloadWidth base formulas) :
      base + formulasWords formulas ≤ 2 ^ payloadWidth := by
    cases formulas with
    | nil => simpa [formulasWords] using baseBound
    | cons formula formulas =>
        have headEnd := FitsFormula.end_le baseBound fits.1
        have tailEnd := FitsFormulas.end_le headEnd fits.2
        simpa [formulasWords, Nat.add_assoc] using tailEnd
end

/-- A fitting complete table stays inside the address space. -/
theorem FitsSequents.end_le {payloadWidth base : Nat}
    {input : List (Tagged.Sequent Nat)}
    (baseBound : base ≤ 2 ^ payloadWidth)
    (fits : FitsSequents payloadWidth base input) :
    base + tableWords input ≤ 2 ^ payloadWidth := by
  induction input generalizing base with
  | nil => simpa [tableWords] using baseBound
  | cons sequent sequents ih =>
      have premiseEnd := FitsFormula.end_le baseBound fits.1
      have conclusionEnd := FitsFormula.end_le premiseEnd fits.2.1
      have restEnd := ih conclusionEnd fits.2.2
      simpa [tableWords, sequentWords, Nat.add_assoc] using restEnd

/-- Concrete output for one formula. -/
structure Chunk (payloadWidth : Nat) where
  reference : Word.Ref payloadWidth
  words : List (Word payloadWidth)
  live : List Block

/-- Concrete output for a proper list of children. -/
structure Forest (payloadWidth : Nat) where
  references : List (Word.Ref payloadWidth)
  words : List (Word payloadWidth)
  live : List Block

/-- Refine a raw nonzero word into a checked proposition reference. -/
def asRef? (word : Word payloadWidth) : Option (Word.Ref payloadWidth) :=
  if reference : word.IsRef then some ⟨word, reference⟩ else none

theorem asRef?_word {word : Word payloadWidth} {reference : Word.Ref payloadWidth}
    (encoded : asRef? word = some reference) : reference.word = word := by
  unfold asRef? at encoded
  split at encoded
  · have equal := Option.some.inj encoded
    subst reference
    rfl
  · contradiction

private theorem asRef?_some {word : Word payloadWidth} (reference : word.IsRef) :
    ∃ result, asRef? word = some result := by
  exact ⟨⟨word, reference⟩, by simp [asRef?, reference]⟩

private theorem literal?_some {payloadWidth atom : Nat} {negative : Bool}
    (bound : 4 * atom + 3 < 2 ^ payloadWidth) :
    ∃ word, Word.literal? payloadWidth atom negative = some word := by
  let word : Word payloadWidth := ⟨negative, ⟨4 * atom + 3, bound⟩⟩
  refine ⟨word, ?_⟩
  suffices 4 * atom + 3 < 2 ^ payloadWidth by
    simpa [Word.literal?, Word.withTag?, word]
  exact bound

private theorem pointer?_some {payloadWidth base tag : Nat} {negative : Bool}
    (aligned : base % 4 = 0) (nonzero : base ≠ 0) (tagBound : tag < 3)
    (bound : base + tag < 2 ^ payloadWidth) :
    ∃ word, Word.pointer? payloadWidth base tag negative = some word := by
  let word : Word payloadWidth := ⟨negative, ⟨base + tag, bound⟩⟩
  refine ⟨word, ?_⟩
  suffices ¬tag = 3 ∧ tag < 4 ∧ base + tag < 2 ^ payloadWidth by
    simpa [Word.pointer?, Word.withTag?, aligned, nonzero, word]
  exact ⟨by omega, by omega, bound⟩

private theorem natural?_some {payloadWidth value : Nat}
    (bound : value < 2 ^ payloadWidth) :
    ∃ word, Allocator.natural? payloadWidth value = some word := by
  exact ⟨⟨false, ⟨value, bound⟩⟩, by simp [Allocator.natural?, bound]⟩

private theorem liveWords?_some {payloadWidth : Nat} {block : Block}
    {references : List (Word.Ref payloadWidth)}
    (classBound : block.sizeClass + 2 ≤ payloadWidth)
    (room : references.length + 1 < block.capacity) :
    ∃ words,
      Allocator.liveWords? payloadWidth block references = some words ∧
      words.length = block.capacity := by
  have classLt : block.sizeClass < 2 ^ payloadWidth := by
    have self : block.sizeClass < 2 ^ block.sizeClass := Nat.lt_two_pow_self
    have monotone : 2 ^ block.sizeClass ≤ 2 ^ payloadWidth := by
      exact Nat.pow_le_pow_right (by decide) (by omega)
    exact self.trans_le monotone
  obtain ⟨header, headerEncoded⟩ := natural?_some classLt
  have childrenRoom : references.length < block.capacity - 1 := by omega
  let children := references.map Word.Ref.word ++
    List.replicate (block.capacity - 1 - references.length)
      (Word.zero payloadWidth)
  have childrenEncoded :
      encodeWords payloadWidth (block.capacity - 1) references = some children := by
    simp [encodeWords, children, childrenRoom]
  refine ⟨header :: children, ?_, ?_⟩
  · simp [Allocator.liveWords?, classBound, headerEncoded, childrenEncoded]
  · rw [List.length_cons, encodeWords_length childrenEncoded]
    have positive := Block.capacity_pos block
    omega

mutual
  /-- Build one formula at the next aligned storage address. -/
  def formula? (payloadWidth base : Nat) :
      Tagged.Formula Nat → Option (Chunk payloadWidth)
    | .literal value => do
        let word ← Word.literal? payloadWidth value.atom value.negative
        let reference ← asRef? word
        some ⟨reference, [], []⟩
    | .and negative children => node? payloadWidth base 0 negative children
    | .or negative children => node? payloadWidth base 1 negative children
    | .sat negative children => node? payloadWidth base 2 negative children

  /-- Build one tagged array and all of its descendants. -/
  def node? (payloadWidth base tag : Nat) (negative : Bool)
      (children : List (Tagged.Formula Nat)) : Option (Chunk payloadWidth) := do
    let block : Block := ⟨base, leastSizeClass children.length⟩
    let forest ← formulas? payloadWidth block.stop children
    let contents ← liveWords? payloadWidth block forest.references
    let word ← Word.pointer? payloadWidth block.base tag negative
    let reference ← asRef? word
    some ⟨reference, contents ++ forest.words, block :: forest.live⟩

  /-- Build children consecutively after their owner's complete block. -/
  def formulas? (payloadWidth base : Nat) :
      List (Tagged.Formula Nat) → Option (Forest payloadWidth)
    | [] => some ⟨[], [], []⟩
    | head :: tail => do
        let builtHead ← formula? payloadWidth base head
        let builtTail ← formulas? payloadWidth
          (base + builtHead.words.length) tail
        some ⟨builtHead.reference :: builtTail.references,
          builtHead.words ++ builtTail.words,
          builtHead.live ++ builtTail.live⟩
end

/-! ## Builder completeness for explicit bounds -/

mutual
  private theorem formula?_complete {payloadWidth base : Nat}
      (formula : Tagged.Formula Nat)
      (fits : FitsFormula payloadWidth base formula) :
      ∃ chunk,
        formula? payloadWidth base formula = some chunk ∧
        chunk.words.length = formulaWords formula := by
    cases formula with
    | literal value =>
        obtain ⟨word, wordEncoded⟩ := literal?_some fits
        have wordIsRef : word.IsRef := by
          have tag := Word.literal?_tag wordEncoded
          intro zero
          simp [Word.tag, zero] at tag
        obtain ⟨reference, referenceEncoded⟩ :=
          asRef?_some wordIsRef
        refine ⟨⟨reference, [], []⟩, ?_, by simp [formulaWords]⟩
        rw [formula?]
        rw [wordEncoded]
        change (do
          let reference ← asRef? word
          some (⟨reference, [], []⟩ : Chunk payloadWidth)) =
            some (⟨reference, [], []⟩ : Chunk payloadWidth)
        rw [referenceEncoded]
        rfl
    | and negative children =>
        simpa only [formula?, formulaWords] using
          node?_complete (tag := 0) (by decide) negative children fits
    | or negative children =>
        simpa only [formula?, formulaWords] using
          node?_complete (tag := 1) (by decide) negative children fits
    | sat negative children =>
        simpa only [formula?, formulaWords] using
          node?_complete (tag := 2) (by decide) negative children fits

  private theorem node?_complete {payloadWidth base tag : Nat}
      (tagBound : tag < 3) (negative : Bool)
      (children : List (Tagged.Formula Nat))
      (fits :
        let block : Block := ⟨base, leastSizeClass children.length⟩
        block.Aligned ∧
        block.stop ≤ 2 ^ payloadWidth ∧
        block.sizeClass + 2 ≤ payloadWidth ∧
        FitsFormulas payloadWidth block.stop children) :
      ∃ chunk,
        node? payloadWidth base tag negative children = some chunk ∧
        chunk.words.length =
          4 * 2 ^ leastSizeClass children.length + formulasWords children := by
    let block : Block := ⟨base, leastSizeClass children.length⟩
    change block.Aligned ∧ block.stop ≤ 2 ^ payloadWidth ∧
      block.sizeClass + 2 ≤ payloadWidth ∧
      FitsFormulas payloadWidth block.stop children at fits
    obtain ⟨forest, forestEncoded, referenceCount, forestLength⟩ :=
      formulas?_complete children fits.2.2.2
    have room : forest.references.length + 1 < block.capacity := by
      rw [referenceCount]
      exact leastSizeClass_room children.length
    obtain ⟨contents, contentsEncoded, contentsLength⟩ :=
      liveWords?_some fits.2.2.1 room
    have pointerBound : block.base + tag < 2 ^ payloadWidth := by
      have capacity := Block.four_le_capacity block
      have stopBound := fits.2.1
      simp only [Block.stop] at stopBound
      omega
    obtain ⟨word, wordEncoded⟩ :=
      pointer?_some (base := block.base) fits.1.2 (by
        have lower := fits.1.1
        omega) tagBound pointerBound
    obtain ⟨reference, referenceEncoded⟩ :=
      asRef?_some (Word.pointer?_isRef wordEncoded)
    refine ⟨⟨reference, contents ++ forest.words, block :: forest.live⟩,
      ?_, ?_⟩
    · rw [node?]
      change (do
        let forest ← formulas? payloadWidth block.stop children
        let contents ← liveWords? payloadWidth block forest.references
        let word ← Word.pointer? payloadWidth block.base tag negative
        let reference ← asRef? word
        some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
          Chunk payloadWidth)) =
          some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
            Chunk payloadWidth)
      rw [forestEncoded]
      change (do
        let contents ← liveWords? payloadWidth block forest.references
        let word ← Word.pointer? payloadWidth block.base tag negative
        let reference ← asRef? word
        some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
          Chunk payloadWidth)) =
          some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
            Chunk payloadWidth)
      rw [contentsEncoded]
      change (do
        let word ← Word.pointer? payloadWidth block.base tag negative
        let reference ← asRef? word
        some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
          Chunk payloadWidth)) =
          some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
            Chunk payloadWidth)
      rw [wordEncoded]
      change (do
        let reference ← asRef? word
        some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
          Chunk payloadWidth)) =
          some (⟨reference, contents ++ forest.words, block :: forest.live⟩ :
            Chunk payloadWidth)
      rw [referenceEncoded]
      rfl
    · simp [contentsLength, forestLength, Block.capacity, block]

  private theorem formulas?_complete {payloadWidth base : Nat}
      (formulas : List (Tagged.Formula Nat))
      (fits : FitsFormulas payloadWidth base formulas) :
      ∃ forest,
        formulas? payloadWidth base formulas = some forest ∧
        forest.references.length = formulas.length ∧
        forest.words.length = formulasWords formulas := by
    cases formulas with
    | nil =>
        refine ⟨(⟨[], [], []⟩ : Forest payloadWidth), ?_, rfl, rfl⟩
        rw [formulas?]
    | cons head tail =>
        obtain ⟨headChunk, headEncoded, headLength⟩ :=
          formula?_complete head fits.1
        obtain ⟨tailForest, tailEncoded, tailReferences, tailLength⟩ :=
          formulas?_complete tail fits.2
        have tailAtActual :
            formulas? payloadWidth (base + headChunk.words.length) tail =
              some tailForest := by
          rw [headLength]
          exact tailEncoded
        refine ⟨⟨headChunk.reference :: tailForest.references,
          headChunk.words ++ tailForest.words,
          headChunk.live ++ tailForest.live⟩, ?_, ?_, ?_⟩
        · rw [formulas?]
          rw [headEncoded]
          change (do
            let builtTail ← formulas? payloadWidth
              (base + headChunk.words.length) tail
            some (⟨headChunk.reference :: builtTail.references,
              headChunk.words ++ builtTail.words,
              headChunk.live ++ builtTail.live⟩ : Forest payloadWidth)) =
              some (⟨headChunk.reference :: tailForest.references,
                headChunk.words ++ tailForest.words,
                headChunk.live ++ tailForest.live⟩ : Forest payloadWidth)
          rw [tailAtActual]
          rfl
        · simp [tailReferences]
        · simp [headLength, tailLength, formulasWords]
end

/-- Concrete output for a complete sequent table. -/
structure RootChunk (payloadWidth : Nat) where
  roots : List (Word.Ref payloadWidth × Word.Ref payloadWidth)
  words : List (Word payloadWidth)
  live : List Block

/-- Build every sequent consecutively. -/
def sequents? (payloadWidth : Nat) : Nat → List (Tagged.Sequent Nat) →
    Option (RootChunk payloadWidth)
  | _, [] => some ⟨[], [], []⟩
  | base, sequent :: sequents => do
      let premise ← formula? payloadWidth base sequent.premise
      let conclusion ← formula? payloadWidth
        (base + premise.words.length) sequent.conclusion
      let rest ← sequents? payloadWidth
        (base + premise.words.length + conclusion.words.length) sequents
      some ⟨(premise.reference, conclusion.reference) :: rest.roots,
        premise.words ++ conclusion.words ++ rest.words,
        premise.live ++ conclusion.live ++ rest.live⟩

theorem sequents?_complete {payloadWidth base : Nat}
    (input : List (Tagged.Sequent Nat))
    (fits : FitsSequents payloadWidth base input) :
    ∃ built,
      sequents? payloadWidth base input = some built ∧
      built.roots.length = input.length ∧
      built.words.length = tableWords input := by
  induction input generalizing base with
  | nil =>
      refine ⟨(⟨[], [], []⟩ : RootChunk payloadWidth), ?_, rfl, rfl⟩
      rw [sequents?]
  | cons sequent sequents ih =>
      obtain ⟨premise, premiseEncoded, premiseLength⟩ :=
        formula?_complete sequent.premise fits.1
      obtain ⟨conclusion, conclusionEncoded, conclusionLength⟩ :=
        formula?_complete sequent.conclusion fits.2.1
      obtain ⟨rest, restEncoded, restRoots, restLength⟩ :=
        ih fits.2.2
      have conclusionAtActual :
          formula? payloadWidth (base + premise.words.length) sequent.conclusion =
            some conclusion := by
        rw [premiseLength]
        exact conclusionEncoded
      have restAtActual :
          sequents? payloadWidth
            (base + premise.words.length + conclusion.words.length) sequents =
              some rest := by
        rw [premiseLength, conclusionLength]
        exact restEncoded
      let built : RootChunk payloadWidth :=
        ⟨(premise.reference, conclusion.reference) :: rest.roots,
          premise.words ++ conclusion.words ++ rest.words,
          premise.live ++ conclusion.live ++ rest.live⟩
      refine ⟨built, ?_, ?_, ?_⟩
      · rw [sequents?, premiseEncoded]
        change (do
          let conclusion ← formula? payloadWidth
            (base + premise.words.length) sequent.conclusion
          let rest ← sequents? payloadWidth
            (base + premise.words.length + conclusion.words.length) sequents
          some (⟨(premise.reference, conclusion.reference) :: rest.roots,
            premise.words ++ conclusion.words ++ rest.words,
            premise.live ++ conclusion.live ++ rest.live⟩ : RootChunk payloadWidth)) =
              some built
        rw [conclusionAtActual]
        change (do
          let rest ← sequents? payloadWidth
            (base + premise.words.length + conclusion.words.length) sequents
          some (⟨(premise.reference, conclusion.reference) :: rest.roots,
            premise.words ++ conclusion.words ++ rest.words,
            premise.live ++ conclusion.live ++ rest.live⟩ : RootChunk payloadWidth)) =
              some built
        rw [restAtActual]
        rfl
      · simp [built, restRoots]
      · simp only [built, List.length_append, premiseLength, conclusionLength,
          restLength, tableWords, sequentWords]

/-- Build the exact canonical candidate without validating it. -/
def raw? (payloadWidth : Nat) (input : List (Tagged.Sequent Nat)) :
    Option (Arena payloadWidth) := do
  let built ← sequents? payloadWidth 4 input
  let header := List.replicate 4 (Word.zero payloadWidth)
  some {
    words := (header ++ built.words).toArray
    freeRoot := Word.zero payloadWidth
    roots := built.roots }

/-- The explicit resource predicate is sufficient for the raw canonical
builder to succeed. -/
theorem raw?_complete {payloadWidth : Nat} {input : List (Tagged.Sequent Nat)}
    (fits : Fits payloadWidth input) :
    ∃ arena,
      raw? payloadWidth input = some arena ∧
      arena.words.size = 4 + tableWords input ∧
      arena.freeRoot = Word.zero payloadWidth := by
  obtain ⟨built, builtEncoded, _, builtLength⟩ :=
    sequents?_complete input fits.2
  let arena : Arena payloadWidth := {
    words := (List.replicate 4 (Word.zero payloadWidth) ++ built.words).toArray
    freeRoot := Word.zero payloadWidth
    roots := built.roots }
  refine ⟨arena, ?_, ?_, rfl⟩
  · unfold raw?
    rw [builtEncoded]
    rfl
  · change (List.replicate 4 (Word.zero payloadWidth) ++ built.words).length =
      4 + tableWords input
    rw [List.length_append, List.length_replicate, builtLength]

/-- Exact canonical normal form produced by the deterministic raw builder. -/
def NormalForm (payloadWidth : Nat) (input : List (Tagged.Sequent Nat))
    (arena : Arena payloadWidth) : Prop :=
  raw? payloadWidth input = some arena

theorem NormalForm.freeRoot_zero
    {input : List (Tagged.Sequent Nat)} {arena : Arena payloadWidth}
    (normal : NormalForm payloadWidth input arena) :
    arena.freeRoot = Word.zero payloadWidth := by
  unfold NormalForm raw? at normal
  cases built : sequents? payloadWidth 4 input with
  | none => simp [built] at normal
  | some value =>
      rw [built] at normal
      have equal := Option.some.inj normal
      subst arena
      rfl

/-- Canonically pack syntax and return it only through the checked runtime
wrapper. -/
def pack? (payloadWidth : Nat) (input : List (Tagged.Sequent Nat)) :
    Option (Checked payloadWidth) := do
  let candidate ← raw? payloadWidth input
  let checked ← check? candidate
  if checked.decoded.sequents = input then some checked else none

/-- Successful packing gives the exact canonical bytes and exact decoded
syntax. -/
theorem pack?_result {input : List (Tagged.Sequent Nat)}
    {checked : Checked payloadWidth}
    (packed : pack? payloadWidth input = some checked) :
    NormalForm payloadWidth input checked.arena ∧
    checked.decoded.sequents = input ∧
    Represents checked.arena input := by
  unfold pack? at packed
  cases raw : raw? payloadWidth input with
  | none => simp [raw] at packed
  | some candidate =>
      rw [raw] at packed
      change (do
        let checked ← check? candidate
        if checked.decoded.sequents = input then some checked else none) =
          some checked at packed
      cases validated : check? candidate with
      | none => simp [validated] at packed
      | some result =>
          rw [validated] at packed
          change (if result.decoded.sequents = input then some result else none) =
            some checked at packed
          by_cases same : result.decoded.sequents = input
          · rw [if_pos same] at packed
            have equal : result = checked := Option.some.inj packed
            subst checked
            have checkedResult := check?_valid validated
            refine ⟨?_, same, ?_⟩
            · unfold NormalForm
              rw [checkedResult.1]
              exact raw
            unfold Represents Arena.decode?
            rw [result.valid]
            simp [same]
          · rw [if_neg same] at packed
            contradiction

/-- In particular, successful packing is accepted by the ordinary runtime
decoder. -/
theorem pack?_decodes {input : List (Tagged.Sequent Nat)}
    {checked : Checked payloadWidth}
    (packed : pack? payloadWidth input = some checked) :
    checked.arena.decode? = some input :=
  (pack?_result packed).2.2

end Nucleus.Classical.Tagged.Runtime.Encode
