[package]
name = "covalence-data-sexpr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Representation-neutral S-expression data types and views"
publish = false

[dependencies]
covalence-data-symbol = { path = "../symbol" }

[lints]
workspace = true
