import Nucleus.HolOmega.Consistency

/-!
# Covalence directly over raw de Bruijn HOL-omega

This is the small, backend-facing Covalence layer.  It deliberately does not
depend on the locally nameless frontend: a frontend may elaborate into this
module, but this module's soundness only uses the raw HOL-omega calculus.

Rows are annotated ternary tuple trees.  Terms are pointwise typed families
over a shared filling of named holes.  In particular, equality and theorem
certificates below are generated by one constructor for each raw rule; there
is no constructor which imports an already-proved conclusion.
-/

universe u v

namespace Nucleus.CovalenceDeBruijn

open HolOmega

/-- A path into an annotated ternary tuple tree. -/
inductive Slot | left | middle | right
  deriving DecidableEq, Repr

/-- The information required to repair de Bruijn indices when a row is moved. -/
structure Annotation where
  tyDepth : Nat
  tmDepth : Nat
  deriving DecidableEq, Repr

/-- The representation used for annotations, hole arguments, and dialect rows. -/
inductive TupleTree (Base : Type u) where
  | atom (annotation : Annotation) (payload : Base)
  | tuple (annotation : Annotation)
      (left middle right : Option (TupleTree Base))
  deriving Repr

namespace TupleTree

def annotation : TupleTree Base → Annotation
  | .atom a _ | .tuple a .. => a

/-- Repair the two namespaces independently after moving a tree under binders. -/
def repairBound (addTy addTm : Nat) : TupleTree Base → TupleTree Base
  | .atom a x => .atom { tyDepth := a.tyDepth + addTy,
                         tmDepth := a.tmDepth + addTm } x
  | .tuple a l m r =>
      .tuple { tyDepth := a.tyDepth + addTy, tmDepth := a.tmDepth + addTm }
        (match l with | none => none | some x => some (repairBound addTy addTm x))
        (match m with | none => none | some x => some (repairBound addTy addTm x))
        (match r with | none => none | some x => some (repairBound addTy addTm x))

end TupleTree

/-- Stable identity of a hole.  Its name is independent of binder depth. -/
structure HoleName where
  id : Nat
  deriving DecidableEq, Repr

/-- Row metadata is deliberately independent of object-language base symbols. -/
inductive RowTag where
  | operator (code : Nat)
  | typeLeaf
  | termLeaf
  | hole (name : HoleName)
  deriving DecidableEq, Repr

/-- A typed result supplied for a hole. -/
structure Typed (Base : Type u) (Δ : KindCtx) (Γ : TmCtx Base) (A : Ty Base) where
  term : Tm Base
  typing : HasType Δ Γ term A

/-- One filling is shared by the whole certificate, including subterms below
term and type binders.  Requiring a typed answer makes filling total and safe. -/
abbrev Filling (Base : Type u) :=
  ∀ (Δ : KindCtx) (Γ : TmCtx Base) (name : HoleName)
    (A : Ty Base) (r : Nat), Kinded Δ A ⟨.star, r⟩ → Typed Base Δ Γ A

/-- Every formed type has a canonical inhabitant: choice applied to the
constantly true predicate.  This gives a filling used by consistency. -/
def canonicalFilling (Base : Type u) : Filling Base := by
  intro Δ Γ _name A r hA
  let pred : Tm Base := .tmLam A (.tmBool true)
  exact ⟨.tmEps A pred,
    Judgement.tmEps hA (Judgement.tmLam hA Judgement.tmBool)⟩

/-- A de Bruijn Covalence term is an annotated row plus a typed interpretation
for every shared hole filling.  The type index is available in constant time. -/
structure Term (Base : Type u) (Δ : KindCtx) (Γ : TmCtx Base) (A : Ty Base) where
  row : TupleTree RowTag
  lower : Filling Base → Tm Base
  typing : ∀ filling, HasType Δ Γ (lower filling) A

namespace Term

variable {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
  {A B : Ty Base} {r : Nat}

def closed (t : Tm Base) (ht : HasType Δ Γ t A) : Term Base Δ Γ A where
  row := .atom ⟨Δ.length, Γ.length⟩ .termLeaf
  lower := fun _ => t
  typing := fun _ => ht

def hole (name : HoleName) (hA : Kinded Δ A ⟨.star, r⟩) : Term Base Δ Γ A where
  row := .tuple ⟨Δ.length, Γ.length⟩
    (some (.atom ⟨Δ.length, Γ.length⟩ .typeLeaf))
    (some (.atom ⟨0, 0⟩ (.hole name))) none
  lower := fun filling => (filling Δ Γ name A r hA).term
  typing := fun filling => (filling Δ Γ name A r hA).typing

private def binaryRow (tag : RowTag) (x y : TupleTree RowTag) :
    TupleTree RowTag := .tuple ⟨0, 0⟩
      (some (.atom ⟨0, 0⟩ tag)) (some x) (some y)

def app (f : Term Base Δ Γ (.tyArr A B)) (x : Term Base Δ Γ A) :
    Term Base Δ Γ B where
  row := binaryRow (.operator 0) f.row x.row
  lower := fun e => .tmApp (f.lower e) (x.lower e)
  typing := fun e => Judgement.tmApp (f.typing e) (x.typing e)

def lam (hA : Kinded Δ A ⟨.star, r⟩) (body : Term Base Δ (A :: Γ) B) :
    Term Base Δ Γ (.tyArr A B) where
  row := .tuple ⟨Δ.length, Γ.length⟩ (some body.row) none none
  lower := fun e => .tmLam A (body.lower e)
  typing := fun e => Judgement.tmLam hA (body.typing e)

def tyApp {RK : RKind} (f : Term Base Δ Γ (.tyAll RK A))
    (X : Ty Base) (hX : Kinded Δ X RK) : Term Base Δ Γ (A.instTy X) where
  row := binaryRow (.operator 1) f.row (.atom ⟨Δ.length, 0⟩ .typeLeaf)
  lower := fun e => .tmTyApp (f.lower e) X
  typing := fun e => Judgement.tmTyApp (f.typing e) hX

def tyLam {RK : RKind} (body : Term Base (RK :: Δ) Γ.liftTy A) :
    Term Base Δ Γ (.tyAll RK A) where
  row := .tuple ⟨Δ.length, Γ.length⟩ (some body.row) none none
  lower := fun e => .tmTyLam RK (body.lower e)
  typing := fun e => Judgement.tmTyLam (body.typing e)

def inst (body : Term Base Δ (A :: Γ) B) (x : Term Base Δ Γ A)
    (ht : ∀ e, HasType Δ Γ ((body.lower e).inst (x.lower e)) B) :
    Term Base Δ Γ B where
  row := binaryRow (.operator 2) body.row x.row
  lower := fun e => (body.lower e).inst (x.lower e)
  typing := ht

def instTy {RK : RKind} (body : Term Base (RK :: Δ) Γ.liftTy A)
    (X : Ty Base) (ht : ∀ e, HasType Δ Γ ((body.lower e).instTy X) (A.instTy X)) :
    Term Base Δ Γ (A.instTy X) where
  row := binaryRow (.operator 3) body.row (.atom ⟨Δ.length, 0⟩ .typeLeaf)
  lower := fun e => (body.lower e).instTy X
  typing := ht

/-- Internal smart constructor for a raw-rule-shaped family.  Its typing
premise is regularity only; it cannot assert equality or provability. -/
def derived (row : TupleTree RowTag) (lower : Filling Base → Tm Base)
    (typing : ∀ e, HasType Δ Γ (lower e) A) : Term Base Δ Γ A :=
  ⟨row, lower, typing⟩

/-- Explicit object-language cast.  The row is unchanged; only a checked
HOL-omega conversion changes its constant-time type index. -/
def cast (t : Term Base Δ Γ A) (hAB : TyConv Δ A B) : Term Base Δ Γ B where
  row := t.row
  lower := t.lower
  typing := fun e => Judgement.conv (t.typing e) hAB

def etaExpansion (f : Term Base Δ Γ (.tyArr A B))
    (ht : ∀ e, HasType Δ Γ
      (.tmLam A (.tmApp ((f.lower e).rename Nat.succ) (.tmVar 0))) (.tyArr A B)) :
    Term Base Δ Γ (.tyArr A B) :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some f.row) none none)
    (fun e => .tmLam A (.tmApp ((f.lower e).rename Nat.succ) (.tmVar 0))) ht

def tyEtaExpansion {RK : RKind} (f : Term Base Δ Γ (.tyAll RK A))
    (ht : ∀ e, HasType Δ Γ
      (.tmTyLam RK (.tmTyApp (f.lower e).liftTy (.tyVar 0))) (.tyAll RK A)) :
    Term Base Δ Γ (.tyAll RK A) :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some f.row) none none)
    (fun e => .tmTyLam RK (.tmTyApp (f.lower e).liftTy (.tyVar 0))) ht

def eq (hA : Kinded Δ A ⟨.star, r⟩) (x y : Term Base Δ Γ A) :
    Term Base Δ Γ .tyBool :=
  derived (binaryRow (.operator 4) x.row y.row)
    (fun e => .tmEq A (x.lower e) (y.lower e))
    (fun e => Judgement.tmEq hA (x.typing e) (y.typing e))

def eps (hA : Kinded Δ A ⟨.star, r⟩)
    (p : Term Base Δ Γ (.tyArr A .tyBool)) : Term Base Δ Γ A :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some p.row) none none)
    (fun e => .tmEps A (p.lower e)) (fun e => Judgement.tmEps hA (p.typing e))

def abs (hA : Kinded Δ A ⟨.star, r⟩) (hp : HasType Δ [A] p .tyBool)
    (x : Term Base Δ Γ A) : Term Base Δ Γ (.tySub A p) :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some x.row) none none)
    (fun e => .tmAbs A p (x.lower e)) (fun e => Judgement.tmAbs hA hp (x.typing e))

def rep (hA : Kinded Δ A ⟨.star, r⟩) (hp : HasType Δ [A] p .tyBool)
    (x : Term Base Δ Γ (.tySub A p)) : Term Base Δ Γ A :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some x.row) none none)
    (fun e => .tmRep A p (x.lower e)) (fun e => Judgement.tmRep hA hp (x.typing e))

def predInst (p : Tm Base) (x : Term Base Δ Γ A)
    (ht : ∀ e, HasType Δ Γ (p.inst (x.lower e)) .tyBool) :
    Term Base Δ Γ .tyBool :=
  derived (.tuple ⟨Δ.length, Γ.length⟩ (some x.row) none none)
    (fun e => p.inst (x.lower e)) ht

end Term

/-- Repair relates an untyped row to its indexed interpretation.  `bound`
records namespace-separated de Bruijn repair, while `cast` records the exact
checked conversion used to change the output index. -/
inductive Repairs {Base : Type u} :
    (Δ : KindCtx) → (Γ : TmCtx Base) → (A : Ty Base) →
    TupleTree RowTag → Term Base Δ Γ A → Prop
  | exact (t : Term Base Δ Γ A) : Repairs Δ Γ A t.row t
  | bound (addTy addTm : Nat) (t : Term Base Δ Γ A) :
      Repairs Δ Γ A (t.row.repairBound addTy addTm) t
  | cast (hAB : TyConv Δ A B) : Repairs Δ Γ A row t →
      Repairs Δ Γ B row (Term.cast t hAB)

/-- Successful indexing of an otherwise untyped row. -/
structure Repaired (Base : Type u) (Δ : KindCtx) (Γ : TmCtx Base)
    (row : TupleTree RowTag) where
  ty : Ty Base
  term : Term Base Δ Γ ty
  repairs : Repairs Δ Γ ty row term

/-- Minimal interface implemented by persistent-memory unfolding.  Keeping
the adapter generic prevents the raw backend from depending on the locally
nameless frontend's row language. -/
structure Unfolding (Index : Type v) where
  unfold : Nat → Index → TupleTree RowTag

/-- A checked repair of an unfolded memory cell is immediately an indexed
backend term; no extra trust or imported proof is introduced. -/
def repairUnfold (source : Unfolding Index) (depth : Nat) (index : Index)
    (result : Repaired Base Δ Γ (source.unfold depth index)) :
    Repaired Base Δ Γ (source.unfold depth index) := result

/-- Premise-driven equality rules.  Checker-side regularity premises are the
same premises exposed by raw `HolOmega.EqTm`; no rule accepts an equality of
its own conclusion. -/
inductive CovEq {Bse : Type u} :
    (Δ : KindCtx) → (Γ : TmCtx Bse) → (A : Ty Bse) →
    Term Bse Δ Γ A → Term Bse Δ Γ A → Prop
  | refl (t : Term Bse Δ Γ A) : CovEq Δ Γ A t t
  | symm : CovEq Δ Γ A t u → CovEq Δ Γ A u t
  | trans : CovEq Δ Γ A t u → CovEq Δ Γ A u v → CovEq Δ Γ A t v
  | app : CovEq Δ Γ (.tyArr A B) f g → CovEq Δ Γ A x y →
      CovEq Δ Γ B (Term.app f x) (Term.app g y)
  | lam (hA : Kinded Δ A ⟨.star, r⟩) : CovEq Δ (A :: Γ) B t u →
      CovEq Δ Γ (.tyArr A B) (Term.lam hA t) (Term.lam hA u)
  | tyApp {RK : RKind} {X A : Ty Bse} (hX : Kinded Δ X RK)
      (f g : Term Bse Δ Γ (.tyAll RK A)) :
      CovEq Δ Γ (.tyAll RK A) f g →
      CovEq Δ Γ (A.instTy X) (Term.tyApp (RK := RK) f X hX)
        (Term.tyApp (RK := RK) g X hX)
  | tyLam {RK : RKind} (t u : Term Bse (RK :: Δ) Γ.liftTy A) :
      CovEq (RK :: Δ) Γ.liftTy A t u →
      CovEq Δ Γ (.tyAll RK A) (Term.tyLam t) (Term.tyLam u)
  | beta (hA : Kinded Δ A ⟨.star, r⟩)
      (body : Term Bse Δ (A :: Γ) B) (x : Term Bse Δ Γ A)
      (hinst : ∀ e, HasType Δ Γ ((body.lower e).inst (x.lower e)) B) :
      CovEq Δ Γ B (Term.app (Term.lam hA body) x) (Term.inst body x hinst)
  | tyBeta {RK : RKind} {X : Ty Bse}
      (body : Term Bse (RK :: Δ) Γ.liftTy A) (hX : Kinded Δ X RK)
      (hinst : ∀ e, HasType Δ Γ ((body.lower e).instTy X) (A.instTy X)) :
      CovEq Δ Γ (A.instTy X) (Term.tyApp (Term.tyLam body) X hX)
        (Term.instTy body X hinst)
  | eta (f : Term Bse Δ Γ (.tyArr A B))
      (heta : ∀ e, HasType Δ Γ
        (.tmLam A (.tmApp ((f.lower e).rename Nat.succ) (.tmVar 0))) (.tyArr A B)) :
      CovEq Δ Γ (.tyArr A B) (Term.etaExpansion f heta) f
  | tyEta {RK : RKind} (f : Term Bse Δ Γ (.tyAll RK A))
      (heta : ∀ e, HasType Δ Γ
        (.tmTyLam RK (.tmTyApp (f.lower e).liftTy (.tyVar 0))) (.tyAll RK A)) :
      CovEq Δ Γ (.tyAll RK A) (Term.tyEtaExpansion f heta) f
  | unpackPack {RK : RKind} (hA : Kinded (RK :: Δ) A ⟨.star, s⟩)
      (hB : Kinded Δ B ⟨.star, q⟩) (hX : Kinded Δ X RK)
      (t : Term Bse Δ Γ (A.instTy X))
      (k : Term Bse (RK :: Δ) (A :: Γ.liftTy) B.liftTy)
      (hlhs : ∀ e, HasType Δ Γ
        (.tmUnpack RK A B (k.lower e) (.tmPack RK A X (t.lower e))) B)
      (hrhs : ∀ e, HasType Δ Γ (((k.lower e).instTy X).inst (t.lower e)) B) :
      CovEq Δ Γ B
        (Term.derived (.tuple ⟨Δ.length, Γ.length⟩ (some k.row) (some t.row) none)
          (fun e => .tmUnpack RK A B (k.lower e) (.tmPack RK A X (t.lower e))) hlhs)
        (Term.derived (.tuple ⟨Δ.length, Γ.length⟩ (some k.row) (some t.row) none)
          (fun e => ((k.lower e).instTy X).inst (t.lower e)) hrhs)
  | packOnto {RK : RKind} (p : Term Bse Δ Γ (.tyEx RK A))
      (heta : ∀ e, HasType Δ Γ
        (.tmUnpack RK A (.tyEx RK A) (Expr.repack RK A) (p.lower e)) (.tyEx RK A)) :
      CovEq Δ Γ (.tyEx RK A)
        (Term.derived (.tuple ⟨Δ.length, Γ.length⟩ (some p.row) none none)
          (fun e => .tmUnpack RK A (.tyEx RK A) (Expr.repack RK A) (p.lower e)) heta) p

theorem CovEq.sound {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
    {A : Ty Base} {t u : Term Base Δ Γ A}
    (h : CovEq Δ Γ A t u) (e : Filling Base) :
    EqTm Δ Γ (t.lower e) (u.lower e) A := by
  induction h with
  | refl t => exact .refl (t.typing e)
  | symm _ ih => exact .symm ih
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂
  | app _ _ ihf ihx => exact .app ihf ihx
  | lam hA _ ih => exact .lam hA ih
  | tyApp hX _ _ _ ih => exact .tyApp hX ih
  | tyLam _ _ _ ih => exact .tyLam ih
  | beta hA body x hinst =>
      exact .beta hA (body.typing e) (x.typing e) (hinst e)
  | tyBeta body hX hinst =>
      exact .tyBeta (body.typing e) hX (hinst e)
  | eta f heta => exact .eta (f.typing e) (heta e)
  | tyEta f heta => exact .tyEta (f.typing e) (heta e)
  | unpackPack hA hB hX t k hlhs hrhs =>
      exact .unpackPack hA hB hX (t.typing e) (k.typing e) (hrhs e)
  | packOnto p heta => exact .packOnto (p.typing e) (heta e)

/-- A hypothesis row lowers pointwise under the same filling as its goal. -/
def lowerHyps (e : Filling Base) (H : List (Term Base Δ Γ .tyBool)) : Hyps Base :=
  H.map (fun p => p.lower e)

theorem typed_lowerHyps (e : Filling Base) (H : List (Term Base Δ Γ .tyBool)) :
    TypedHyps Δ Γ (lowerHyps e H) := by
  intro p hp
  rcases List.mem_map.mp hp with ⟨q, hq, rfl⟩
  exact q.typing e

/-- Premise-driven counterpart of every raw theorem rule. -/
inductive CovProves {Base : Type u} (Δ : KindCtx) (Γ : TmCtx Base) :
    List (Term Base Δ Γ .tyBool) → Term Base Δ Γ .tyBool → Prop
  | hyp (hp : p ∈ H) : CovProves Δ Γ H p
  | truth : CovProves Δ Γ H (Term.closed (.tmBool true) Judgement.tmBool)
  | eqRefl (x : Term Base Δ Γ A) (hA : Kinded Δ A ⟨.star, r⟩) :
      CovProves Δ Γ H (Term.eq hA x x)
  | eqMp (p : Term Base Δ Γ (.tyArr A .tyBool))
      (x y : Term Base Δ Γ A) (hA : Kinded Δ A ⟨.star, r⟩) :
      CovProves Δ Γ H (Term.eq hA x y) →
      CovProves Δ Γ H (Term.app p x) → CovProves Δ Γ H (Term.app p y)
  | choice (p : Term Base Δ Γ (.tyArr A .tyBool))
      (x : Term Base Δ Γ A) (hA : Kinded Δ A ⟨.star, r⟩) :
      CovProves Δ Γ H (Term.app p x) →
      CovProves Δ Γ H (Term.app p (Term.eps hA p))
  | convert : CovEq Δ Γ .tyBool p q → CovProves Δ Γ H p → CovProves Δ Γ H q
  | eqOfEqTm (hA : Kinded Δ A ⟨.star, r⟩) (x y : Term Base Δ Γ A) :
      CovEq Δ Γ A x y → CovProves Δ Γ H (Term.eq hA x y)
  | antisymm (p q : Term Base Δ Γ .tyBool) :
      CovProves Δ Γ (p :: H) q → CovProves Δ Γ (q :: H) p →
      CovProves Δ Γ H (Term.eq (Judgement.tyBool (Δ := Δ)) p q)
  | absRep (hA : Kinded Δ A ⟨.star, r⟩) (hp : HasType Δ [A] pred .tyBool)
      (x : Term Base Δ Γ (.tySub A pred)) :
      CovProves Δ Γ H (Term.eq (Judgement.tySub hA hp)
        (Term.abs hA hp (Term.rep hA hp x)) x)
  | repAbs (hA : Kinded Δ A ⟨.star, r⟩) (hp : HasType Δ [A] pred .tyBool)
      (x : Term Base Δ Γ A)
      (hpx : ∀ e, HasType Δ Γ (pred.inst (x.lower e)) .tyBool) :
      CovProves Δ Γ H (Term.predInst pred x hpx) →
      CovProves Δ Γ H (Term.eq hA (Term.rep hA hp (Term.abs hA hp x)) x)

theorem CovProves.sound {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
    {H : List (Term Base Δ Γ .tyBool)} {p : Term Base Δ Γ .tyBool}
    (h : CovProves Δ Γ H p) (e : Filling Base) :
    Proves Δ Γ (lowerHyps e H) (p.lower e) := by
  induction h with
  | hyp hp =>
      exact .hyp (typed_lowerHyps e _) (List.mem_map.mpr ⟨_, hp, rfl⟩)
  | truth => exact .truth (typed_lowerHyps e _)
  | eqRefl x hA => exact .eqRefl (typed_lowerHyps e _) (x.typing e) hA
  | eqMp p x y hA _ _ iheq ihp =>
      exact .eqMp (typed_lowerHyps e _) (p.typing e) (x.typing e) (y.typing e)
        hA iheq ihp
  | choice p x hA _ ih =>
      exact .choice (typed_lowerHyps e _) (p.typing e) (x.typing e) hA ih
  | convert heq _ ih => exact .convert (typed_lowerHyps e _) (heq.sound e) ih
  | eqOfEqTm hA x y heq => exact .eqOfEqTm (typed_lowerHyps e _) hA (heq.sound e)
  | antisymm p q _ _ ihp ihq =>
      exact .antisymm (typed_lowerHyps e _) (p.typing e) (q.typing e)
        (by
          intro z hz
          simp only [List.mem_cons] at hz
          rcases hz with rfl | hz
          · exact p.typing e
          · exact typed_lowerHyps e _ z hz)
        (by
          intro z hz
          simp only [List.mem_cons] at hz
          rcases hz with rfl | hz
          · exact q.typing e
          · exact typed_lowerHyps e _ z hz) ihp ihq
  | absRep hA hp x => exact .absRep (typed_lowerHyps e _) hA hp (x.typing e)
  | repAbs hA hp x hpx _ ih =>
      exact .repAbs (typed_lowerHyps e _) hA hp (x.typing e) (hpx e) ih

abbrev falseTerm : Term Empty [] [] .tyBool :=
  Term.closed (.tmBool false) Judgement.tmBool

/-- Exact backend consistency, with no auxiliary premise. -/
theorem empty_consistent : ¬ CovProves ([] : KindCtx) ([] : TmCtx Empty) [] falseTerm := by
  intro h
  exact HolOmega.raw_not_proves_false (h.sound (canonicalFilling Empty))

end Nucleus.CovalenceDeBruijn
