import Nucleus.HolOmega.Proof

/-!
# Covalence directly over raw de Bruijn HOL-omega

This is the small, backend-facing Covalence layer.  It deliberately does not
depend on the locally nameless frontend: a frontend may elaborate into this
module, but this module's soundness only uses the raw HOL-omega calculus.

Rows are annotated ternary tuple trees.  Terms are pointwise typed families
over a shared filling of named holes.  In particular, equality and theorem
certificates below are generated by one constructor for each raw rule; there
is no constructor which imports an already-proved conclusion.
-/

universe u

namespace Nucleus.CovalenceDeBruijn

open HolOmega

/-- A path into an annotated ternary tuple tree. -/
inductive Slot | left | middle | right
  deriving DecidableEq, Repr

/-- The information required to repair de Bruijn indices when a row is moved. -/
structure Annotation where
  tyDepth : Nat
  tmDepth : Nat
  deriving DecidableEq, Repr

/-- The representation used for annotations, hole arguments, and dialect rows. -/
inductive TupleTree (Base : Type u) where
  | atom (annotation : Annotation) (payload : Base)
  | tuple (annotation : Annotation)
      (left middle right : Option (TupleTree Base))
  deriving Repr

namespace TupleTree

def annotation : TupleTree Base → Annotation
  | .atom a _ | .tuple a .. => a

/-- Repair the two namespaces independently after moving a tree under binders. -/
def repairBound (addTy addTm : Nat) : TupleTree Base → TupleTree Base
  | .atom a x => .atom { tyDepth := a.tyDepth + addTy,
                         tmDepth := a.tmDepth + addTm } x
  | .tuple a l m r =>
      .tuple { tyDepth := a.tyDepth + addTy, tmDepth := a.tmDepth + addTm }
        (match l with | none => none | some x => some (repairBound addTy addTm x))
        (match m with | none => none | some x => some (repairBound addTy addTm x))
        (match r with | none => none | some x => some (repairBound addTy addTm x))

end TupleTree

/-- Stable identity of a hole.  Its name is independent of binder depth. -/
structure HoleName where
  id : Nat
  deriving DecidableEq, Repr

/-- Row metadata is deliberately independent of object-language base symbols. -/
inductive RowTag where
  | operator (code : Nat)
  | typeLeaf
  | termLeaf
  | hole (name : HoleName)
  deriving DecidableEq, Repr

/-- A typed result supplied for a hole. -/
structure Typed (Base : Type u) (Δ : KindCtx) (Γ : TmCtx Base) (A : Ty Base) where
  term : Tm Base
  typing : HasType Δ Γ term A

/-- One filling is shared by the whole certificate, including subterms below
term and type binders.  Requiring a typed answer makes filling total and safe. -/
abbrev Filling (Base : Type u) :=
  ∀ (Δ : KindCtx) (Γ : TmCtx Base) (name : HoleName)
    (A : Ty Base) (r : Nat), Kinded Δ A ⟨.star, r⟩ → Typed Base Δ Γ A

/-- Every formed type has a canonical inhabitant: choice applied to the
constantly true predicate.  This gives a filling used by consistency. -/
def canonicalFilling (Base : Type u) : Filling Base := by
  intro Δ Γ name A r hA
  let pred : Tm Base := .tmLam A (.tmBool true)
  exact ⟨.tmEps A pred,
    Judgement.tmEps hA (Judgement.tmLam hA Judgement.tmBool)⟩

/-- A de Bruijn Covalence term is an annotated row plus a typed interpretation
for every shared hole filling.  The type index is available in constant time. -/
structure Term (Base : Type u) (Δ : KindCtx) (Γ : TmCtx Base) (A : Ty Base) where
  row : TupleTree RowTag
  lower : Filling Base → Tm Base
  typing : ∀ filling, HasType Δ Γ (lower filling) A

namespace Term

variable {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
  {A B : Ty Base} {r : Nat}

def closed (t : Tm Base) (ht : HasType Δ Γ t A) : Term Base Δ Γ A where
  row := .atom ⟨Δ.length, Γ.length⟩ .termLeaf
  lower := fun _ => t
  typing := fun _ => ht

def hole (name : HoleName) (hA : Kinded Δ A ⟨.star, r⟩) : Term Base Δ Γ A where
  row := .tuple ⟨Δ.length, Γ.length⟩
    (some (.atom ⟨Δ.length, Γ.length⟩ .typeLeaf))
    (some (.atom ⟨0, 0⟩ (.hole name))) none
  lower := fun filling => (filling Δ Γ name A r hA).term
  typing := fun filling => (filling Δ Γ name A r hA).typing

private def binaryRow (tag : RowTag) (x y : TupleTree RowTag) :
    TupleTree RowTag := .tuple ⟨0, 0⟩
      (some (.atom ⟨0, 0⟩ tag)) (some x) (some y)

def app (f : Term Base Δ Γ (.tyArr A B)) (x : Term Base Δ Γ A) :
    Term Base Δ Γ B where
  row := binaryRow (.operator 0) f.row x.row
  lower := fun e => .tmApp (f.lower e) (x.lower e)
  typing := fun e => Judgement.tmApp (f.typing e) (x.typing e)

def lam (hA : Kinded Δ A ⟨.star, r⟩) (body : Term Base Δ (A :: Γ) B) :
    Term Base Δ Γ (.tyArr A B) where
  row := .tuple ⟨Δ.length, Γ.length⟩ (some body.row) none none
  lower := fun e => .tmLam A (body.lower e)
  typing := fun e => Judgement.tmLam hA (body.typing e)

def tyApp {RK : RKind} (f : Term Base Δ Γ (.tyAll RK A))
    (X : Ty Base) (hX : Kinded Δ X RK) : Term Base Δ Γ (A.instTy X) where
  row := binaryRow (.operator 1) f.row (.atom ⟨Δ.length, 0⟩ .typeLeaf)
  lower := fun e => .tmTyApp (f.lower e) X
  typing := fun e => Judgement.tmTyApp (f.typing e) hX

def tyLam {RK : RKind} (body : Term Base (RK :: Δ) Γ.liftTy A) :
    Term Base Δ Γ (.tyAll RK A) where
  row := .tuple ⟨Δ.length, Γ.length⟩ (some body.row) none none
  lower := fun e => .tmTyLam RK (body.lower e)
  typing := fun e => Judgement.tmTyLam (body.typing e)

def inst (body : Term Base Δ (A :: Γ) B) (x : Term Base Δ Γ A)
    (ht : ∀ e, HasType Δ Γ ((body.lower e).inst (x.lower e)) B) :
    Term Base Δ Γ B where
  row := binaryRow (.operator 2) body.row x.row
  lower := fun e => (body.lower e).inst (x.lower e)
  typing := ht

def instTy {RK : RKind} (body : Term Base (RK :: Δ) Γ.liftTy A)
    (X : Ty Base) (ht : ∀ e, HasType Δ Γ ((body.lower e).instTy X) (A.instTy X)) :
    Term Base Δ Γ (A.instTy X) where
  row := binaryRow (.operator 3) body.row (.atom ⟨Δ.length, 0⟩ .typeLeaf)
  lower := fun e => (body.lower e).instTy X
  typing := ht

end Term

/-- Premise-driven equality rules.  Checker-side regularity premises are the
same premises exposed by raw `HolOmega.EqTm`; no rule accepts an equality of
its own conclusion. -/
inductive CovEq {Bse : Type u} :
    (Δ : KindCtx) → (Γ : TmCtx Bse) → (A : Ty Bse) →
    Term Bse Δ Γ A → Term Bse Δ Γ A → Prop
  | refl (t : Term Bse Δ Γ A) : CovEq Δ Γ A t t
  | symm : CovEq Δ Γ A t u → CovEq Δ Γ A u t
  | trans : CovEq Δ Γ A t u → CovEq Δ Γ A u v → CovEq Δ Γ A t v
  | app : CovEq Δ Γ (.tyArr A B) f g → CovEq Δ Γ A x y →
      CovEq Δ Γ B (Term.app f x) (Term.app g y)
  | lam (hA : Kinded Δ A ⟨.star, r⟩) : CovEq Δ (A :: Γ) B t u →
      CovEq Δ Γ (.tyArr A B) (Term.lam hA t) (Term.lam hA u)
  | tyApp {RK : RKind} {X A : Ty Bse} (hX : Kinded Δ X RK)
      (f g : Term Bse Δ Γ (.tyAll RK A)) :
      CovEq Δ Γ (.tyAll RK A) f g →
      CovEq Δ Γ (A.instTy X) (Term.tyApp (RK := RK) f X hX)
        (Term.tyApp (RK := RK) g X hX)
  | tyLam {RK : RKind} (t u : Term Bse (RK :: Δ) Γ.liftTy A) :
      CovEq (RK :: Δ) Γ.liftTy A t u →
      CovEq Δ Γ (.tyAll RK A) (Term.tyLam t) (Term.tyLam u)
  | beta (hA : Kinded Δ A ⟨.star, r⟩)
      (body : Term Bse Δ (A :: Γ) B) (x : Term Bse Δ Γ A)
      (hinst : ∀ e, HasType Δ Γ ((body.lower e).inst (x.lower e)) B) :
      CovEq Δ Γ B (Term.app (Term.lam hA body) x) (Term.inst body x hinst)
  | tyBeta {RK : RKind} {X : Ty Bse}
      (body : Term Bse (RK :: Δ) Γ.liftTy A) (hX : Kinded Δ X RK)
      (hinst : ∀ e, HasType Δ Γ ((body.lower e).instTy X) (A.instTy X)) :
      CovEq Δ Γ (A.instTy X) (Term.tyApp (Term.tyLam body) X hX)
        (Term.instTy body X hinst)

theorem CovEq.sound {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
    {A : Ty Base} {t u : Term Base Δ Γ A}
    (h : CovEq Δ Γ A t u) (e : Filling Base) :
    EqTm Δ Γ (t.lower e) (u.lower e) A := by
  induction h with
  | refl t => exact .refl (t.typing e)
  | symm _ ih => exact .symm ih
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂
  | app _ _ ihf ihx => exact .app ihf ihx
  | lam hA _ ih => exact .lam hA ih
  | tyApp hX _ _ _ ih => exact .tyApp hX ih
  | tyLam _ _ _ ih => exact .tyLam ih
  | beta hA body x hinst =>
      exact .beta hA (body.typing e) (x.typing e) (hinst e)
  | tyBeta body hX hinst =>
      exact .tyBeta (body.typing e) hX (hinst e)

/-- A hypothesis row lowers pointwise under the same filling as its goal. -/
def lowerHyps (e : Filling Base) (H : List (Term Base Δ Γ .tyBool)) : Hyps Base :=
  H.map (fun p => p.lower e)

theorem typed_lowerHyps (e : Filling Base) (H : List (Term Base Δ Γ .tyBool)) :
    TypedHyps Δ Γ (lowerHyps e H) := by
  intro p hp
  rcases List.mem_map.mp hp with ⟨q, hq, rfl⟩
  exact q.typing e

/-- The theorem fragment starts with the structural rules needed to state and
prove exact empty consistency.  Further logical constructors are added beside
their matching raw rule, never through an imported conclusion certificate. -/
inductive CovProves {Base : Type u} (Δ : KindCtx) (Γ : TmCtx Base) :
    List (Term Base Δ Γ .tyBool) → Term Base Δ Γ .tyBool → Prop
  | hyp (hp : p ∈ H) : CovProves Δ Γ H p
  | truth : CovProves Δ Γ H (Term.closed (.tmBool true) Judgement.tmBool)

theorem CovProves.sound {Base : Type u} {Δ : KindCtx} {Γ : TmCtx Base}
    {H : List (Term Base Δ Γ .tyBool)} {p : Term Base Δ Γ .tyBool}
    (h : CovProves Δ Γ H p) (e : Filling Base) :
    Proves Δ Γ (lowerHyps e H) (p.lower e) := by
  induction h with
  | hyp hp =>
      exact .hyp (typed_lowerHyps e _) (List.mem_map.mpr ⟨_, hp, rfl⟩)
  | truth => exact .truth (typed_lowerHyps e _)

abbrev falseTerm : Term Empty [] [] .tyBool :=
  Term.closed (.tmBool false) Judgement.tmBool

/-- Exact backend consistency, with no auxiliary premise. -/
theorem empty_consistent : ¬ CovProves ([] : KindCtx) ([] : TmCtx Empty) [] falseTerm := by
  intro h
  generalize heq : falseTerm = p at h
  induction h with
  | hyp hp => simp at hp
  | truth =>
      have hraw := congrArg (fun t => t.lower (canonicalFilling Empty)) heq
      simp [falseTerm, Term.closed] at hraw

end Nucleus.CovalenceDeBruijn
