import Nucleus.TypeFormers

/-!
# Simple types

This is the free simple-type algebra used throughout Nucleus.  It is not tied
to a particular client: forests may use its denotations as index types, while
HOL models may use the same algebra to describe semantic carriers.

`SimpTy` has only caller-supplied atoms and the three binary type formers.
`SimpTy1` and `SimpTy0` add distinguished unit and empty atoms without adding
recursive constructors.  Consequently all three share the same recursion and
the distinguished constants reduce definitionally through atom denotation.

Exponentiation follows cardinal arithmetic: `B ^ A` denotes `A → B`.
-/

namespace Nucleus

universe u v w x

/-- Free simple types generated by atoms, coproducts, products, and functions. -/
inductive SimpTy (Base : Type u) where
  | base (code : Base)
  | sum (left right : SimpTy Base)
  | prod (left right : SimpTy Base)
  | arr (domain codomain : SimpTy Base)
  deriving DecidableEq, Repr

namespace SimpTy

variable {Base : Type u} {Target : Type w} {Middle : Type x}

/-- Atoms for the fragment with a distinguished unit type. -/
inductive Atom1 (Base : Type u) where
  | ofBase (code : Base)
  | unit
  deriving DecidableEq, Repr

/-- Atoms for the fragment with distinguished unit and empty types. -/
inductive Atom0 (Base : Type u) where
  | ofBase (code : Base)
  | unit
  | empty
  deriving DecidableEq, Repr

instance [Denotes Base] : Denotes (Atom1 Base) where
  denote
    | .ofBase code => code
    | .unit => PUnit

instance [Denotes Base] : HasUnit (Atom1 Base) where
  unit := .unit
  encodes := ⟨(Equiv.equivPUnit Unit).symm⟩

instance [Denotes Base] : Denotes (Atom0 Base) where
  denote
    | .ofBase code => code
    | .unit => PUnit
    | .empty => PEmpty

instance [Denotes Base] : HasUnit (Atom0 Base) where
  unit := .unit
  encodes := ⟨(Equiv.equivPUnit Unit).symm⟩

instance [Denotes Base] : HasEmpty (Atom0 Base) where
  empty := .empty
  encodes := ⟨(Equiv.equivPEmpty Empty).symm⟩

instance : Add (SimpTy Base) where
  add := .sum

instance : Mul (SimpTy Base) where
  mul := .prod

/-- `codomain ^ domain` is the code for `domain → codomain`. -/
instance : HomogeneousPow (SimpTy Base) where
  pow codomain domain := .arr domain codomain

/-- Map the atoms of a simple type without changing its type-former tree. -/
def map (f : Base → Target) : SimpTy Base → SimpTy Target
  | .base code => .base (f code)
  | .sum left right => .sum (left.map f) (right.map f)
  | .prod left right => .prod (left.map f) (right.map f)
  | .arr domain codomain => .arr (domain.map f) (codomain.map f)

@[simp] theorem map_base (f : Base → Target) (code : Base) :
    (base code).map f = base (f code) := rfl

@[simp] theorem map_id (code : SimpTy Base) : code.map id = code := by
  induction code <;> simp [map, *]

theorem map_comp (f : Base → Middle) (g : Middle → Target) (code : SimpTy Base) :
    (code.map f).map g = code.map (g ∘ f) := by
  induction code <;> simp [map, Function.comp_def, *]

theorem map_injective (hf : Function.Injective f) : Function.Injective (@map Base Target f) := by
  intro left
  induction left with
  | base code =>
      intro right equality
      cases right with
      | base other => exact congrArg SimpTy.base (hf (SimpTy.base.inj equality))
      | sum | prod | arr => contradiction
  | sum left right ihLeft ihRight =>
      intro other equality
      cases other with
      | base => contradiction
      | sum otherLeft otherRight =>
          exact congrArg₂ SimpTy.sum
            (ihLeft (SimpTy.sum.inj equality).1)
            (ihRight (SimpTy.sum.inj equality).2)
      | prod | arr => contradiction
  | prod left right ihLeft ihRight =>
      intro other equality
      cases other with
      | base | sum => contradiction
      | prod otherLeft otherRight =>
          exact congrArg₂ SimpTy.prod
            (ihLeft (SimpTy.prod.inj equality).1)
            (ihRight (SimpTy.prod.inj equality).2)
      | arr => contradiction
  | arr domain codomain ihDomain ihCodomain =>
      intro other equality
      cases other with
      | base | sum | prod => contradiction
      | arr otherDomain otherCodomain =>
          exact congrArg₂ SimpTy.arr
            (ihDomain (SimpTy.arr.inj equality).1)
            (ihCodomain (SimpTy.arr.inj equality).2)

/-- Interpret a simple type as a Lean type from an interpretation of atoms. -/
def denote (base : Base → Type v) : SimpTy Base → Type v
  | .base code => base code
  | .sum left right => denote base left ⊕ denote base right
  | .prod left right => denote base left × denote base right
  | .arr domain codomain => denote base domain → denote base codomain

instance [Denotes Base] : Denotes (SimpTy Base) where
  denote := denote fun code => code

instance [Denotes Base] : HasCoproduct (SimpTy Base) where
  coproduct := .sum
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] : HasProduct (SimpTy Base) where
  product := .prod
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] : HasExponential (SimpTy Base) where
  exponential := .arr
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] [HasEmpty Base] : HasEmpty (SimpTy Base) where
  empty := .base HasEmpty.empty
  encodes := ⟨HasEmpty.encodes.equiv⟩

instance [Denotes Base] [HasUnit Base] : HasUnit (SimpTy Base) where
  unit := .base HasUnit.unit
  encodes := ⟨HasUnit.encodes.equiv⟩

instance [Denotes Base] [HasNat Base] : HasNat (SimpTy Base) where
  nat := .base HasNat.nat
  encodes := ⟨HasNat.encodes.equiv⟩

instance [Denotes Base] [HasBool Base] : HasBool (SimpTy Base) where
  bool := .base HasBool.bool
  encodes := ⟨HasBool.encodes.equiv⟩

/-- Mapping atoms and then denoting agrees with changing the atom model. -/
def denoteMapEquiv (target : Target → Type v) (f : Base → Target) :
    (code : SimpTy Base) → denote target (code.map f) ≃ denote (target ∘ f) code
  | .base _ => Equiv.refl _
  | .sum left right =>
      Equiv.sumCongr (denoteMapEquiv target f left) (denoteMapEquiv target f right)
  | .prod left right =>
      Equiv.prodCongr (denoteMapEquiv target f left) (denoteMapEquiv target f right)
  | .arr domain codomain =>
      Equiv.arrowCongr (denoteMapEquiv target f domain) (denoteMapEquiv target f codomain)

@[simp] theorem denote_base_id (X : Type u) :
    denote (Base := Type u) id (.base X) = X := rfl

end SimpTy

/-- Simple types with a distinguished unit atom. -/
abbrev SimpTy1 (Base : Type u) := SimpTy (SimpTy.Atom1 Base)

/-- Simple types with distinguished unit and empty atoms. -/
abbrev SimpTy0 (Base : Type u) := SimpTy (SimpTy.Atom0 Base)

namespace SimpTy1

variable {Base : Type u}

def ofBase (code : Base) : SimpTy1 Base := .base (.ofBase code)
def unit : SimpTy1 Base := .base .unit

instance : One (SimpTy1 Base) where one := unit

/-- The canonical positive numeral code. There is deliberately no zero. -/
def positive : Nat → SimpTy1 Base
  | 0 => unit
  | n + 1 => .sum unit (positive n)

instance (n : Nat) : OfNat (SimpTy1 Base) (n + 1) where
  ofNat := positive n

def denoteAtom (base : Base → Type v) : SimpTy.Atom1 Base → Type v
  | .ofBase code => base code
  | .unit => PUnit.{v + 1}

/-- Interpret `SimpTy1`; unit reduces through the distinguished atom. -/
abbrev denote (base : Base → Type v) : SimpTy1 Base → Type v :=
  SimpTy.denote (denoteAtom base)

end SimpTy1

namespace SimpTy

variable {Base : Type u}

/-- Include unit-bearing atoms in the unit-and-empty atom language. -/
def Atom1.toAtom0 : Atom1 Base → Atom0 Base
  | .ofBase code => .ofBase code
  | .unit => .unit

theorem Atom1.toAtom0_injective : Function.Injective (@Atom1.toAtom0 Base) := by
  intro left right equality
  cases left <;> cases right <;> simp_all [Atom1.toAtom0]

end SimpTy

namespace SimpTy0

variable {Base : Type u}

def ofBase (code : Base) : SimpTy0 Base := .base (.ofBase code)
def unit : SimpTy0 Base := .base .unit
def empty : SimpTy0 Base := .base .empty

instance : Zero (SimpTy0 Base) where zero := empty
instance : One (SimpTy0 Base) where one := unit

/-- The canonical numeral code: zero is empty and positive numerals are sums
of units. -/
def numeral : Nat → SimpTy0 Base
  | 0 => empty
  | n + 1 => (SimpTy1.positive n).map SimpTy.Atom1.toAtom0

instance (n : Nat) : OfNat (SimpTy0 Base) n where
  ofNat := numeral n

def denoteAtom (base : Base → Type v) : SimpTy.Atom0 Base → Type v
  | .ofBase code => base code
  | .unit => PUnit.{v + 1}
  | .empty => PEmpty.{v + 1}

/-- Interpret `SimpTy0`; unit and empty reduce through distinguished atoms. -/
abbrev denote (base : Base → Type v) : SimpTy0 Base → Type v :=
  SimpTy.denote (denoteAtom base)

end SimpTy0

namespace SimpTy1

variable {Base : Type u}

/-- Include the no-empty simple types in the language with an empty atom. -/
def toSimpTy0 (code : SimpTy1 Base) : SimpTy0 Base := code.map SimpTy.Atom1.toAtom0

theorem toSimpTy0_injective : Function.Injective (@toSimpTy0 Base) :=
  SimpTy.map_injective SimpTy.Atom1.toAtom0_injective

/-- Inclusion into `SimpTy0` preserves denotation by a canonical equivalence. -/
def denoteToSimpTy0Equiv (base : Base → Type v) (code : SimpTy1 Base) :
    SimpTy0.denote base code.toSimpTy0 ≃ denote base code := match code with
  | .base (.ofBase _) => Equiv.refl _
  | .base .unit => Equiv.refl _
  | .sum left right =>
      Equiv.sumCongr (denoteToSimpTy0Equiv base left) (denoteToSimpTy0Equiv base right)
  | .prod left right =>
      Equiv.prodCongr (denoteToSimpTy0Equiv base left) (denoteToSimpTy0Equiv base right)
  | .arr domain codomain =>
      Equiv.arrowCongr (denoteToSimpTy0Equiv base domain)
        (denoteToSimpTy0Equiv base codomain)

end SimpTy1

section Examples

variable {Base : Type u}

example : (0 : SimpTy0 Empty) = SimpTy0.empty := rfl
example : (1 : SimpTy0 Empty) = SimpTy0.unit := rfl
example : (3 : SimpTy1 Empty) = .sum SimpTy1.unit (.sum SimpTy1.unit SimpTy1.unit) := rfl

example (left right : SimpTy Empty) : left + right = .sum left right := rfl
example (left right : SimpTy Empty) : left * right = .prod left right := rfl
example (domain codomain : SimpTy Empty) : codomain ^ domain = .arr domain codomain := rfl

example (base : Base → Type v) : SimpTy1.denote base SimpTy1.unit = PUnit := rfl
example (base : Base → Type v) : SimpTy0.denote base SimpTy0.empty = PEmpty := rfl

end Examples

end Nucleus
