[package]
name = "covalence-lib-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Minimal safe wrapper over the SQLite C API"
publish = false

[features]
default = []
vfs = ["dep:bitflags", "dep:covalence-data-cas", "dep:covalence-lib-hash"]
vfs-register = ["vfs", "dep:indexmap"]

[dependencies]
bitflags = { version = "2", optional = true }
covalence-data-cas = { path = "../../data/cas", optional = true }
covalence-lib-hash = { path = "../hash", default-features = false, optional = true }
indexmap = { version = "2", optional = true }


[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
sqlite-wasm-rs = { version = "=0.5.5", default-features = false }

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
libsqlite3-sys = { version = "=0.38.1", features = ["bundled"] }

[lints]
workspace = true
