//! Regenerate the committed Lean fixture for the canonical init slice.

use std::{fmt::Write as _, fs, path::PathBuf};

use covalence_lib_json::serde_json;
use covalence_logic_hol::{Kernel, ThmId, init, wire};
use covalence_logic_hol_script::{InitSlice, compile_init_slice};

const LOGICAL_INIT: &str = include_str!("../../../../theories/init-boolean.checked.json");

fn main() {
    let destination = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .expect("usage: freeze_init PATH");
    let manifest: init::Manifest =
        serde_json::from_str(LOGICAL_INIT).expect("logical init manifest must parse");
    let logical = init::compile(&manifest).expect("logical init manifest must check");
    let slice = compile_init_slice(&logical).expect("standard init slice must compile");
    let mut kernel = slice.kernel();
    let proved = slice
        .prove_naturals(&logical, &mut kernel)
        .expect("standard natural package must replay through the checked kernel");
    let theorem_ids = [
        proved.proof.induction,
        proved.proof.succ_injective,
        proved.proof.zero_ne_succ,
    ];
    let theorem_rows = theorem_ids.map(|theorem| serialized_theorem_row(&kernel, theorem));
    let mut bytes = Vec::new();
    wire::serialize(kernel.arena(), &mut bytes)
        .expect("proved standard init arena must serialize canonically");
    assert_serialized_theorems(&kernel, theorem_ids, theorem_rows, &bytes);
    let address =
        kernel
            .arena()
            .addr()
            .as_bytes()
            .iter()
            .fold(String::new(), |mut output, byte| {
                write!(output, "{byte:02x}").unwrap();
                output
            });

    let output = render(&slice, theorem_rows, &bytes, &address);
    fs::write(&destination, output).expect("fixture destination must be writable");
    eprintln!(
        "wrote {} bytes at {address} to {}",
        bytes.len(),
        destination.display()
    );
}

fn serialized_theorem_row(kernel: &Kernel, theorem: ThmId) -> i32 {
    let target = kernel
        .theorems()
        .get(theorem)
        .expect("natural proof theorem must remain live");
    let position = kernel
        .theorems()
        .live_theorems()
        .position(|candidate| candidate == target)
        .expect("live natural theorem must be serialized");
    i32::try_from(position + 1).expect("serialized theorem rows fit in i32")
}

fn assert_serialized_theorems(
    kernel: &Kernel,
    theorem_ids: [ThmId; 3],
    theorem_rows: [i32; 3],
    bytes: &[u8],
) {
    let decoded = wire::deserialize(bytes).expect("generated arena must decode");
    for (source, row) in theorem_ids.into_iter().zip(theorem_rows) {
        let serialized = ThmId::new(row).expect("generated theorem rows are one-based");
        assert_eq!(
            decoded.theorems().get(serialized),
            kernel.theorems().get(source),
            "serialized theorem row must retain its checked natural law"
        );
    }
}

fn render(slice: &InitSlice, theorem_rows: [i32; 3], bytes: &[u8], address: &str) -> String {
    let mut output = String::new();
    output.push_str(
        "import Nucleus.Hol.Ethane.Arena.OneBased.NestedCbor\n\n\
/-! # Canonical checked natural init fixture\n\n\
Generated by the untrusted `covalence-logic-hol-script` userspace frontend.\n\
The userspace natural proof is replayed through the checked kernel before\n\
serialization. These bytes carry no independent proof authority: the production\n\
CBOR decoder reconstructs an `Arena`, and semantic claims must follow from its\n\
checked rows.\n\
-/\n\n\
namespace Nucleus.Hol.Ethane.OneBased.FrozenInit\n\n\
open Nucleus\n\n",
    );
    render_bytes(&mut output, bytes, address);
    output.push_str(
        "/-- Parse and decode the committed bytes through the production Lean decoder. -/\n\
def arena? : Option Layout.Arena :=\n",
    );
    output.push_str("  (CborWire.parse? bytes).bind NestedCbor.decodeArenaByte?\n\n");
    output.push_str(
        "\
/-! ## Frozen natural-package roots\n\n\
These positions are semantic input to the source-independent certificate, not\n\
names recovered from the userspace dictionary. -/\n\n",
    );
    render_natural_roots(&mut output, slice, theorem_rows);
    output.push_str("end Nucleus.Hol.Ethane.OneBased.FrozenInit\n");
    output
}

fn render_bytes(output: &mut String, bytes: &[u8], address: &str) {
    const CHUNK_SIZE: usize = 2_048;
    for (chunk_index, chunk) in bytes.chunks(CHUNK_SIZE).enumerate() {
        writeln!(
            output,
            "private def byteChunk{chunk_index} : ByteArray := ByteArray.mk #["
        )
        .unwrap();
        for line in chunk.chunks(16) {
            output.push_str("  ");
            for (index, byte) in line.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                write!(output, "{byte}").unwrap();
            }
            output.push_str(",\n");
        }
        output.push_str("]\n\n");
    }
    writeln!(
        output,
        "/-- Canonical deterministic CBOR of the opcode-free, proof-bearing init arena\n\
at address `{address}`. -/\n\
def bytes : Bytes := ⟨"
    )
    .unwrap();
    for chunk_index in 0..bytes.len().div_ceil(CHUNK_SIZE) {
        if chunk_index != 0 {
            output.push_str(" ++\n  ");
        }
        write!(output, "byteChunk{chunk_index}").unwrap();
    }
    output.push_str("⟩\n\n");
}

fn render_natural_roots(output: &mut String, slice: &InitSlice, theorem_rows: [i32; 3]) {
    let naturals = slice.naturals();
    for (doc, name, reference) in [
        (
            "The closed natural-number carrier.",
            "naturalCarrier",
            naturals.ty,
        ),
        ("The selected natural zero.", "naturalZero", naturals.zero),
        (
            "The selected natural successor.",
            "naturalSuccessor",
            naturals.succ,
        ),
        (
            "The Boolean induction assertion.",
            "naturalInduction",
            naturals.induction,
        ),
        (
            "The Boolean successor-injectivity assertion.",
            "naturalSuccessorInjective",
            naturals.succ_injective,
        ),
        (
            "The Boolean zero/successor-separation assertion.",
            "naturalZeroNeSuccessor",
            naturals.zero_ne_succ,
        ),
    ] {
        writeln!(
            output,
            "/-- {doc} -/\ndef {name} : Ref := ⟨{}, by decide⟩\n",
            reference.get()
        )
        .unwrap();
    }
    for (doc, name, row) in [
        (
            "One-based serialized HOL theorem row proving natural induction.",
            "naturalInductionTheoremRow",
            theorem_rows[0],
        ),
        (
            "One-based serialized HOL theorem row proving successor injectivity.",
            "naturalSuccessorInjectiveTheoremRow",
            theorem_rows[1],
        ),
        (
            "One-based serialized HOL theorem row proving zero/successor separation.",
            "naturalZeroNeSuccessorTheoremRow",
            theorem_rows[2],
        ),
    ] {
        writeln!(output, "/-- {doc} -/\ndef {name} : Nat := {row}\n").unwrap();
    }
}
