//! Regenerate the committed Lean fixture for the canonical init slice.

use std::{fmt::Write as _, fs, path::PathBuf};

use covalence_lib_json::serde_json;
use covalence_logic_hol::{init, wire};
use covalence_logic_hol_script::{InitSlice, compile_init_slice};

const LOGICAL_INIT: &str = include_str!("../../../../theories/init-boolean.checked.json");

fn main() {
    let destination = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .expect("usage: freeze_init PATH");
    let manifest: init::Manifest =
        serde_json::from_str(LOGICAL_INIT).expect("logical init manifest must parse");
    let logical = init::compile(&manifest).expect("logical init manifest must check");
    let slice = compile_init_slice(&logical).expect("standard init slice must compile");
    let mut bytes = Vec::new();
    wire::serialize(slice.prefix().arena(), &mut bytes)
        .expect("standard init slice must serialize canonically");
    let address =
        slice
            .prefix()
            .addr()
            .as_bytes()
            .iter()
            .fold(String::new(), |mut output, byte| {
                write!(output, "{byte:02x}").unwrap();
                output
            });

    let output = render(&slice, &bytes, &address);
    fs::write(&destination, output).expect("fixture destination must be writable");
    eprintln!(
        "wrote {} bytes at {address} to {}",
        bytes.len(),
        destination.display()
    );
}

fn render(slice: &InitSlice, bytes: &[u8], address: &str) -> String {
    let naturals = slice.naturals();
    let mut output = String::new();
    output.push_str(
        "import Nucleus.Hol.Ethane.Arena.OneBased.NestedCbor\n\n\
/-! # Canonical checked init prefix fixture\n\n\
Generated by the untrusted `covalence-logic-hol-script` userspace frontend.\n\
These bytes carry no proof authority: the production CBOR decoder reconstructs\n\
an `Arena`, and all semantic claims must still be proved from checked rows.\n\
-/\n\n\
namespace Nucleus.Hol.Ethane.OneBased.FrozenInit\n\n\
open Nucleus\n\n\
set_option linter.style.longLine false in\n\
set_option maxHeartbeats 0 in\n\
set_option maxRecDepth 100000 in\n",
    );
    writeln!(
        output,
        "/-- Canonical deterministic CBOR of the projected opcode-free init prefix\n\
at address `{address}`. -/\n\
def bytes : Bytes := ⟨ByteArray.mk #["
    )
    .unwrap();
    for chunk in bytes.chunks(24) {
        output.push_str("  ");
        for (index, byte) in chunk.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            write!(output, "{byte}").unwrap();
        }
        output.push_str(",\n");
    }
    output.push_str("]⟩\n\n");
    output.push_str(
        "/-- Parse and decode the committed bytes through the production Lean decoder. -/\n\
def arena? : Option Layout.Arena :=\n",
    );
    output.push_str("  (CborWire.parse? bytes).bind NestedCbor.decodeArenaByte?\n\n");
    output.push_str(
        "\
/-! ## Frozen natural-package roots\n\n\
These positions are semantic input to the source-independent certificate, not\n\
names recovered from the userspace dictionary. -/\n\n",
    );
    for (doc, name, reference) in [
        (
            "The closed natural-number carrier.",
            "naturalCarrier",
            naturals.ty,
        ),
        ("The selected natural zero.", "naturalZero", naturals.zero),
        (
            "The selected natural successor.",
            "naturalSuccessor",
            naturals.succ,
        ),
        (
            "The Boolean induction assertion.",
            "naturalInduction",
            naturals.induction,
        ),
        (
            "The Boolean successor-injectivity assertion.",
            "naturalSuccessorInjective",
            naturals.succ_injective,
        ),
        (
            "The Boolean zero/successor-separation assertion.",
            "naturalZeroNeSuccessor",
            naturals.zero_ne_succ,
        ),
    ] {
        writeln!(
            output,
            "/-- {doc} -/\ndef {name} : Ref := ⟨{}, by decide⟩\n",
            reference.get()
        )
        .unwrap();
    }
    output.push_str("end Nucleus.Hol.Ethane.OneBased.FrozenInit\n");
    output
}
