//! Static weakenings between flat product types.

use crate::Arity;

/// Returns whether `indices` describe a weakening between the given arities.
///
/// A weakening selects each target element from a distinct source position.
/// Indices must be in range, non-repeating, and equal in number to the target
/// arity. Source elements that do not occur are dropped.
#[must_use]
pub const fn valid_weakening(source_len: usize, target_len: usize, indices: &[usize]) -> bool {
    if indices.len() != target_len || target_len > source_len {
        return false;
    }

    let mut position = 0;
    while position < indices.len() {
        if indices[position] >= source_len {
            return false;
        }

        let mut earlier = 0;
        while earlier < position {
            if indices[earlier] == indices[position] {
                return false;
            }
            earlier += 1;
        }
        position += 1;
    }
    true
}

/// Returns whether `indices` describe a permutation of `len` elements.
#[must_use]
pub const fn is_permutation(len: usize, indices: &[usize]) -> bool {
    valid_weakening(len, len, indices)
}

/// A static weakening from `Source` to a flat product [`Target`](Self::Target).
///
/// Implementations are normally declared with [`define_weakening!`]. The
/// implementing type is a zero-sized witness; [`INDICES`](Self::INDICES)
/// maps each target position to its source position.
///
/// `VALID` checks that the indices are in range and non-repeating.
/// `IS_PERMUTATION` identifies the subset of weakenings that retain every
/// source element.
pub trait Weakening<Source: Arity>: Copy + Default {
    /// The weakened product.
    type Target: Arity;

    /// For each target position, its corresponding source index.
    const INDICES: &'static [usize];

    /// Whether [`INDICES`](Self::INDICES) form a valid weakening.
    const VALID: bool = valid_weakening(Source::LEN, Self::Target::LEN, Self::INDICES);

    /// Whether this weakening is a permutation.
    const IS_PERMUTATION: bool = Self::VALID && Source::LEN == Self::Target::LEN;

    /// Performs the statically described weakening.
    fn weaken(source: Source) -> Self::Target;
}

/// Applies the weakening represented by `W`.
///
/// # Panics
///
/// Panics if a manually written implementation reports an invalid index map.
/// Implementations generated by [`define_weakening!`] are type-checked and
/// valid by construction.
pub fn weaken<Source, W>(source: Source) -> W::Target
where
    Source: Arity,
    W: Weakening<Source>,
{
    assert!(W::VALID, "cannot apply an invalid weakening");
    W::weaken(source)
}

/// Declares a zero-sized static weakening between flat tuples.
///
/// Each target entry names its type parameter and source index. Moving tuple
/// fields makes an out-of-range index, mismatched type, or repeated index a
/// compile error.
///
/// ```
/// use covalence_data_container::{Weakening, define_weakening, weaken};
///
/// define_weakening! {
///     pub DropAndSwap: (A, B, C) => (B @ 1, A @ 0);
/// }
///
/// assert!(DropAndSwap::VALID);
/// assert!(!DropAndSwap::IS_PERMUTATION);
/// assert_eq!(weaken::<_, DropAndSwap>((1_u8, "two", false)), ("two", 1_u8));
/// ```
#[macro_export]
macro_rules! define_weakening {
    (
        $(#[$attribute:meta])*
        $visibility:vis $name:ident:
        ($($source:ident),+ $(,)?) => ($($target:ident @ $index:tt),* $(,)?);
    ) => {
        $(#[$attribute])*
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
        $visibility struct $name;

        impl $name {
            /// For each target position, its corresponding source index.
            pub const INDICES: &'static [usize] = &[$($index),*];

            /// Whether the declared indices form a valid weakening.
            pub const VALID: bool = $crate::valid_weakening(
                [$(stringify!($source)),+].len(),
                Self::INDICES.len(),
                Self::INDICES,
            );

            /// Whether this weakening retains every source position.
            pub const IS_PERMUTATION: bool =
                Self::VALID
                    && [$(stringify!($source)),+].len() == Self::INDICES.len();
        }

        impl<$($source),+> $crate::Weakening<($($source,)+)> for $name {
            type Target = ($($target,)*);

            const INDICES: &'static [usize] = Self::INDICES;
            const VALID: bool = Self::VALID;
            const IS_PERMUTATION: bool = Self::IS_PERMUTATION;

            fn weaken(source: ($($source,)+)) -> Self::Target {
                let _ = &source;
                $crate::__weakening_target!(source; $($index),*)
            }
        }
    };
}

/// Implementation detail for [`define_weakening!`].
#[doc(hidden)]
#[macro_export]
macro_rules! __weakening_target {
    ($source:ident;) => {{
        let _ = &$source;
    }};
    ($source:ident; $($index:tt),+ $(,)?) => {
        ($($source.$index,)+)
    };
}

#[cfg(test)]
mod tests {
    use crate::{is_permutation, valid_weakening, weaken};

    define_weakening! {
        /// Drops the third field and swaps the first two.
        pub DropAndSwap: (A, B, C) => (B @ 1, A @ 0);
    }

    define_weakening! {
        pub Reverse: (A, B, C) => (C @ 2, B @ 1, A @ 0);
    }

    define_weakening! {
        pub DropAll: (A, B, C) => ();
    }

    #[test]
    fn const_validation_distinguishes_weakenings_and_permutations() {
        const VALID: bool = valid_weakening(3, 2, &[1, 0]);
        const REPEATED: bool = valid_weakening(3, 2, &[1, 1]);
        const OUT_OF_RANGE: bool = valid_weakening(3, 1, &[3]);

        const {
            assert!(VALID);
            assert!(!REPEATED);
            assert!(!OUT_OF_RANGE);
            assert!(DropAndSwap::VALID);
            assert!(!DropAndSwap::IS_PERMUTATION);
            assert!(Reverse::IS_PERMUTATION);
            assert!(DropAll::VALID);
        }
        assert!(is_permutation(3, &[2, 0, 1]));
        assert!(!is_permutation(3, &[2, 0]));
    }

    #[test]
    fn generated_witnesses_apply_type_safe_flat_tuple_weakenings() {
        let weakened = weaken::<_, DropAndSwap>((1_u8, String::from("two"), false));
        assert_eq!(weakened, (String::from("two"), 1_u8));

        let reversed = weaken::<_, Reverse>((1_u8, "two", false));
        assert_eq!(reversed, (false, "two", 1_u8));

        weaken::<_, DropAll>((1_u8, "two", false));
    }
}
