import Nucleus.TypeFormers

/-!
# Basic simple types

This is the free simple-type algebra used throughout Nucleus.  It is not tied
to a particular client: forests may use its denotations as index types, while
HOL models may use the same algebra to describe semantic carriers.

`SimpTy` has only caller-supplied atoms and the three binary type formers.
Exponentiation follows cardinal arithmetic: `B ^ A` denotes `A → B`.
-/

namespace Nucleus

universe u v w x

/-- Free simple types generated by atoms, coproducts, products, and functions. -/
inductive SimpTy (Base : Type u) where
  | base (code : Base)
  | sum (left right : SimpTy Base)
  | prod (left right : SimpTy Base)
  | arr (domain codomain : SimpTy Base)
  deriving DecidableEq, Repr

namespace SimpTy

variable {Base : Type u} {Target : Type w} {Middle : Type x}

instance : Add (SimpTy Base) where
  add := .sum

instance : Mul (SimpTy Base) where
  mul := .prod

/-- `codomain ^ domain` is the code for `domain → codomain`. -/
instance : HomogeneousPow (SimpTy Base) where
  pow codomain domain := .arr domain codomain

/-- Map the atoms of a simple type without changing its type-former tree. -/
def map (f : Base → Target) : SimpTy Base → SimpTy Target
  | .base code => .base (f code)
  | .sum left right => .sum (left.map f) (right.map f)
  | .prod left right => .prod (left.map f) (right.map f)
  | .arr domain codomain => .arr (domain.map f) (codomain.map f)

@[simp] theorem map_base (f : Base → Target) (code : Base) :
    (base code).map f = base (f code) := rfl

@[simp] theorem map_id (code : SimpTy Base) : code.map id = code := by
  induction code <;> simp [map, *]

theorem map_comp (f : Base → Middle) (g : Middle → Target) (code : SimpTy Base) :
    (code.map f).map g = code.map (g ∘ f) := by
  induction code <;> simp [map, Function.comp_def, *]

theorem map_injective (hf : Function.Injective f) : Function.Injective (@map Base Target f) := by
  intro left
  induction left with
  | base code =>
      intro right equality
      cases right with
      | base other => exact congrArg SimpTy.base (hf (SimpTy.base.inj equality))
      | sum | prod | arr => contradiction
  | sum left right ihLeft ihRight =>
      intro other equality
      cases other with
      | base => contradiction
      | sum otherLeft otherRight =>
          exact congrArg₂ SimpTy.sum
            (ihLeft (SimpTy.sum.inj equality).1)
            (ihRight (SimpTy.sum.inj equality).2)
      | prod | arr => contradiction
  | prod left right ihLeft ihRight =>
      intro other equality
      cases other with
      | base | sum => contradiction
      | prod otherLeft otherRight =>
          exact congrArg₂ SimpTy.prod
            (ihLeft (SimpTy.prod.inj equality).1)
            (ihRight (SimpTy.prod.inj equality).2)
      | arr => contradiction
  | arr domain codomain ihDomain ihCodomain =>
      intro other equality
      cases other with
      | base | sum | prod => contradiction
      | arr otherDomain otherCodomain =>
          exact congrArg₂ SimpTy.arr
            (ihDomain (SimpTy.arr.inj equality).1)
            (ihCodomain (SimpTy.arr.inj equality).2)

/-- Interpret a simple type as a Lean type from an interpretation of atoms. -/
def denote (base : Base → Type v) : SimpTy Base → Type v
  | .base code => base code
  | .sum left right => denote base left ⊕ denote base right
  | .prod left right => denote base left × denote base right
  | .arr domain codomain => denote base domain → denote base codomain

instance [Denotes Base] : Denotes (SimpTy Base) where
  denote := denote fun code => code

instance [Denotes Base] : HasCoproduct (SimpTy Base) where
  coproduct := .sum
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] : HasProduct (SimpTy Base) where
  product := .prod
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] : HasExponential (SimpTy Base) where
  exponential := .arr
  encodes _ _ := ⟨Equiv.refl _⟩

instance [Denotes Base] [HasEmpty Base] : HasEmpty (SimpTy Base) where
  empty := .base HasEmpty.empty
  encodes := ⟨HasEmpty.encodes.equiv⟩

instance [Denotes Base] [HasUnit Base] : HasUnit (SimpTy Base) where
  unit := .base HasUnit.unit
  encodes := ⟨HasUnit.encodes.equiv⟩

instance [Denotes Base] [HasNat Base] : HasNat (SimpTy Base) where
  nat := .base HasNat.nat
  encodes := ⟨HasNat.encodes.equiv⟩

instance [Denotes Base] [HasBool Base] : HasBool (SimpTy Base) where
  bool := .base HasBool.bool
  encodes := ⟨HasBool.encodes.equiv⟩

/-- Mapping atoms and then denoting agrees with changing the atom model. -/
def denoteMapEquiv (target : Target → Type v) (f : Base → Target) :
    (code : SimpTy Base) → denote target (code.map f) ≃ denote (target ∘ f) code
  | .base _ => Equiv.refl _
  | .sum left right =>
      Equiv.sumCongr (denoteMapEquiv target f left) (denoteMapEquiv target f right)
  | .prod left right =>
      Equiv.prodCongr (denoteMapEquiv target f left) (denoteMapEquiv target f right)
  | .arr domain codomain =>
      Equiv.arrowCongr (denoteMapEquiv target f domain) (denoteMapEquiv target f codomain)

@[simp] theorem denote_base_id (X : Type u) :
    denote (Base := Type u) id (.base X) = X := rfl

end SimpTy

section Examples

example (left right : SimpTy Empty) : left + right = .sum left right := rfl
example (left right : SimpTy Empty) : left * right = .prod left right := rfl
example (domain codomain : SimpTy Empty) : codomain ^ domain = .arr domain codomain := rfl

end Examples

end Nucleus
