[package]
name = "covalence-data-cas-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "HTTP transport for composable content-addressed storage"
publish = false

[dependencies]
axum = "0.8"
axum-extra = { version = "0.10", features = ["typed-header"] }
bytes = "1"
covalence-data-cas = { path = "../cas" }
covalence-lib-error = { path = "../../lib/error" }
covalence-lib-hash = { path = "../../lib/hash", default-features = false, features = ["blake3"] }
covalence-lib-serde = { path = "../../lib/serde" }
covalence-logic-cas = { path = "../../logic/cas" }
futures = "0.3"
headers = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["net", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }

[lints]
workspace = true
