[package]
name = "covalence-logic-sat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Bounded checking for untrusted SAT results"
publish = false

[dependencies]
blake3 = "1"
covalence-logic-lrat = { path = "../lrat" }

[lints]
workspace = true
