[package]
name = "covalence-logic-sat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Typed propositional logic and SAT problems"
publish = false

[dependencies]
covalence-lib-error = { path = "../../lib/error" }

[lints]
workspace = true
