[package]
name = "nucleus-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
nucleus-frontend = { path = "../nucleus-frontend" }
winnow = "0.7.10"
pretty = "0.12.4"
