/-!
# HOL-omega: raw syntax

The content-addressed raw trees, over an abstract `Base` of atoms.

Types and terms are **one indexed family** rather than two mutually recursive
types. They genuinely are mutually recursive — a subtype holds a predicate
term, and terms hold types — but expressing that as a `mutual` block costs more
than it buys:

* `induction` and `cases` work directly on an indexed family. A `mutual` block
  gives no usable `induction` tactic, so every proof has to be spelled out with
  `Expr.rec` and one motive per type, or wrapped in its own `mutual` block.
* `simp` and `omega`-style automation compose with ordinary recursors far
  better than with mutual ones.
* Structural recursion over the family is one definition, not two that have to
  be kept in step by hand.

The one real cost is that constructor names must be distinct across the whole
family, so they cannot be `Ty.app` and `Tm.app`. That turns out to be an
advantage here: naming them after the store's tags — `tyApp`, `tmApp` — makes
the correspondence this development exists to maintain visible at every use
site rather than only in a comment.

It also anticipates where the stack is going. The dialect layer wants a single
type carrying a `sort` function, with the sort-indexed family as its
equivalent presentation; this is already that family, one tag short.

`Ty` and `Tm` remain available as abbreviations, so `Ty Base` and `Tm Base`
still read as types and dot notation still resolves.

## Ranks

Every binder for a type variable carries a rank as well as a kind, so `RKind`
rather than `Kind` is what binders and kind contexts hold.

The rank is not decoration. `TY_ALL` quantifies over the types of a kind, and
if that means *all* of them there is no set-theoretic model: a product indexed
by every type, instantiated at its own type, surjects onto its own double
powerset. Restricting the quantifier to the types below a rank is what makes
`Kernel.Universe` inhabitable, and full HOL-omega carries ranks for exactly
this reason.

Ranks are plain naturals and are always present at the point of import. Unlike
a type or a kind, a rank can never itself be an import, so there are no hole
ranks.
-/

universe u

namespace Nucleus.HolOmega

/-- Kinds, freely generated by `*` and `K ⇒ L`. -/
inductive Kind : Type
  | star : Kind
  | arr : Kind → Kind → Kind
  deriving DecidableEq, Repr

/-- A kind together with the rank its variables range over. -/
structure RKind where
  kind : Kind
  rank : Nat
  deriving DecidableEq, Repr

/-- The two syntactic sorts of the raw language. -/
inductive ExprSort : Type
  | ty
  | tm
  deriving DecidableEq, Repr

/-- Raw syntax trees, indexed by sort.

Every constructor is one tag of the store's vocabulary. `tySub` carries its
predicate as a term, checked in the fixed context determined by the carrier
rather than in the ambient one — which is what makes a subtype independently
addressable. -/
inductive Expr (Base : Type u) : ExprSort → Type u
  | base : Base → Expr Base .ty
  | tyVar : Nat → Expr Base .ty
  | tyLam : RKind → Expr Base .ty → Expr Base .ty
  | tyApp : Expr Base .ty → Expr Base .ty → Expr Base .ty
  | tyAll : RKind → Expr Base .ty → Expr Base .ty
  /-- Raw/store extension: primitive existential type.  This constructor has
  no persisted store tag yet; see `crates/nucleus/src/hol/semantics.txt`. -/
  | tyEx : RKind → Expr Base .ty → Expr Base .ty
  | tyBool : Expr Base .ty
  | tyArr : Expr Base .ty → Expr Base .ty → Expr Base .ty
  | tySub : Expr Base .ty → Expr Base .tm → Expr Base .ty
  | tmVar : Nat → Expr Base .tm
  | tmApp : Expr Base .tm → Expr Base .tm → Expr Base .tm
  | tmLam : Expr Base .ty → Expr Base .tm → Expr Base .tm
  | tmTyApp : Expr Base .tm → Expr Base .ty → Expr Base .tm
  | tmTyLam : RKind → Expr Base .tm → Expr Base .tm
  /-- Raw/store extension: package a witness type and payload for family `A`. -/
  | tmPack : RKind → Expr Base .ty → Expr Base .ty → Expr Base .tm → Expr Base .tm
  /-- Raw/store extension: eliminate a package with annotated family and
  witness-independent answer type. -/
  | tmUnpack : RKind → Expr Base .ty → Expr Base .ty → Expr Base .tm →
      Expr Base .tm → Expr Base .tm
  | tmBool : Bool → Expr Base .tm
  | tmEq : Expr Base .ty → Expr Base .tm → Expr Base .tm → Expr Base .tm
  | tmEps : Expr Base .ty → Expr Base .tm → Expr Base .tm
  | tmAbs : Expr Base .ty → Expr Base .tm → Expr Base .tm → Expr Base .tm
  | tmRep : Expr Base .ty → Expr Base .tm → Expr Base .tm → Expr Base .tm

/-- Raw type trees. -/
abbrev Ty (Base : Type u) := Expr Base .ty

/-- Raw term trees. -/
abbrev Tm (Base : Type u) := Expr Base .tm

/-- A kind context. -/
abbrev KindCtx := List RKind

/-- A variable context. -/
abbrev TmCtx (Base : Type u) := List (Ty Base)

/-- A hypothesis set. -/
abbrev Hyps (Base : Type u) := List (Tm Base)

end Nucleus.HolOmega
